'use strict';
/**
 * HUMANIZER — English (en)
 * Pure simple English. No Hindi words, no technical astrology tokens
 * (no "Ascendant", "Lagna", "Mahadasha", house numbers). The humanizer's job is
 * to convert astrology data into simple, warm life-guidance language WITHIN English.
 */
module.exports = {
  lang: 'en',

  HOUSE_THEME: {
    1: 'yourself, health, nature and identity', 2: 'money, family, speech and savings',
    3: 'courage, siblings, effort and communication', 4: 'home, mother, comfort and property',
    5: 'children, education, intelligence and love', 6: 'loans, health, rivals and competition',
    7: 'marriage, partner and partnerships', 8: 'ups and downs, longevity and sudden events',
    9: 'luck, faith, mentors and long journeys', 10: 'career, job, position and reputation',
    11: 'income, gains, wishes and friends', 12: 'expenses, foreign matters, peace and solitude',
  },

  AREA_LABEL: {
    summary: 'Your Snapshot', personality: 'Your Personality', family: 'Family & Home',
    career: 'Career & Job', money: 'Business & Money', marriage: 'Marriage & Partner',
    children: 'Children', siblings: 'Siblings & Friends', health: 'Health',
    debt: 'Loans & Disputes', property: 'Property, Vehicle & Comfort', spirituality: 'Luck & Spirituality',
    dasha: 'Your Current Phase', daily: "Today's Guidance", yogas: 'Special Strengths in Your Chart', remedies: 'Simple Remedies',
  },

  SCORE_LABEL: {
    5: 'this area looks very strong', 4: 'this area looks strong',
    3: 'this area is balanced', 2: 'this area needs patience and care',
    1: 'this area needs special attention and effort',
  },

  PLANET: {
    Sun: { name: 'Sun', energy: 'confidence, responsibility, leadership and decisions', focus: 'position, recognition, authority and respect',
      dasha: { theme: 'This period can make you more responsible, active and decision-driven. Identity, career and respect may become more important now.',
        good: 'Recognition, a better position and support from seniors are possible.', challenge: 'Watch for ego clashes with authority figures and some fatigue.',
        do: 'Lead with honesty and effort, and rise early.', avoid: 'Pride and acting in haste against others.' } },
    Moon: { name: 'Moon', energy: 'the mind, emotions, calm and relationships', focus: 'mind, mother, home and relationships',
      dasha: { theme: 'This period is connected to your mind and emotions. Relationships, home and inner peace will matter more to you now.',
        good: 'Popularity, warm relationships and peace of mind are supported.', challenge: 'Mood swings and overthinking can disturb you.',
        do: 'Keep the mind calm and spend time with family.', avoid: 'Emotional, hasty decisions.' } },
    Mars: { name: 'Mars', energy: 'energy, courage, hard work and quick decisions', focus: 'courage, property, siblings and competition',
      dasha: { theme: 'This period can make you more active, courageous and result-focused. Property, competition and technical work may open up.',
        good: 'Courage helps stuck work move; gains through property and competition.', challenge: 'Watch for anger, haste or small injuries.',
        do: 'Channel your energy into the right direction and exercise.', avoid: 'Conflict driven by anger and impatience.' } },
    Mercury: { name: 'Mercury', energy: 'intelligence, business, communication and accounts', focus: 'study, business, communication and accounts',
      dasha: { theme: 'This period is connected to thinking, study and communication. Business, writing and contacts can bring gains through your intellect.',
        good: 'Business, new contacts and learning go well.', challenge: 'Overthinking and confusion in decisions.',
        do: 'Work with a clear plan and clean accounts.', avoid: 'Dishonesty or rushed deals.' } },
    Jupiter: { name: 'Jupiter', energy: 'wisdom, luck and growth in life', focus: 'wisdom, luck, education and auspicious work',
      dasha: { theme: 'This period brings wisdom, luck and positivity. Education, marriage, children and faith-related matters may become active.',
        good: 'Support of luck, respect and completion of good work.', challenge: 'Over-optimism, and keep an eye on health.',
        do: 'Respect elders and mentors, and stay honest.', avoid: 'Big promises made on over-confidence.' } },
    Venus: { name: 'Venus', energy: 'love, comfort, art and beauty', focus: 'relationships, comfort, money and lifestyle',
      dasha: { theme: 'This period is connected to comfort, love and creativity. Marriage, relationships and lifestyle matters may become more important now.',
        good: 'Sweetness in relationships, comforts and gains through art.', challenge: 'Too much indulgence and drifting in relationships.',
        do: 'Give value to relationships and creative work.', avoid: 'Overspending and excess comfort-seeking.' } },
    Saturn: { name: 'Saturn', energy: 'discipline, hard work, patience and responsibility', focus: 'hard work, responsibility, job and patience',
      dasha: { theme: 'This period asks for hard work, patience and responsibility. Results come slowly but solidly — discipline makes success last.',
        good: 'Lasting rewards for effort and stability at work.', challenge: 'Watch for delays, tiredness or low moods.',
        do: 'Stay patient, work by the rules, and help elders and workers.', avoid: 'Shortcuts, dishonesty and laziness.' } },
    Rahu: { name: 'Rahu', energy: 'ambition, change and new fields', focus: 'ambition, foreign matters, technology and change',
      dasha: { theme: 'This period brings strong ambition and change. Foreign matters, technology and sudden ups and downs may appear.',
        good: 'Sudden growth, new opportunities and gains through foreign or tech areas.', challenge: 'Beware of confusion, deception and haste.',
        do: 'Keep your thinking clear and check every big step carefully.', avoid: 'Shortcuts, wrong company and greed.' } },
    Ketu: { name: 'Ketu', energy: 'detachment, spirituality and inner change', focus: 'spirituality, practice and inner change',
      dasha: { theme: 'This is a more inward, spiritual period. Attachments soften and interest grows in practice and deeper understanding.',
        good: 'Spiritual growth and freedom from needless attachment.', challenge: 'Some confusion, disinterest or a sense of distance.',
        do: 'Take up meditation, spiritual practice and a simpler life.', avoid: 'Big, risky decisions.' } },
  },

  SIGN: {
    1:  { name: 'Aries',       nature: 'courageous, energetic and quick to start new things',     manas: 'your mind is fast and impatient — quick to excite, quick to settle' },
    2:  { name: 'Taurus',      nature: 'steady, patient and practical',                            manas: 'your mind stays calm and lasting, but resists change' },
    3:  { name: 'Gemini',      nature: 'intelligent, talkative and curious',                       manas: 'your mind is restless and feels lighter through conversation' },
    4:  { name: 'Cancer',      nature: 'emotional, caring and family-loving',                      manas: 'your mind is soft and sensitive, easily affected' },
    5:  { name: 'Leo',         nature: 'confident, generous and natural at leading',               manas: 'your mind needs respect and appreciation' },
    6:  { name: 'Virgo',       nature: 'practical, analytical and hard-working',                   manas: 'your mind analyses a lot and worries over small things' },
    7:  { name: 'Libra',       nature: 'balanced, fair-minded and friendly',                       manas: 'your mind seeks harmony and tires from conflict' },
    8:  { name: 'Scorpio',     nature: 'deep, determined and private',                             manas: 'your mind is deep and intense, keeping feelings inside' },
    9:  { name: 'Sagittarius', nature: 'optimistic, honest and independent',                       manas: 'your mind is hopeful and free, finding peace in faith' },
    10: { name: 'Capricorn',   nature: 'disciplined, responsible and hard-working',                manas: 'your mind is serious and dutiful, showing few emotions' },
    11: { name: 'Aquarius',    nature: 'original-thinking, social and humane',                      manas: 'your mind is free and thoughtful' },
    12: { name: 'Pisces',      nature: 'imaginative, kind and spiritual',                          manas: "your mind is emotional and dreamy, absorbing others' feelings" },
  },

  NAKSHATRA: {
    1:'quick, independent and a fast starter', 2:'firm in resolve with strong endurance', 3:'sharp, outspoken and a leader',
    4:'attractive, creative and loving', 5:'gentle, curious and a little restless', 6:'spirited and curious but sometimes uneasy',
    7:'friendly, positive and sensible', 8:'calm, nurturing and dependable', 9:'deep-thinking, intuitive and clever — sensitive in emotions',
    10:'self-respecting and a natural leader', 11:'creative, easygoing and sociable', 12:'hard-working, service-minded and responsible',
    13:'skilful and clear-thinking', 14:'artistic, charming and organised', 15:'flexible, friendly and independent',
    16:'goal-focused, energetic and firm', 17:'friendly, devoted and balanced', 18:'brave, leading and a little stubborn',
    19:'serious, searching and transformative', 20:'patient, hard-working with lasting success', 21:'disciplined, responsible and a winner',
    22:'a learner, sensible and good with contacts', 23:'ambitious and generous', 24:'thoughtful, searching and spiritual',
    25:'wise, deep and spiritually inclined', 26:'steady, hard-working and dependable', 27:'gentle, kind and imaginative',
  },

  DIGNITY: {
    exalted: 'in a very strong position', moolatrikona: 'in a very good position', own: 'in a strong, natural position',
    great_friend: 'in a good position', friend: 'in a good position', neutral: 'in an average position',
    enemy: 'in a slightly weak position', great_enemy: 'in a weak position',
    debilitated: 'in a weak position — this needs a little extra care and effort',
  },

  TARA: {
    Janma: 'Your mind may feel a little sensitive today, so take big decisions calmly.',
    Sampat: 'A good day for money and work-related matters.',
    Vipat: 'Keep some caution today — better to avoid risk and arguments.',
    Kshema: 'A steady, favourable day — you can move ahead.',
    Pratyak: 'Small hurdles may come up today; stay patient.',
    Sadhana: 'A good day for effort and finishing pending work.',
    Naidhana: 'Avoid conflict and risk today, and keep the mind calm.',
    Mitra: 'A good day for relationships and cooperation.',
    'Parama Mitra': 'A specially favourable day for you — get important things done.',
  },

  YOGA_RULES: [
    { match: /raj/i, text: 'with effort and the right opportunity, it can bring respect and a good position in life.' },
    { match: /dhana|dhan/i, text: 'it gives a good ability to earn and build wealth.' },
    { match: /lakshmi|laxmi/i, text: 'it points towards comfort, beauty and prosperity.' },
    { match: /gajakesari|gaj/i, text: 'it gives intelligence, respect and a good name among people.' },
    { match: /budh.?aditya|nipun|saraswat/i, text: 'it sharpens intelligence, study and communication.' },
    { match: /chandra.?mangal/i, text: 'it gives practical money-making chances; but keep spending and temper in check.' },
    { match: /adhi/i, text: 'it points to good advisors, support and a leadership position.' },
    { match: /parivartan/i, text: 'it links two areas of life — over time it brings good changes.' },
    { match: /neecha.?bhanga/i, text: 'an early weakness can later turn into a strength.' },
    { match: /vipreet|viparit/i, text: 'difficult situations can later bring unexpected gains.' },
    { match: /hamsa/i, text: 'it brings respect through wisdom and a good nature.' },
    { match: /malavya/i, text: 'it points to comfort, beauty and material ease.' },
    { match: /ruchaka/i, text: 'it lifts you up through courage and hard work.' },
    { match: /bhadra/i, text: 'it gives success in intelligence, business and communication.' },
    { match: /sasa|shasha/i, text: 'discipline and hard work bring authority and lasting success.' },
  ],
  YOGA_DEFAULT: 'this is a supportive combination that strengthens some areas of life.',

  PHRASES: {
    but: ', but ',
    dashaAlso: ' Alongside, matters related to {focus} may also become more important now.',
    dashaGeneric: 'The energy of this phase is gently moving your life forward.',
    goodSide: 'Good side: {x}', whatToDo: 'What to do: {x}', avoidThese: 'Avoid: {x}',
    sumNature: 'By nature you are {nature}, and {manas}.',
    sumInner: ' Deep inside, you are {nak}.',
    sumBest: '{area} — this area looks favourable for you right now.',
    sumWeak: 'On the other hand, {area} — here a little patience and care will help.',
    sumClose: 'Avoid haste — with effort and the right direction, life can bring good results.',
    yogasIntro: 'Your chart carries a few supportive combinations; their simple meaning is below:',
    yogasNone: 'Your chart carries ordinary combinations; effort and the right direction bring good results.',
    remediesIntro: 'These remedies are simple, safe and free — meant for balance and positivity, never for fear:',
    healthDisclaimer: 'These are astrological pointers only — for any health problem, please do consult a doctor.',
    dailyMood: 'Your mind should feel steady today.',
    dailyWork: 'Work: {x}', dailyWorkFallback: 'A day to focus on your work.',
    dailyRel: 'Relationships: keep your words gentle with loved ones today.',
    dailyHealth: 'Health: timely meals and a little rest are important.',
    dailyAdvice: 'Whatever you do today, do it with a calm mind and patience.',
    dailyCaution: 'Avoid haste and anger.',
  },

  REMEDIES: {
    base: [
      'Offer water to the Sun and build the habit of waking up early.',
      'Spend a few minutes daily in meditation or deep breathing — the mind stays calm and steady.',
      'Respect your parents and elders — this is the most effective remedy.',
      'Donate food or grains to those in need.',
      'Avoid anger and haste; walk the path of truth and honesty.',
    ],
    money: 'Read the Hanuman Chalisa on Tuesday/Saturday; avoid unthinking loans or risky investments.',
    health: 'Donate something white (milk/rice) on Monday and keep a regular daily routine.',
    career: 'Help hard-working and elderly people on Saturday; stay disciplined.',
    marriage: 'Talk more openly with your partner; donating something white/fragrant on Friday is good.',
    children: 'Donate yellow items / split gram on Thursday and seek the blessings of elders.',
    spirituality: 'Chanting the Gayatri Mantra on Thursday and a little service work will strengthen the mind.',
  },
};
