#!/usr/bin/env bash
# Full deployment script for Jyotish Stack AI.
# Run on the production server as the deploy user:
#   APP_DIR=/var/www/jyotish-stack bash deploy.sh
#
# Optional overrides (all have sane defaults):
#   APP_DIR        repo location              (default: /var/www/jyotish-stack)
#   BRANCH         git branch to deploy       (default: main)
#   API_INSTANCES  PM2 cluster size for API   (default: 1, read by ecosystem.config.js)
#   UI_INSTANCES   PM2 cluster size for UI    (default: 1, read by ecosystem.config.js)
#   RUN_SEED       run production seeds       (default: 0; set to 1 only when intentional)
#   SEED_SPECIFIC  run one specific seed file (e.g. SEED_SPECIFIC=019_judgement_rules.js)
#
# NOTE: migrations run from server/ so dotenv loads server/.env. The knexfile
# production block has no fallback defaults — server/.env MUST exist on the box.

set -euo pipefail

# Exported so the Node process behind `pm2 reload ecosystem.config.js` reads them at
# config-eval time (cwd/instances). NOTE: we deliberately do NOT export NODE_ENV=production
# globally — that makes `npm install` skip devDependencies and breaks `next build`
# (Cannot find module 'tailwindcss'). NODE_ENV is set inline only where it's actually needed.
export APP_DIR="${APP_DIR:-/var/www/jyotish-stack}"
export BRANCH="${BRANCH:-main}"
export API_INSTANCES="${API_INSTANCES:-1}"
export UI_INSTANCES="${UI_INSTANCES:-1}"
export RUN_SEED="${RUN_SEED:-0}"
export SEED_SPECIFIC="${SEED_SPECIFIC:-}"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: Required command '$1' was not found on PATH." >&2
    exit 1
  fi
}

log "Jyotish Stack AI deploy starting"
log "App dir: ${APP_DIR} | Branch: ${BRANCH} | API x${API_INSTANCES} | UI x${UI_INSTANCES} | RUN_SEED=${RUN_SEED}"

for cmd in git npm pm2 curl sudo apache2ctl systemctl python3; do
  require_cmd "$cmd"
done

if [ ! -d "$APP_DIR/.git" ]; then
  echo "ERROR: ${APP_DIR} is not a git checkout. Clone the repo there first." >&2
  exit 1
fi
if [ ! -f "$APP_DIR/server/.env" ]; then
  echo "ERROR: ${APP_DIR}/server/.env not found. Copy .env.production.example and fill it in." >&2
  exit 1
fi

cd "$APP_DIR"

log "Pulling latest code..."
git fetch origin "$BRANCH"
git checkout "$BRANCH"
git pull --ff-only origin "$BRANCH"

log "Installing workspace dependencies (incl. build tools needed by next build)..."
npm install --include=dev

log "Preparing the local Python question-understanding service..."
QUESTION_SERVICE_DIR="$APP_DIR/question-service"
if [ ! -d "$QUESTION_SERVICE_DIR/.venv" ]; then
  if ! python3 -m venv "$QUESTION_SERVICE_DIR/.venv"; then
    echo "ERROR: Could not create the Python virtual environment. Install python3-venv and run deploy.sh again." >&2
    exit 1
  fi
fi
"$QUESTION_SERVICE_DIR/.venv/bin/pip" install --disable-pip-version-check -r "$QUESTION_SERVICE_DIR/requirements.txt"

log "Running database migrations (from server/ so server/.env is loaded)..."
( cd "$APP_DIR/server" && NODE_ENV=production npm run migrate )

if [ -n "$SEED_SPECIFIC" ]; then
  log "Running specific seed: ${SEED_SPECIFIC}..."
  ( cd "$APP_DIR/server" && NODE_ENV=production npx knex seed:run --specific="$SEED_SPECIFIC" )
elif [ "$RUN_SEED" = "1" ]; then
  log "Running all database seeds because RUN_SEED=1..."
  ( cd "$APP_DIR/server" && NODE_ENV=production npm run seed )
else
  log "Skipping seeds. Use SEED_SPECIFIC=<file> for one seed, or RUN_SEED=1 for all."
fi

log "Building public Next.js app into a release directory..."
UI_DIR="$APP_DIR/ui-main"
NEXT_RELEASE_DIR=".next-release"
NEXT_PREVIOUS_DIR=".next-previous"

rm -rf "$UI_DIR/$NEXT_RELEASE_DIR" "$UI_DIR/$NEXT_PREVIOUS_DIR"
NEXT_DIST_DIR="$NEXT_RELEASE_DIR" NODE_ENV=production npm run build:main

# Keep the previous build's content-hashed assets available. Browser tabs that
# were open during a deploy may still request those files after the new build
# becomes active. Never overwrite files generated by the new build.
if [ -d "$UI_DIR/.next/static" ]; then
  log "Preserving previous Next.js static chunks for open browser sessions..."
  mkdir -p "$UI_DIR/$NEXT_RELEASE_DIR/static"
  cp -a -n "$UI_DIR/.next/static/." "$UI_DIR/$NEXT_RELEASE_DIR/static/"
fi

# Both directories are on the same filesystem, so each rename is atomic. The
# release already contains the previous static assets before it becomes live.
if [ -d "$UI_DIR/.next" ]; then
  mv "$UI_DIR/.next" "$UI_DIR/$NEXT_PREVIOUS_DIR"
fi
mv "$UI_DIR/$NEXT_RELEASE_DIR" "$UI_DIR/.next"

log "Starting or reloading PM2 processes..."
pm2 startOrReload ecosystem.config.js --env production --update-env
pm2 save

# PM2 now serves the new release. The active `.next/static` already includes
# the previous content-hashed assets, so the old server directory is redundant.
rm -rf "$UI_DIR/$NEXT_PREVIOUS_DIR"

log "Reloading Apache..."
sudo apache2ctl configtest && sudo systemctl reload apache2

log "Smoke-testing API health endpoint..."
ok=0
for i in 1 2 3 4 5 6; do
  if curl -fsS --max-time 5 http://127.0.0.1:5000/health >/dev/null 2>&1; then
    ok=1
    break
  fi
  log "  health check attempt ${i} failed; retrying in 3s..."
  sleep 3
done
if [ "$ok" -ne 1 ]; then
  echo "ERROR: API did not become healthy on http://127.0.0.1:5000/health" >&2
  log "Recent API logs:"
  pm2 logs jyotish-api --lines 30 --nostream || true
  exit 1
fi

log "Smoke-testing question-understanding service..."
question_ok=0
for i in 1 2 3 4 5 6; do
  if curl -fsS --max-time 5 http://127.0.0.1:5100/health >/dev/null 2>&1; then
    question_ok=1
    break
  fi
  log "  question service health attempt ${i} failed; retrying in 2s..."
  sleep 2
done
if [ "$question_ok" -ne 1 ]; then
  echo "ERROR: Question service did not become healthy on http://127.0.0.1:5100/health" >&2
  pm2 logs jyotish-question-nlp --lines 30 --nostream || true
  exit 1
fi

log "Deployment complete."
log "API: http://127.0.0.1:5000/health"
log "Question understanding: http://127.0.0.1:5100/health"
log "UI:  http://127.0.0.1:3000"
