import LegalPage from '../../components/LegalPage';

export const metadata = {
  title: 'Terms & Conditions',
  description: 'Terms and Conditions governing the use of Jyotish Stack AI platform.',
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      subtitle="Please read these terms carefully before using the Jyotish Stack AI platform."
      lastUpdated="June 2026"
      currentHref="/terms"
    >
      <div className="notice-box">
        <p>By accessing or using Jyotish Stack AI, you agree to be bound by these Terms and Conditions. If you do not agree, please discontinue use of the Platform immediately.</p>
      </div>

      <h2>1. Definitions</h2>
      <p><strong>"Platform"</strong> refers to the Jyotish Stack AI website and all associated services accessible at jyotishstack.com, jyotishstack.in, jyotishstackai.com, and jyotishstackai.in.</p>
      <p><strong>"User", "you", "your"</strong> refers to any individual who accesses, registers on, or uses the Platform.</p>
      <p><strong>"We", "us", "our"</strong> refers to Jyotish Stack AI, the operator of this Platform.</p>
      <p><strong>"Astrological Content"</strong> refers to Kundli charts, planetary readings, dasha analysis, predictions, matchmaking reports, and all other astrology-related outputs generated by the Platform.</p>

      <h2>2. Acceptance of Terms</h2>
      <p>These Terms constitute a legally binding agreement between you and Jyotish Stack AI. By creating an account, you represent that you have read, understood, and agree to be bound by these Terms, along with our <a href="/privacy">Privacy Policy</a>, <a href="/refund-policy">Refund Policy</a>, and <a href="/disclaimer">Disclaimer</a>.</p>

      <h2>3. Eligibility</h2>
      <p>You must be at least <strong>18 years of age</strong> to use the Platform. By using the Platform, you represent and warrant that you meet this age requirement. We do not knowingly provide services to minors.</p>

      <h2>4. Services</h2>
      <p>Jyotish Stack AI provides AI-assisted Vedic astrology services, including but not limited to:</p>
      <ul>
        <li>Kundli (Janam Patrika / birth chart) generation and analysis</li>
        <li>Dasha and Antardasha timeline analysis (Vimshottari, Yogini)</li>
        <li>Kundli matchmaking and Guna Milan (for marriage compatibility)</li>
        <li>Daily, weekly, and monthly astrological predictions (Bhavishya Vani)</li>
        <li>Panchang (Hindu almanac) and Muhurta (auspicious timing) calculations</li>
        <li>Varshphal (Solar Return / annual chart) analysis</li>
        <li>Divisional chart (Varga) analysis</li>
        <li>Nakshatra, planetary strength, and Yoga analysis</li>
      </ul>
      <p>We reserve the right to modify, suspend, or discontinue any service with or without notice.</p>

      <h2>5. User Accounts</h2>
      <p>To access most services, you must register for an account. You agree to:</p>
      <ul>
        <li>Provide accurate, complete, and current information during registration</li>
        <li>Maintain the security of your account password</li>
        <li>Immediately notify us of any unauthorized use of your account</li>
        <li>Accept responsibility for all activities that occur under your account</li>
      </ul>
      <p>You may not create multiple accounts to circumvent subscription limits or access restrictions.</p>

      <h2>6. Subscription Plans and Payments</h2>
      <p>Access to premium features requires a paid subscription:</p>
      <ul>
        <li><strong>Free Plan</strong> — Create a Kundli profile; no analysis access</li>
        <li><strong>Basic Plan (₹200/month)</strong> — Full Kundli analysis access for 1 profile</li>
        <li><strong>Premium Plan (₹499/month)</strong> — Full access for up to 5 profiles, PDF download</li>
        <li><strong>Yearly Plan (₹3,999/year)</strong> — Full access for up to 50 profiles, all features</li>
      </ul>
      <p>All prices are in Indian Rupees (INR) and are <strong>inclusive of applicable GST</strong> as required under Indian tax law. Payments are processed securely via Razorpay. By completing a purchase, you authorize Razorpay to charge your selected payment method. Please refer to our <a href="/refund-policy">Refund & Cancellation Policy</a> for details on refunds.</p>

      <h2>7. Critical: Astrological Content Disclaimer</h2>
      <div className="warn-box">
        <p><strong>⚠ Please read this section carefully.</strong> All astrological content provided by Jyotish Stack AI is for <strong>guidance, spiritual insight, and entertainment purposes only</strong>. Astrological predictions are NOT scientifically proven facts. We make no guarantee of accuracy, completeness, or reliability of any astrological prediction. Do NOT make major life decisions — including medical, legal, financial, or relationship decisions — based solely on astrological content from this Platform.</p>
      </div>
      <p>For the complete disclaimer, please read our <a href="/disclaimer">Disclaimer page</a>.</p>

      <h2>8. Intellectual Property</h2>
      <p>All content on the Platform — including text, graphics, logos, software, AI models, and Astrological Content generated by our systems — is the property of Jyotish Stack AI and is protected under applicable Indian and international intellectual property laws.</p>
      <p>You may not copy, reproduce, distribute, modify, or create derivative works from Platform content without our express written permission. However, you retain ownership of the personal birth data you submit; we use it only to provide the requested services.</p>

      <h2>9. Prohibited Conduct</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Share, sell, or transfer your account credentials to any third party</li>
        <li>Use the Platform for any unlawful purpose under Indian or applicable law</li>
        <li>Attempt to reverse-engineer, decompile, or extract the Platform's source code or AI models</li>
        <li>Submit false, fraudulent, or misleading information</li>
        <li>Scrape, crawl, or systematically extract data from the Platform</li>
        <li>Use automated tools to access the Platform in ways that circumvent normal usage patterns</li>
        <li>Circumvent any access controls, subscription limits, or usage restrictions</li>
        <li>Interfere with the operation or security of the Platform</li>
      </ul>

      <h2>10. Privacy</h2>
      <p>Our collection and use of your personal information, including Kundli birth data, is governed by our <a href="/privacy">Privacy Policy</a>, which forms an integral part of these Terms.</p>

      <h2>11. Third-Party Services</h2>
      <p>The Platform integrates third-party services including Razorpay for payment processing. Your use of these services is subject to their respective terms and privacy policies. We are not responsible for the practices of third-party service providers.</p>

      <h2>12. Disclaimers and Limitation of Liability</h2>
      <p>To the maximum extent permitted by applicable law:</p>
      <ul>
        <li>The Platform is provided on an "as is" and "as available" basis without warranties of any kind</li>
        <li>We do not warrant that the Platform will be uninterrupted, error-free, or free of viruses</li>
        <li>We shall not be liable for any indirect, incidental, special, consequential, or punitive damages</li>
        <li>Our total liability to you for any claim shall not exceed the total amount you paid us in the three (3) months immediately preceding the event giving rise to the claim</li>
      </ul>

      <h2>13. Termination</h2>
      <p>We reserve the right to suspend or permanently terminate your account and access to the Platform if you violate these Terms, engage in fraudulent activity, or if we determine, at our sole discretion, that your continued use is harmful to the Platform or other users. You may terminate your account at any time from your account dashboard.</p>

      <h2>14. Governing Law and Jurisdiction</h2>
      <p>These Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles. Any disputes arising out of or relating to these Terms or the Platform shall be subject to the exclusive jurisdiction of the competent courts in India.</p>

      <h2>15. Grievance Redressal</h2>
      <p>In accordance with the Information Technology Act, 2000 and Consumer Protection (E-Commerce) Rules, 2020, we have designated a Grievance Officer:</p>
      <div className="notice-box">
        <p><strong>Grievance Officer:</strong> Jyotish Stack AI Support Team<br />
        <strong>Email:</strong> <a href="mailto:legal@jyotishstack.com">legal@jyotishstack.com</a><br />
        <strong>Response Time:</strong> We will acknowledge your grievance within 48 hours and endeavour to resolve it within 30 days of receipt.</p>
      </div>

      <h2>16. Changes to These Terms</h2>
      <p>We reserve the right to modify these Terms at any time. When we make material changes, we will update the "Last Updated" date at the top of this page and, where appropriate, notify you via email. Your continued use of the Platform after any changes constitutes your acceptance of the revised Terms.</p>

      <h2>17. Contact</h2>
      <p>For any questions or concerns about these Terms, please contact us at:</p>
      <ul>
        <li><strong>Email:</strong> <a href="mailto:support@jyotishstack.com">support@jyotishstack.com</a></li>
        <li><strong>Legal:</strong> <a href="mailto:legal@jyotishstack.com">legal@jyotishstack.com</a></li>
        <li><strong>Website:</strong> <a href="https://jyotishstack.com">jyotishstack.com</a></li>
      </ul>
    </LegalPage>
  );
}
