#!/usr/bin/env bash
# Configure a self-hosted mail server for Jyotish Stack AI on Ubuntu.
# Run on the VPS as root:
#   sudo bash scripts/setup-self-hosted-smtp.sh jyotishstack.com
#
# Creates these mailboxes by default:
#   sales@DOMAIN, team@DOMAIN, account@DOMAIN
#
# Passwords are generated once and stored at /root/jyotish-mailbox-passwords.txt.

set -euo pipefail

DOMAIN="${1:-${MAIL_DOMAIN:-jyotishstack.com}}"
MAIL_HOST="${MAIL_HOST:-mail.${DOMAIN}}"
PASSWORD_FILE="${PASSWORD_FILE:-/root/jyotish-mailbox-passwords.txt}"
DNS_FILE="${DNS_FILE:-/root/jyotish-mail-dns-records.txt}"
MAILBOXES=(sales team account)

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

if [ "$(id -u)" -ne 0 ]; then
  die "Run this script as root with sudo."
fi

if ! [[ "$DOMAIN" =~ ^[A-Za-z0-9.-]+$ ]]; then
  die "Invalid domain: $DOMAIN"
fi

if ! [[ "$MAIL_HOST" =~ ^[A-Za-z0-9.-]+$ ]]; then
  die "Invalid mail hostname: $MAIL_HOST"
fi

APACHE_STOPPED=0
restart_apache_if_needed() {
  if [ "$APACHE_STOPPED" = "1" ]; then
    systemctl start apache2 || true
    APACHE_STOPPED=0
  fi
}
trap restart_apache_if_needed EXIT

log "Installing mail packages..."
export DEBIAN_FRONTEND=noninteractive
echo "postfix postfix/mailname string ${DOMAIN}" | debconf-set-selections
echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
apt update
apt install -y postfix dovecot-core dovecot-imapd opendkim opendkim-tools certbot openssl swaks

log "Creating vmail user and directories..."
if ! getent group vmail >/dev/null 2>&1; then
  groupadd -g 5000 vmail
fi
if ! id -u vmail >/dev/null 2>&1; then
  useradd -g vmail -u 5000 vmail -d /var/vmail -m -s /usr/sbin/nologin vmail
fi
mkdir -p "/var/vmail/${DOMAIN}" /etc/postfix/virtual "/etc/opendkim/keys/${DOMAIN}"
chown -R vmail:vmail /var/vmail
chmod 750 /var/vmail

CERT_DIR="/etc/letsencrypt/live/${MAIL_HOST}"
CERT_FILE="${CERT_DIR}/fullchain.pem"
KEY_FILE="${CERT_DIR}/privkey.pem"

if [ ! -f "$CERT_FILE" ] || [ ! -f "$KEY_FILE" ]; then
  log "Requesting Let's Encrypt certificate for ${MAIL_HOST}..."
  log "DNS must already have A mail -> this VPS public IP."
  if systemctl is-active --quiet apache2; then
    APACHE_STOPPED=1
    systemctl stop apache2
  fi
  certbot certonly --standalone --non-interactive --agree-tos \
    --register-unsafely-without-email -d "$MAIL_HOST"
  restart_apache_if_needed
fi

[ -f "$CERT_FILE" ] || die "Missing certificate: $CERT_FILE"
[ -f "$KEY_FILE" ] || die "Missing private key: $KEY_FILE"

touch "$PASSWORD_FILE"
chmod 600 "$PASSWORD_FILE"

password_for() {
  local email="$1"
  local existing=""
  existing="$(awk -F= -v key="$email" '$1 == key { print $2; exit }' "$PASSWORD_FILE" 2>/dev/null || true)"
  if [ -n "$existing" ]; then
    echo "$existing"
  else
    openssl rand -hex 18
  fi
}

TMP_PASS="$(mktemp)"
TMP_DOVECOT="$(mktemp)"
TMP_MAILBOXES="$(mktemp)"
TMP_ALIASES="$(mktemp)"

{
  echo "# Generated by scripts/setup-self-hosted-smtp.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  for local_part in "${MAILBOXES[@]}"; do
    email="${local_part}@${DOMAIN}"
    pass="$(password_for "$email")"
    hash="$(doveadm pw -s SHA512-CRYPT -p "$pass")"
    echo "${email}=${pass}" >> "$TMP_PASS"
    echo "${email}:${hash}:5000:5000::/var/vmail/${DOMAIN}/${local_part}::" >> "$TMP_DOVECOT"
    echo "${email} ${DOMAIN}/${local_part}/Maildir/" >> "$TMP_MAILBOXES"
    mkdir -p "/var/vmail/${DOMAIN}/${local_part}/Maildir"/{cur,new,tmp}
  done
} >/dev/null

cat > "$TMP_ALIASES" <<EOF
postmaster@${DOMAIN} account@${DOMAIN}
abuse@${DOMAIN} account@${DOMAIN}
admin@${DOMAIN} account@${DOMAIN}
contact@${DOMAIN} team@${DOMAIN}
support@${DOMAIN} team@${DOMAIN}
EOF

install -m 600 -o root -g root "$TMP_PASS" "$PASSWORD_FILE"
install -m 640 -o root -g dovecot "$TMP_DOVECOT" /etc/dovecot/users
install -m 644 "$TMP_MAILBOXES" /etc/postfix/virtual/virtual_mailbox_maps
install -m 644 "$TMP_ALIASES" /etc/postfix/virtual/virtual_alias_maps
echo "${DOMAIN} OK" > /etc/postfix/virtual/virtual_mailbox_domains
postmap /etc/postfix/virtual/virtual_mailbox_domains
postmap /etc/postfix/virtual/virtual_mailbox_maps
postmap /etc/postfix/virtual/virtual_alias_maps
chown -R vmail:vmail "/var/vmail/${DOMAIN}"
rm -f "$TMP_PASS" "$TMP_DOVECOT" "$TMP_MAILBOXES" "$TMP_ALIASES"

log "Configuring Dovecot..."
cat > /etc/dovecot/conf.d/99-jyotish-mail.conf <<EOF
protocols = imap
mail_location = maildir:/var/vmail/%d/%n/Maildir
disable_plaintext_auth = yes
auth_mechanisms = plain login

ssl = required
ssl_cert = <${CERT_FILE}
ssl_key = <${KEY_FILE}

passdb {
  driver = passwd-file
  args = scheme=SHA512-CRYPT username_format=%u /etc/dovecot/users
}

userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/vmail/%d/%n
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}
EOF

log "Configuring Postfix..."
postconf -e "myhostname = ${MAIL_HOST}"
postconf -e "myorigin = ${DOMAIN}"
postconf -e "mydestination = localhost"
postconf -e "mynetworks = 127.0.0.0/8"
postconf -e "inet_interfaces = all"
postconf -e "inet_protocols = ipv4"
postconf -e "recipient_delimiter = +"
postconf -e "smtpd_tls_cert_file = ${CERT_FILE}"
postconf -e "smtpd_tls_key_file = ${KEY_FILE}"
postconf -e "smtpd_tls_security_level = may"
postconf -e "smtp_tls_security_level = may"
postconf -e "smtpd_sasl_type = dovecot"
postconf -e "smtpd_sasl_path = private/auth"
postconf -e "smtpd_sasl_auth_enable = yes"
postconf -e "smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination"
postconf -e "smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination"
postconf -e "virtual_mailbox_domains = hash:/etc/postfix/virtual/virtual_mailbox_domains"
postconf -e "virtual_mailbox_base = /var/vmail"
postconf -e "virtual_mailbox_maps = hash:/etc/postfix/virtual/virtual_mailbox_maps"
postconf -e "virtual_alias_maps = hash:/etc/postfix/virtual/virtual_alias_maps"
postconf -e "virtual_uid_maps = static:5000"
postconf -e "virtual_gid_maps = static:5000"
postconf -e "mailbox_size_limit = 0"
postconf -e "message_size_limit = 52428800"

postconf -M "submission/inet=submission inet n - y - - smtpd"
postconf -P "submission/inet/syslog_name=postfix/submission"
postconf -P "submission/inet/smtpd_tls_security_level=encrypt"
postconf -P "submission/inet/smtpd_sasl_auth_enable=yes"
postconf -P "submission/inet/smtpd_client_restrictions=permit_sasl_authenticated,reject"
postconf -P "submission/inet/smtpd_recipient_restrictions=permit_sasl_authenticated,reject"

log "Configuring OpenDKIM..."
if [ ! -f "/etc/opendkim/keys/${DOMAIN}/mail.private" ]; then
  opendkim-genkey -b 2048 -d "$DOMAIN" -s mail -D "/etc/opendkim/keys/${DOMAIN}"
fi
chown -R opendkim:opendkim "/etc/opendkim/keys/${DOMAIN}"
chmod 600 "/etc/opendkim/keys/${DOMAIN}/mail.private"

cat > /etc/opendkim.conf <<EOF
Syslog yes
UMask 002
Canonicalization relaxed/simple
Mode sv
SubDomains no
OversignHeaders From
Socket inet:8891@localhost
PidFile /run/opendkim/opendkim.pid
UserID opendkim
KeyTable refile:/etc/opendkim/key.table
SigningTable refile:/etc/opendkim/signing.table
ExternalIgnoreList refile:/etc/opendkim/trusted.hosts
InternalHosts refile:/etc/opendkim/trusted.hosts
EOF

cat > /etc/opendkim/key.table <<EOF
mail._domainkey.${DOMAIN} ${DOMAIN}:mail:/etc/opendkim/keys/${DOMAIN}/mail.private
EOF
cat > /etc/opendkim/signing.table <<EOF
*@${DOMAIN} mail._domainkey.${DOMAIN}
EOF
cat > /etc/opendkim/trusted.hosts <<EOF
127.0.0.1
localhost
${DOMAIN}
${MAIL_HOST}
EOF

postconf -e "milter_default_action = accept"
postconf -e "milter_protocol = 6"
postconf -e "smtpd_milters = inet:localhost:8891"
postconf -e "non_smtpd_milters = inet:localhost:8891"

log "Validating and restarting mail services..."
doveconf -n >/tmp/doveconf-jyotish-mail.txt
postfix check
systemctl enable --now opendkim dovecot postfix
systemctl restart opendkim dovecot postfix

DKIM_PATH="/etc/opendkim/keys/${DOMAIN}/mail.txt"
cat > "$DNS_FILE" <<EOF
Self-hosted mail DNS records for ${DOMAIN}

Required DNS:
  A     mail              <VPS_PUBLIC_IP>
  MX    @       10        ${MAIL_HOST}
  TXT   @                 "v=spf1 mx -all"
  TXT   _dmarc            "v=DMARC1; p=quarantine; rua=mailto:account@${DOMAIN}; adkim=s; aspf=s"

Required reverse DNS / PTR:
  <VPS_PUBLIC_IP> -> ${MAIL_HOST}

DKIM:
  Copy the TXT record from ${DKIM_PATH}

App server/.env values:
  SMTP_HOST=${MAIL_HOST}
  SMTP_PORT=587
  SMTP_SECURE=false
  SMTP_REQUIRE_TLS=true
  SMTP_TLS_REJECT_UNAUTHORIZED=true
  SMTP_TLS_SERVERNAME=${MAIL_HOST}
  MAIL_SALES_USER=sales@${DOMAIN}
  MAIL_TEAM_USER=team@${DOMAIN}
  MAIL_ACCOUNT_USER=account@${DOMAIN}

Mailbox passwords:
  ${PASSWORD_FILE}
EOF
chmod 600 "$DNS_FILE"

log "Self-hosted SMTP/IMAP setup complete."
log "Mailbox passwords: ${PASSWORD_FILE}"
log "DNS checklist: ${DNS_FILE}"
log "DKIM TXT source: ${DKIM_PATH}"
log "Listening ports:"
ss -ltnp | grep -E ':(25|587|993)\b' || true
