// Seed: 9 Vedic Planets (Navagrahas)
exports.seed = async function (knex) {
  await knex('planet_dignity').del();
  await knex('nakshatras').del();
  await knex('planets').del();

  await knex('planets').insert([
    {
      id: 1, name: 'Sun', name_hi: 'सूर्य', name_sanskrit: 'Surya',
      abbreviation: 'SU', symbol: '☉',
      nature: 'malefic', gender: 'masculine', element: 'Fire',
      weekday: 'Sunday', color: 'Copper/Red-Orange', gemstone: 'Ruby', gemstone_hi: 'माणिक',
      metal: 'Gold', direction: 'East', body_part: 'Heart, Eyes, Bones, Spine',
      body_part_hi: 'हृदय, आँखें, हड्डियाँ, रीढ़',
      is_shadow_planet: false, vimshottari_years: 6,
      characteristics: 'Soul, Father, Authority, Government, Power, Self-esteem, Ego, Vitality, Leadership',
      characteristics_hi: 'आत्मा, पिता, अधिकार, सरकार, शक्ति, आत्मसम्मान, अहंकार, जीवनशक्ति, नेतृत्व',
    },
    {
      id: 2, name: 'Moon', name_hi: 'चन्द्रमा', name_sanskrit: 'Chandra',
      abbreviation: 'MO', symbol: '☽',
      nature: 'benefic', gender: 'feminine', element: 'Water',
      weekday: 'Monday', color: 'White/Silver', gemstone: 'Pearl', gemstone_hi: 'मोती',
      metal: 'Silver', direction: 'North-West', body_part: 'Mind, Blood, Chest, Left Eye (women), Right Eye (men)',
      body_part_hi: 'मन, रक्त, छाती, बायीं आँख (महिला), दायीं आँख (पुरुष)',
      is_shadow_planet: false, vimshottari_years: 10,
      characteristics: 'Mind, Mother, Emotions, Intuition, Nurturing, Home, Public, Fluids, Fertility',
      characteristics_hi: 'मन, माता, भावनाएं, अंतर्ज्ञान, पालन-पोषण, घर, जनता, तरल पदार्थ, उर्वरता',
    },
    {
      id: 3, name: 'Mars', name_hi: 'मंगल', name_sanskrit: 'Mangala',
      abbreviation: 'MA', symbol: '♂',
      nature: 'malefic', gender: 'masculine', element: 'Fire',
      weekday: 'Tuesday', color: 'Red', gemstone: 'Red Coral', gemstone_hi: 'मूंगा',
      metal: 'Copper', direction: 'South', body_part: 'Blood, Muscles, Bone Marrow, Brothers, Energy',
      body_part_hi: 'रक्त, मांसपेशियाँ, अस्थि मज्जा, भाई, ऊर्जा',
      is_shadow_planet: false, vimshottari_years: 7,
      characteristics: 'Courage, Energy, Action, Brothers, Property, War, Surgery, Police, Sports, Ambition',
      characteristics_hi: 'साहस, ऊर्जा, क्रिया, भाई, संपत्ति, युद्ध, शल्य चिकित्सा, पुलिस, खेल, महत्वाकांक्षा',
    },
    {
      id: 4, name: 'Mercury', name_hi: 'बुध', name_sanskrit: 'Budha',
      abbreviation: 'ME', symbol: '☿',
      nature: 'neutral', gender: 'neutral', element: 'Earth/Air',
      weekday: 'Wednesday', color: 'Green', gemstone: 'Emerald', gemstone_hi: 'पन्ना',
      metal: 'Brass/Bronze', direction: 'North', body_part: 'Nervous System, Skin, Speech, Intelligence, Arms',
      body_part_hi: 'तंत्रिका तंत्र, त्वचा, वाणी, बुद्धि, भुजाएं',
      is_shadow_planet: false, vimshottari_years: 17,
      characteristics: 'Intelligence, Communication, Business, Education, Writing, Wit, Discrimination, Adaptability',
      characteristics_hi: 'बुद्धि, संचार, व्यापार, शिक्षा, लेखन, चतुराई, विवेक, अनुकूलनशीलता',
    },
    {
      id: 5, name: 'Jupiter', name_hi: 'बृहस्पति', name_sanskrit: 'Guru',
      abbreviation: 'JU', symbol: '♃',
      nature: 'benefic', gender: 'masculine', element: 'Ether/Space',
      weekday: 'Thursday', color: 'Yellow/Gold', gemstone: 'Yellow Sapphire', gemstone_hi: 'पुखराज',
      metal: 'Gold', direction: 'North-East', body_part: 'Liver, Hips, Thighs, Fat, Ears',
      body_part_hi: 'यकृत, कूल्हे, जांघें, चर्बी, कान',
      is_shadow_planet: false, vimshottari_years: 16,
      characteristics: 'Wisdom, Knowledge, Religion, Philosophy, Guru, Children, Wealth, Expansion, Grace, Fortune',
      characteristics_hi: 'ज्ञान, धर्म, दर्शन, गुरु, संतान, धन, विस्तार, कृपा, भाग्य',
    },
    {
      id: 6, name: 'Venus', name_hi: 'शुक्र', name_sanskrit: 'Shukra',
      abbreviation: 'VE', symbol: '♀',
      nature: 'benefic', gender: 'feminine', element: 'Water/Earth',
      weekday: 'Friday', color: 'White/Multicolor', gemstone: 'Diamond', gemstone_hi: 'हीरा',
      metal: 'Silver/Platinum', direction: 'South-East', body_part: 'Reproductive Organs, Kidneys, Throat, Eyes, Semen',
      body_part_hi: 'प्रजनन अंग, गुर्दे, गला, आँखें, वीर्य',
      is_shadow_planet: false, vimshottari_years: 20,
      characteristics: 'Love, Beauty, Art, Music, Luxury, Comfort, Marriage, Spouse, Vehicles, Creativity',
      characteristics_hi: 'प्रेम, सौंदर्य, कला, संगीत, विलासिता, आराम, विवाह, जीवनसाथी, वाहन, सृजनशीलता',
    },
    {
      id: 7, name: 'Saturn', name_hi: 'शनि', name_sanskrit: 'Shani',
      abbreviation: 'SA', symbol: '♄',
      nature: 'malefic', gender: 'neutral', element: 'Air/Earth',
      weekday: 'Saturday', color: 'Black/Dark Blue', gemstone: 'Blue Sapphire', gemstone_hi: 'नीलम',
      metal: 'Iron', direction: 'West', body_part: 'Bones, Teeth, Joints, Nerves, Chronic Diseases, Old Age',
      body_part_hi: 'हड्डियाँ, दाँत, जोड़, नसें, पुराने रोग, बुढ़ापा',
      is_shadow_planet: false, vimshottari_years: 19,
      characteristics: 'Discipline, Karma, Hard Work, Delays, Service, Longevity, Servants, Oil, Mines, Detachment',
      characteristics_hi: 'अनुशासन, कर्म, कठिन परिश्रम, विलंब, सेवा, दीर्घायु, नौकर, तेल, खनन, वैराग्य',
    },
    {
      id: 8, name: 'Rahu', name_hi: 'राहु', name_sanskrit: 'Rahu',
      abbreviation: 'RA', symbol: '☊',
      nature: 'shadow', gender: 'masculine', element: 'Air',
      weekday: null, color: 'Smoky/Black', gemstone: 'Hessonite (Gomed)', gemstone_hi: 'गोमेद',
      metal: 'Lead', direction: 'South-West', body_part: 'Skin, Nervous System, Epidemics',
      body_part_hi: 'त्वचा, तंत्रिका तंत्र, महामारी',
      is_shadow_planet: true, vimshottari_years: 18,
      characteristics: 'Obsessions, Foreign, Technology, Unconventional, Illusions, Amplification, Materialistic Desires',
      characteristics_hi: 'जुनून, विदेश, प्रौद्योगिकी, अपरंपरागत, भ्रम, प्रवर्धन, भौतिक इच्छाएं',
    },
    {
      id: 9, name: 'Ketu', name_hi: 'केतु', name_sanskrit: 'Ketu',
      abbreviation: 'KE', symbol: '☋',
      nature: 'shadow', gender: 'neutral', element: 'Fire',
      weekday: null, color: 'Grey/Spotted', gemstone: "Cat's Eye (Lehsunia)", gemstone_hi: 'लहसुनिया',
      metal: 'Mixed Metals', direction: 'North-East (debated)', body_part: 'Feet, Spirituality, Detachment',
      body_part_hi: 'पैर, आध्यात्मिकता, वैराग्य',
      is_shadow_planet: true, vimshottari_years: 7,
      characteristics: 'Spirituality, Moksha, Past Life, Detachment, Isolation, Occult, Liberation, Confusion',
      characteristics_hi: 'आध्यात्मिकता, मोक्ष, पूर्व जन्म, वैराग्य, एकांत, तंत्र, मुक्ति, भ्रम',
    },
  ]);
};
