// Seed: 12 Rashis (Zodiac Signs) + 12 Bhavas (Houses)
exports.seed = async function (knex) {
  await knex('zodiac_signs').del();

  await knex('zodiac_signs').insert([
    { id: 1,  name: 'Aries',       name_hi: 'मेष',      name_sanskrit: 'Mesha',      symbol: '♈', element: 'fire',  quality: 'cardinal', gender: 'masculine', lord_planet: 'MA', start_degree: 0,   end_degree: 30,  description: 'First sign. Pioneer, assertive, courageous, impulsive.', description_hi: 'पहली राशि। अग्रणी, जोशीला, साहसी, आवेगी।' },
    { id: 2,  name: 'Taurus',      name_hi: 'वृषभ',     name_sanskrit: 'Vrishabha',   symbol: '♉', element: 'earth', quality: 'fixed',    gender: 'feminine',  lord_planet: 'VE', start_degree: 30,  end_degree: 60,  description: 'Second sign. Stable, sensual, determined, practical.', description_hi: 'दूसरी राशि। स्थिर, संवेदनशील, दृढ़निश्चयी, व्यावहारिक।' },
    { id: 3,  name: 'Gemini',      name_hi: 'मिथुन',    name_sanskrit: 'Mithuna',     symbol: '♊', element: 'air',   quality: 'mutable',  gender: 'masculine', lord_planet: 'ME', start_degree: 60,  end_degree: 90,  description: 'Third sign. Curious, communicative, adaptable, dual nature.', description_hi: 'तीसरी राशि। जिज्ञासु, संचारशील, अनुकूलनीय, द्विस्वभाव।' },
    { id: 4,  name: 'Cancer',      name_hi: 'कर्क',     name_sanskrit: 'Kataka',      symbol: '♋', element: 'water', quality: 'cardinal', gender: 'feminine',  lord_planet: 'MO', start_degree: 90,  end_degree: 120, description: 'Fourth sign. Nurturing, emotional, protective, home-loving.', description_hi: 'चौथी राशि। पालन-पोषण करने वाली, भावनात्मक, सुरक्षात्मक, घर से प्यार करने वाली।' },
    { id: 5,  name: 'Leo',         name_hi: 'सिंह',     name_sanskrit: 'Simha',       symbol: '♌', element: 'fire',  quality: 'fixed',    gender: 'masculine', lord_planet: 'SU', start_degree: 120, end_degree: 150, description: 'Fifth sign. Creative, generous, dramatic, royal, confident.', description_hi: 'पाँचवीं राशि। रचनात्मक, उदार, नाटकीय, शाही, आत्मविश्वासी।' },
    { id: 6,  name: 'Virgo',       name_hi: 'कन्या',    name_sanskrit: 'Kanya',       symbol: '♍', element: 'earth', quality: 'mutable',  gender: 'feminine',  lord_planet: 'ME', start_degree: 150, end_degree: 180, description: 'Sixth sign. Analytical, precise, service-oriented, perfectionist.', description_hi: 'छठी राशि। विश्लेषणात्मक, सटीक, सेवामुखी, परिपूर्णतावादी।' },
    { id: 7,  name: 'Libra',       name_hi: 'तुला',     name_sanskrit: 'Tula',        symbol: '♎', element: 'air',   quality: 'cardinal', gender: 'masculine', lord_planet: 'VE', start_degree: 180, end_degree: 210, description: 'Seventh sign. Balanced, diplomatic, social, beauty-loving.', description_hi: 'सातवीं राशि। संतुलित, कूटनीतिक, सामाजिक, सौंदर्यप्रिय।' },
    { id: 8,  name: 'Scorpio',     name_hi: 'वृश्चिक',  name_sanskrit: 'Vrischika',   symbol: '♏', element: 'water', quality: 'fixed',    gender: 'feminine',  lord_planet: 'MA', start_degree: 210, end_degree: 240, description: 'Eighth sign. Intense, investigative, transformative, secretive.', description_hi: 'आठवीं राशि। तीव्र, जाँचकर्ता, परिवर्तनकारी, रहस्यमय।' },
    { id: 9,  name: 'Sagittarius', name_hi: 'धनु',      name_sanskrit: 'Dhanus',      symbol: '♐', element: 'fire',  quality: 'mutable',  gender: 'masculine', lord_planet: 'JU', start_degree: 240, end_degree: 270, description: 'Ninth sign. Philosophical, adventurous, optimistic, truth-seeking.', description_hi: 'नौवीं राशि। दार्शनिक, साहसिक, आशावादी, सत्य-खोजी।' },
    { id: 10, name: 'Capricorn',   name_hi: 'मकर',      name_sanskrit: 'Makara',      symbol: '♑', element: 'earth', quality: 'cardinal', gender: 'feminine',  lord_planet: 'SA', start_degree: 270, end_degree: 300, description: 'Tenth sign. Disciplined, ambitious, responsible, traditional.', description_hi: 'दसवीं राशि। अनुशासित, महत्वाकांक्षी, जिम्मेदार, परंपरागत।' },
    { id: 11, name: 'Aquarius',    name_hi: 'कुम्भ',    name_sanskrit: 'Kumbha',      symbol: '♒', element: 'air',   quality: 'fixed',    gender: 'masculine', lord_planet: 'SA', start_degree: 300, end_degree: 330, description: 'Eleventh sign. Humanitarian, innovative, independent, progressive.', description_hi: 'ग्यारहवीं राशि। मानवतावादी, अभिनव, स्वतंत्र, प्रगतिशील।' },
    { id: 12, name: 'Pisces',      name_hi: 'मीन',      name_sanskrit: 'Meena',       symbol: '♓', element: 'water', quality: 'mutable',  gender: 'feminine',  lord_planet: 'JU', start_degree: 330, end_degree: 360, description: 'Twelfth sign. Compassionate, intuitive, spiritual, dreamy.', description_hi: 'बारहवीं राशि। दयालु, अंतर्ज्ञानी, आध्यात्मिक, स्वप्निल।' },
  ]);

  // ── 12 Bhavas (Houses) ──
  await knex('houses').del();
  await knex('houses').insert([
    { id: 1,  name: 'First House (Ascendant / Lagna)',   name_hi: 'प्रथम भाव (लग्न)',      sanskrit_name: 'Tanu Bhava',     significations: 'Self,Body,Appearance,Personality,Health,Fame,Character', significations_hi: 'स्व,शरीर,रूप,व्यक्तित्व,स्वास्थ्य,यश,चरित्र', body_parts: 'Head, Brain', quality: 'kendra',    karaka: 'Sun',     description: 'The self, physical body, personality, general health, and overall life outlook.', description_hi: 'स्वयं, शारीरिक रूप, व्यक्तित्व, सामान्य स्वास्थ्य और जीवन दृष्टिकोण।' },
    { id: 2,  name: 'Second House (Wealth)',             name_hi: 'द्वितीय भाव (धन)',      sanskrit_name: 'Dhana Bhava',    significations: 'Wealth,Speech,Family,Food,Savings,Face,Right Eye', significations_hi: 'धन,वाणी,परिवार,भोजन,बचत,मुख,दायीं आँख', body_parts: 'Face, Mouth, Throat', quality: 'neutral',   karaka: 'Jupiter', description: 'Accumulated wealth, speech, family of origin, food habits, and movable assets.', description_hi: 'संचित धन, वाणी, मूल परिवार, खान-पान की आदतें और चल संपत्ति।' },
    { id: 3,  name: 'Third House (Siblings)',            name_hi: 'तृतीय भाव (भाई-बहन)',   sanskrit_name: 'Sahaja Bhava',   significations: 'Siblings,Courage,Short Travel,Writing,Communication,Efforts', significations_hi: 'भाई-बहन,साहस,छोटी यात्रा,लेखन,संचार,प्रयास', body_parts: 'Arms, Shoulders, Lungs', quality: 'upachaya', karaka: 'Mars',    description: 'Siblings, courage, short journeys, communication, writing, and self-effort.', description_hi: 'भाई-बहन, साहस, छोटी यात्राएँ, संचार, लेखन और स्वयं के प्रयास।' },
    { id: 4,  name: 'Fourth House (Home/Mother)',        name_hi: 'चतुर्थ भाव (घर/माता)',  sanskrit_name: 'Sukha Bhava',    significations: 'Mother,Home,Property,Vehicles,Education,Happiness,Heart', significations_hi: 'माता,घर,संपत्ति,वाहन,शिक्षा,सुख,हृदय', body_parts: 'Chest, Heart, Lungs', quality: 'kendra',    karaka: 'Moon',    description: 'Mother, home, land and property, vehicles, domestic happiness, and academic education.', description_hi: 'माता, घर, भूमि और संपत्ति, वाहन, घरेलू सुख और शैक्षणिक शिक्षा।' },
    { id: 5,  name: 'Fifth House (Intelligence)',        name_hi: 'पंचम भाव (संतान/बुद्धि)', sanskrit_name: 'Putra Bhava',   significations: 'Children,Intelligence,Creativity,Romance,Speculation,Past Merit', significations_hi: 'संतान,बुद्धि,रचनात्मकता,प्रेम,सट्टा,पूर्व जन्म के पुण्य', body_parts: 'Stomach, Upper Abdomen', quality: 'trikona',  karaka: 'Jupiter', description: 'Children, intelligence, creativity, romance, speculative gains, and past life merits.', description_hi: 'संतान, बुद्धि, रचनात्मकता, प्रेम, सट्टे का लाभ और पूर्व जन्म के पुण्य।' },
    { id: 6,  name: 'Sixth House (Enemies/Diseases)',   name_hi: 'षष्ठ भाव (शत्रु/रोग)',  sanskrit_name: 'Ripu Bhava',     significations: 'Enemies,Diseases,Debts,Service,Litigation,Competition', significations_hi: 'शत्रु,रोग,कर्ज,सेवा,मुकदमेबाजी,प्रतिस्पर्धा', body_parts: 'Abdomen, Intestines', quality: 'dusthana', karaka: 'Mars',    description: 'Enemies, illnesses, debts, obstacles, service-oriented work, and legal disputes.', description_hi: 'शत्रु, बीमारियाँ, कर्ज, बाधाएँ, सेवा-उन्मुख कार्य और कानूनी विवाद।' },
    { id: 7,  name: 'Seventh House (Marriage/Partner)', name_hi: 'सप्तम भाव (विवाह/साझेदार)', sanskrit_name: 'Kalatra Bhava', significations: 'Marriage,Spouse,Partnerships,Business,Foreign Travel,Desires', significations_hi: 'विवाह,जीवनसाथी,साझेदारी,व्यापार,विदेश यात्रा,इच्छाएं', body_parts: 'Pelvis, Kidneys, Lower Back', quality: 'kendra',    karaka: 'Venus',   description: 'Marriage, life partner, business partnerships, open enemies, and public dealings.', description_hi: 'विवाह, जीवनसाथी, व्यापार साझेदारी, खुले शत्रु और सार्वजनिक व्यवहार।' },
    { id: 8,  name: 'Eighth House (Longevity/Secrets)', name_hi: 'अष्टम भाव (आयु/रहस्य)',  sanskrit_name: 'Ayu Bhava',      significations: 'Longevity,Death,Transformation,Inheritance,Occult,Sudden Events', significations_hi: 'आयु,मृत्यु,परिवर्तन,विरासत,तंत्र,अचानक घटनाएँ', body_parts: 'Genitals, Anus, Chronic Diseases', quality: 'dusthana', karaka: 'Saturn',  description: 'Longevity, death, transformation, hidden matters, inheritance, and occult knowledge.', description_hi: 'आयु, मृत्यु, परिवर्तन, छिपे हुए मामले, विरासत और तांत्रिक ज्ञान।' },
    { id: 9,  name: 'Ninth House (Fortune/Religion)',   name_hi: 'नवम भाव (भाग्य/धर्म)',   sanskrit_name: 'Dharma Bhava',   significations: 'Fortune,Religion,Philosophy,Father,Long Travel,Higher Education,Guru', significations_hi: 'भाग्य,धर्म,दर्शन,पिता,लंबी यात्रा,उच्च शिक्षा,गुरु', body_parts: 'Thighs, Hips', quality: 'trikona',  karaka: 'Jupiter', description: 'Fortune, religion, dharma, father, long journeys, higher education, and spiritual wisdom.', description_hi: 'भाग्य, धर्म, पिता, लंबी यात्राएँ, उच्च शिक्षा और आध्यात्मिक ज्ञान।' },
    { id: 10, name: 'Tenth House (Career/Karma)',       name_hi: 'दशम भाव (कर्म/कैरियर)',  sanskrit_name: 'Karma Bhava',    significations: 'Career,Status,Fame,Government,Authority,Public Life,Karma', significations_hi: 'करियर,प्रतिष्ठा,यश,सरकार,अधिकार,सार्वजनिक जीवन,कर्म', body_parts: 'Knees, Bones', quality: 'kendra',    karaka: 'Mercury, Sun, Jupiter, Saturn', description: 'Career, profession, public status, authority, fame, and social standing.', description_hi: 'करियर, व्यवसाय, सार्वजनिक प्रतिष्ठा, अधिकार, यश और सामाजिक स्थान।' },
    { id: 11, name: 'Eleventh House (Gains/Desires)',   name_hi: 'एकादश भाव (लाभ/इच्छाएं)', sanskrit_name: 'Labha Bhava',   significations: 'Gains,Income,Friends,Elder Siblings,Ambitions,Social Circle,Fulfillment', significations_hi: 'लाभ,आय,मित्र,बड़े भाई-बहन,महत्वाकांक्षाएं,सामाजिक मंडल,पूर्ति', body_parts: 'Ankles, Calves', quality: 'upachaya', karaka: 'Jupiter', description: 'Gains, income, fulfillment of desires, friends, elder siblings, and social networks.', description_hi: 'लाभ, आय, इच्छाओं की पूर्ति, मित्र, बड़े भाई-बहन और सामाजिक नेटवर्क।' },
    { id: 12, name: 'Twelfth House (Losses/Liberation)', name_hi: 'द्वादश भाव (व्यय/मोक्ष)', sanskrit_name: 'Vyaya Bhava',   significations: 'Losses,Expenditure,Foreign Lands,Spirituality,Liberation,Isolation,Bed Pleasures', significations_hi: 'व्यय,हानि,विदेश,आध्यात्मिकता,मोक्ष,एकांत,शयन सुख', body_parts: 'Feet, Left Eye', quality: 'dusthana', karaka: 'Saturn',  description: 'Losses, expenditures, foreign lands, spirituality, liberation (moksha), and isolation.', description_hi: 'व्यय, हानि, विदेश भूमि, आध्यात्मिकता, मोक्ष और एकांत।' },
  ]);
};
