// Seed 006 — House Lord Interpretations (Lord of Every House in 12 Houses)
// Source: "12_HOUSE_LORD.md" (full English content extracted and mapped)
// Complete 144 combinations (12 lords × 12 placements)

exports.seed = async function (knex) {
  await knex('house_lord_interpretations').del();

  const src = 'Lord of every house in 12 houses.pdf / 12_HOUSE_LORD.md';
  const rows = [];

  // ─── Effect helper ────────────────────────────────────────────────────────
  function eff(lord, house) {
    if (house === lord) return 'highly_positive';
    if ([1,5,9].includes(house)) return 'highly_positive';
    if ([4,10,11].includes(house)) return 'positive';
    if ([6,12].includes(house)) return 'negative';
    if (house === 8) return lord === 8 ? 'neutral' : 'negative';
    return 'neutral';
  }

  function add(lord, house, title, en, keys = []) {
    rows.push({
      house_lord: lord,
      placed_in_house: house,
      title,
      title_hi: null,
      interpretation_en: en.trim(),
      interpretation_hi: null,
      key_results_en: JSON.stringify(keys),
      key_results_hi: JSON.stringify([]),
      overall_effect: eff(lord, house),
      source: src,
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 1ST HOUSE LORD (Lagna Lord / Self)
  // ═══════════════════════════════════════════════════════════════════════════
  add(1,1,'1st Lord in 1st House','When the 1st house lord is in the 1st house, it creates a powerful alignment of self-awareness and vitality. The native possesses a strong personality, good health (unless afflicted), and a clear sense of identity. They are self-reliant, confident, and often take initiative in life. This placement emphasizes personal growth and independence, making the individual a natural leader. Health is generally robust unless malefic influences like Rahu or Saturn weaken the lord.',['Strong physique and vitality','Self-reliant and confident','Leadership abilities','Good health generally','Fame and recognition']);
  add(1,2,'1st Lord in 2nd House','The 1st house lord in the 2nd house connects the self to wealth, family, and speech. The native\'s identity and efforts are directed toward accumulating wealth and maintaining family harmony. They are likely to have a pleasant voice, good financial acumen, and a personality shaped by material security. Health may depend on financial stability, and they work hard to support their loved ones.',['Wealth building is primary focus','Good speech and communication','Family-oriented','Financial stability through efforts','Interest in food and luxury']);
  add(1,3,'1st Lord in 3rd House','With the 1st house lord in the 3rd house, the native\'s identity is tied to courage, communication, and siblings. They are bold, skillful, and often excel in fields requiring initiative, such as writing, media, or entrepreneurship. Siblings or short travels play a significant role in shaping their life. The native thrives on challenges, using their vitality to master skills and assert themselves.',['Courageous and self-motivated','Writing and communication skills','Entrepreneurial nature','Good sibling relationships','Love for travel and adventure']);
  add(1,4,'1st Lord in 4th House','The 1st house lord in the 4th house ties the self to home, mother, and emotional security. The native is deeply attached to their roots, finding comfort in domestic life and property matters. They may have a nurturing personality and good health if supported by a stable home environment. Their identity is shaped by familial bonds and a sense of belonging.',['Property and real estate gains','Strong maternal bond','Domestic happiness','Good education','Vehicles and comforts']);
  add(1,5,'1st Lord in 5th House','The 1st house lord in the 5th house connects the self to creativity, intelligence, children, and romance. The native is imaginative, intellectually sharp, and often blessed with progeny. Their identity shines through creative pursuits or speculative ventures, where they take risks with confidence. Children or students may play a key role in their life\'s purpose.',['High intelligence and creativity','Blessed with good children','Success in speculation','Romantic and artistic nature','Past life blessings']);
  add(1,6,'1st Lord in 6th House','The 1st house lord in the 6th house ties the self to competition, service, and overcoming obstacles. The native is hardworking, resilient, and thrives in challenging environments. They may excel in service-oriented fields (e.g., healthcare, law) or defeat enemies through determination. Health may be a concern, requiring effort to maintain.',['Health challenges possible','Strong fighting spirit','Service-oriented career','Overcoming debts and enemies','Resilience builds strength']);
  add(1,7,'1st Lord in 7th House','The 1st house lord in the 7th house connects the self to partnerships, marriage, and public dealings. The native\'s identity is heavily influenced by their spouse or business partners, and they thrive in collaborative environments. They are charming, diplomatic, and often successful in relationships or trade.',['Good marriage prospects','Charming personality','Business success through partnerships','Foreign travel possible','Public popularity']);
  add(1,8,'1st Lord in 8th House','The 1st house lord in the 8th house ties the self to transformation, occult, and longevity. The native is introspective, resilient, and drawn to mysteries. Their life involves sudden changes, and they may face health challenges or hidden struggles. This placement gives depth and a secretive personality.',['Interest in occult and mysticism','Possible inheritance','Sudden transformative events','Secretive personality','Longevity may be tested if afflicted']);
  add(1,9,'1st Lord in 9th House','The 1st house lord in the 9th house connects the self to luck, spirituality, and higher learning. The native is fortunate, wise, and guided by a strong moral compass. They may excel in teaching, philosophy, or travel-related fields, with their identity shaped by faith and a quest for knowledge.',['Great fortune and luck','Spiritual and philosophical nature','Blessed with wise father','Higher education and wisdom','Long travel and foreign connections']);
  add(1,10,'1st Lord in 10th House','The 1st house lord in the 10th house ties the self to career, status, and public life. The native is ambitious, authoritative, and achieves recognition through their efforts. Their identity is defined by professional success, and they often hold leadership roles.',['High career success and fame','Leadership and authority positions','Government or public sector success','Strong professional identity','Recognition and awards']);
  add(1,11,'1st Lord in 11th House','The 1st house lord in the 11th house connects the self to gains, ambitions, and social networks. The native is goal-oriented, socially active, and achieves desires through teamwork or friendships. Their identity is tied to fulfilling aspirations.',['High income and gains','Desires and ambitions fulfilled','Influential social network','Elder sibling support','Multiple income streams']);
  add(1,12,'1st Lord in 12th House','The 1st house lord in the 12th house ties the self to spirituality, isolation, or foreign lands. The native may be introspective, seeking liberation or living abroad. Their identity is shaped by detachment, and they may face losses or health challenges requiring solitude for healing.',['Expenses and financial losses','Spiritual inclinations','Foreign settlement possible','Hospital stays or isolation','Moksha and liberation potential']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 2ND HOUSE LORD (Dhana Lord / Wealth, Speech, Family)
  // ═══════════════════════════════════════════════════════════════════════════
  add(2,1,'2nd Lord in 1st House','The 2nd house lord in the 1st house ties wealth and speech to the self. The native\'s personality is shaped by their financial status and communication style. They are likely to earn through personal efforts, have a charming voice, and value self-worth. Family plays a key role in their identity.',['Wealth-conscious personality','Good earning power','Charming appearance','Family loyalty','Eloquent speech']);
  add(2,2,'2nd Lord in 2nd House','The 2nd house lord in the 2nd house is a highly auspicious placement for wealth and family harmony. The native excels in accumulating money, has a strong family bond, and speaks with authority or sweetness. They value material stability and may inherit wealth.',['Excellent wealth accumulation','Powerful speech','Strong family bonds','Material comforts','Financial security']);
  add(2,3,'2nd Lord in 3rd House','The 2nd house lord in the 3rd house connects wealth and speech to skills, courage, and siblings. The native earns through their talents (e.g., writing, sales) or with siblings\' help. They have a bold, persuasive voice and value initiative in financial pursuits.',['Income from communication/media','Business gains through efforts','Sibling financial support','Writing and publishing income','Travel-related earnings']);
  add(2,4,'2nd Lord in 4th House','The 2nd house lord in the 4th house ties wealth and speech to home, mother, and property. The native gains financially through real estate or family support, enjoying a comfortable domestic life. They speak with emotional warmth and value family traditions.',['Property and real estate','Comfortable home life','Wealthy mother','Vehicles and comforts','Family assets grow']);
  add(2,5,'2nd Lord in 5th House','The 2nd house lord in the 5th house connects wealth and speech to creativity, children, and speculation. The native earns through creative talents or speculative ventures. They have an eloquent, artistic voice and value intellectual pursuits.',['Speculative gains','Wealth through creativity','Intelligent investments','Children bring prosperity','Financial wisdom']);
  add(2,6,'2nd Lord in 6th House','The 2nd house lord in the 6th house ties wealth and speech to service, competition, and debts. The native earns through hard work, often in service fields, or by overcoming obstacles. Their speech may be sharp or critical, and family life may involve financial struggles.',['Financial debts possible','Medical or legal expenses','Hard work for financial gains','Income from service sector','Financial competition and losses']);
  add(2,7,'2nd Lord in 7th House','The 2nd house lord in the 7th house connects wealth and speech to partnerships and marriage. The native gains financially through their spouse or business collaborations, often excelling in trade or diplomacy. They have a charming, persuasive voice.',['Wealthy spouse','Business partnership gains','Marriage brings prosperity','Foreign trade income','Public financial dealings']);
  add(2,8,'2nd Lord in 8th House','The 2nd house lord in the 8th house ties wealth and speech to transformation, occult, and sudden events. The native may gain through inheritance, insurance, or unexpected sources. Their speech is intense, secretive, or profound.',['Inheritance possible','Sudden financial events','Hidden income sources','Debt and financial instability','Occult-related income']);
  add(2,9,'2nd Lord in 9th House','The 2nd house lord in the 9th house connects wealth and speech to luck, spirituality, and higher learning. The native earns through teaching, travel, or ethical ventures, often blessed with financial fortune. Their speech is wise and inspiring.',['Fortunate financial life','Income from religion/philosophy','Wealthy father','Long-distance trade gains','Dharma brings prosperity']);
  add(2,10,'2nd Lord in 10th House','The 2nd house lord in the 10th house ties wealth and speech to career and status. The native earns through their profession, often in fields requiring communication. Their voice carries authority, and they value professional success as a source of financial stability.',['High professional income','Career brings wealth','Government or corporate income','Financial fame and recognition','Business success']);
  add(2,11,'2nd Lord in 11th House','The 2nd house lord in the 11th house connects wealth and speech to gains, ambitions, and social networks. The native earns through large-scale ventures, friendships, or teamwork, fulfilling their financial desires. Their voice is influential in social circles.',['Multiple income sources','Abundant financial gains','Friendly wealthy network','Elder sibling financial support','Desires fulfilled']);
  add(2,12,'2nd Lord in 12th House','The 2nd house lord in the 12th house ties wealth and speech to losses, spirituality, or foreign lands. The native may spend heavily on charity, travel, or spiritual pursuits, or earn through foreign sources. Their speech is soft or secretive.',['Excessive expenses','Savings challenges','Foreign financial dealings','Charitable expenditure','Spiritual use of wealth']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 3RD HOUSE LORD (Sahaja Lord / Courage, Siblings, Skills)
  // ═══════════════════════════════════════════════════════════════════════════
  add(3,1,'3rd Lord in 1st House','The 3rd house lord in the 1st house ties courage and skills to the self. The native is bold, communicative, and highly skilled, with a personality shaped by initiative and effort. Siblings may influence their identity, and they excel in fields requiring dexterity or expression.',['Courageous and assertive','Writing and communication skills','Entrepreneur spirit','Good sibling relationships','Active energetic nature']);
  add(3,2,'3rd Lord in 2nd House','The 3rd house lord in the 2nd house connects courage and skills to wealth and speech. The native earns through their talents or siblings\' support, often in communication-related fields. They have a bold, expressive voice and value effort in financial pursuits.',['Earnings through communication','Bold expressive voice','Sibling financial support','Effort converts to money','Media and sales income']);
  add(3,3,'3rd Lord in 3rd House','The 3rd house lord in the 3rd house is a powerful placement for courage, skills, and sibling harmony. The native is exceptionally brave, dexterous, and excels in communication or hands-on fields. Siblings are supportive, and short travels enhance their life.',['Exceptional courage','Supportive siblings','Mastery in skills','Success in media/writing','Short travels bring gains']);
  add(3,4,'3rd Lord in 4th House','The 3rd house lord in the 4th house ties courage and skills to home, mother, and property. The native applies effort to create a comfortable home, often with siblings\' or mother\'s support. They may excel in domestic skills and communicate with emotional depth.',['Domestic skills excel','Sibling and maternal support','Real estate through effort','Emotional communication','Home environment enhanced']);
  add(3,5,'3rd Lord in 5th House','The 3rd house lord in the 5th house connects courage and skills to creativity, children, and intellect. The native excels in creative communication (e.g., writing, media), often with sibling support. They value intellectual effort and may involve children in their endeavors.',['Creative communication skills','Sibling support in creativity','Writing and performing arts','Intellectual vigor','Children inspired by efforts']);
  add(3,6,'3rd Lord in 6th House','The 3rd house lord in the 6th house ties courage and skills to competition, service, and enemies. The native uses their talents to overcome obstacles, excelling in service or competitive fields. They are resilient, with a sharp, critical voice.',['Competitive spirit strong','Service through skills','Sibling rivalry possible','Sharp critical voice','Health from overexertion']);
  add(3,7,'3rd Lord in 7th House','The 3rd house lord in the 7th house connects courage and skills to partnerships and marriage. The native\'s efforts strengthen relationships, often excelling in collaborative ventures. Their spouse may be communicative or supportive, and they value teamwork.',['Communication strengthens partnerships','Supportive communicative spouse','Business collaborations flourish','Sibling role in marriage','Active relational dynamic']);
  add(3,8,'3rd Lord in 8th House','The 3rd house lord in the 8th house ties courage and skills to transformation, occult, and sudden events. The native applies effort in research, mysteries, or healing. Their voice is intense, and siblings may face upheavals.',['Research and investigative skills','Occult knowledge through effort','Sibling upheavals possible','Intense voice and communication','Resilience through challenges']);
  add(3,9,'3rd Lord in 9th House','The 3rd house lord in the 9th house connects courage and skills to luck, spirituality, and higher learning. The native applies effort in teaching, travel, or philosophical pursuits, often with fortunate outcomes. Their voice is wise and motivating.',['Teaching and publishing success','Travel brings fortune','Sibling support in growth','Philosophical communication','Skills lead to wisdom']);
  add(3,10,'3rd Lord in 10th House','The 3rd house lord in the 10th house ties courage and skills to career and status. The native excels in professions requiring effort or communication (e.g., media, business), gaining recognition through their talents.',['Media and communication career','Sibling career support','Authority through skills','Recognition for efforts','Public-facing profession success']);
  add(3,11,'3rd Lord in 11th House','The 3rd house lord in the 11th house connects courage and skills to gains, ambitions, and social networks. The native achieves desires through teamwork, friendships, or skillful effort. Their voice is influential in social circles.',['Gains through teamwork','Influential social voice','Sibling support for gains','Ambitions fulfilled through effort','Collaborative success']);
  add(3,12,'3rd Lord in 12th House','The 3rd house lord in the 12th house ties courage and skills to losses, spirituality, or foreign lands. The native applies effort in spiritual pursuits, foreign ventures, or isolation. Their voice is soft or secretive, and they value detachment.',['Foreign ventures through effort','Spiritual communication','Sibling distance possible','Skills for inner growth','Isolation for creative work']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 4TH HOUSE LORD (Sukha Lord / Home, Mother, Property)
  // ═══════════════════════════════════════════════════════════════════════════
  add(4,1,'4th Lord in 1st House','The 4th house lord in the 1st house ties home and emotional security to the self. The native\'s identity is deeply connected to their roots, mother, and domestic life. They are nurturing, with a strong attachment to family, and may derive vitality from a stable home environment.',['Nurturing and domestic nature','Strong maternal bond','Home shapes identity','Property matters influence life','Emotionally grounded']);
  add(4,2,'4th Lord in 2nd House','The 4th house lord in the 2nd house connects home and emotional security to wealth and family. The native gains financial stability through property or maternal support, enjoying a comfortable domestic life. They speak with warmth and value family traditions.',['Property and real estate gains','Warm speech and communication','Family wealth grows','Maternal financial support','Comfortable domestic life']);
  add(4,3,'4th Lord in 3rd House','The 4th house lord in the 3rd house ties home and emotional security to courage, siblings, and skills. The native finds comfort through siblings or short travels, often using their skills to enhance domestic stability. Property matters may involve siblings.',['Siblings strengthen home','Domestic skills through effort','Property via sibling connections','Emotional communication','Short travel brings home comfort']);
  add(4,4,'4th Lord in 4th House','The 4th house lord in the 4th house is a highly favorable placement for home, mother, and emotional security. The native enjoys a stable, nurturing domestic life, with a strong bond to their mother and property. They value comfort and tradition.',['Excellent domestic happiness','Strong mother bond','Abundant property','Vehicles and real estate','Deep emotional stability']);
  add(4,5,'4th Lord in 5th House','The 4th house lord in the 5th house connects home and emotional security to creativity, children, and intellect. The native finds comfort in creative pursuits or through children, often nurturing their intellectual growth. They value emotional expression.',['Creative home environment','Children bring domestic joy','Speculative property gains','Emotional-intellectual balance','Warm family creativity']);
  add(4,6,'4th Lord in 6th House','The 4th house lord in the 6th house ties home and emotional security to service, competition, and obstacles. The native works hard to maintain domestic stability, often facing challenges related to property or family. They value resilience.',['Property disputes possible','Hard work for domestic stability','Family health expenses','Domestic service orientation','Home requires constant effort']);
  add(4,7,'4th Lord in 7th House','The 4th house lord in the 7th house connects home and emotional security to partnerships and marriage. The native finds comfort and stability through marriage or alliances, often building a harmonious domestic life with their spouse\'s support.',['Spouse brings domestic comfort','Property through partnerships','Marriage creates stable home','Nurturing spouse','Relational peace in home']);
  add(4,8,'4th Lord in 8th House','The 4th house lord in the 8th house ties home and emotional security to transformation, occult, and sudden events. The native may face upheavals in domestic life or gain property through inheritance or unexpected sources.',['Inheritance of property','Sudden domestic changes','Hidden emotional issues','Transformation of home life','Resilience through domestic crises']);
  add(4,9,'4th Lord in 9th House','The 4th house lord in the 9th house connects home and emotional security to luck, spirituality, and higher learning. The native finds comfort in travel, philosophy, or spiritual pursuits, often with a stable home as their foundation.',['Fortunate domestic life','Spiritual home environment','Travel brings home peace','Property through fortune','Wise and fortunate mother']);
  add(4,10,'4th Lord in 10th House','The 4th house lord in the 10th house ties home and emotional security to career and status. The native builds a stable home through professional success, often with maternal support. They value public recognition and may gain property through their career.',['Career builds domestic stability','Maternal career influence','Property through profession','Ambitious yet family-focused','Work-life balance achieved']);
  add(4,11,'4th Lord in 11th House','The 4th house lord in the 11th house connects home and emotional security to gains, ambitions, and social networks. The native finds comfort in friendships or social circles, often gaining property through collective efforts.',['Property through social gains','Friendly domestic network','Community supports home','Gains enhance domestic life','Social ambitions bring comfort']);
  add(4,12,'4th Lord in 12th House','The 4th house lord in the 12th house ties home and emotional security to losses, spirituality, or foreign lands. The native may find comfort abroad or in spiritual pursuits, often sacrificing domestic stability. They value detachment.',['Foreign settlement possible','Spiritual home abroad','Property loss risk','Emotional detachment from roots','Inner peace replaces home comfort']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 5TH HOUSE LORD (Putra Lord / Intelligence, Children, Creativity)
  // ═══════════════════════════════════════════════════════════════════════════
  add(5,1,'5th Lord in 1st House','The 5th house lord in the 1st house ties creativity and intellect to the self. The native is imaginative, intelligent, and expresses their personality through creative pursuits or romance. They value self-expression and may be blessed with children who reflect their identity.',['High intelligence','Creative personality','Good progeny','Youthful appearance','Speculative success']);
  add(5,2,'5th Lord in 2nd House','The 5th house lord in the 2nd house connects creativity and intellect to wealth and speech. The native earns through creative talents or intellectual pursuits, often with an eloquent, artistic voice. They value financial success through innovation.',['Creative income sources','Artistic voice','Wealth through intellect','Children benefit family','Innovative financial ideas']);
  add(5,3,'5th Lord in 3rd House','The 5th house lord in the 3rd house ties creativity and intellect to courage, siblings, and skills. The native excels in creative communication, often with sibling support. They value intellectual effort.',['Creative communication','Sibling intellectual bond','Writing and media success','Artistic skills shine','Educational efforts rewarded']);
  add(5,4,'5th Lord in 4th House','The 5th house lord in the 4th house connects creativity and intellect to home, mother, and emotional security. The native finds joy in a creative home environment, often nurturing children or intellectual pursuits domestically.',['Creative home atmosphere','Children nurture home','Emotional-creative balance','Mother inspires creativity','Property through speculation']);
  add(5,5,'5th Lord in 5th House','The 5th house lord in the 5th house is a powerful placement for creativity, children, and intellect. The native excels in creative fields, enjoys a strong bond with children, and has a sharp, innovative mind. They value self-expression and romance.',['Exceptional creativity','Blessed with children','Speculative genius','Romantic and joyful','Intellectual excellence']);
  add(5,6,'5th Lord in 6th House','The 5th house lord in the 6th house ties creativity and intellect to service, competition, and obstacles. The native uses their creative talents to overcome challenges, often excelling in service-oriented fields. They may face delays with children.',['Creativity through hard work','Service with intellect','Delays in children possible','Competitive creative fields','Intelligence helps overcome obstacles']);
  add(5,7,'5th Lord in 7th House','The 5th house lord in the 7th house connects creativity and intellect to partnerships and marriage. The native finds joy in romantic or creative collaborations, often with a spouse who supports their talents.',['Creative romantic partnership','Spouse shares intellectual interests','Children strengthen marriage','Love through creativity','Charming romantic nature']);
  add(5,8,'5th Lord in 8th House','The 5th house lord in the 8th house ties creativity and intellect to transformation, occult, and sudden events. The native finds joy in deep research or mystical pursuits. They value depth and may gain through speculative risks.',['Occult and mystical intellect','Speculative depth','Children face upheavals possible','Creative transformation','Research and investigation talent']);
  add(5,9,'5th Lord in 9th House','The 5th house lord in the 9th house connects creativity and intellect to luck, spirituality, and higher learning. The native finds joy in teaching, travel, or philosophical pursuits, often blessed with intelligent children.',['Excellent fortune','Spiritual and philosophical creativity','Blessed with wise children','Higher education success','Creative luck and fortune']);
  add(5,10,'5th Lord in 10th House','The 5th house lord in the 10th house ties creativity and intellect to career and status. The native excels in creative professions, gaining recognition through their talents. They value professional success.',['Fame through creativity','Creative career excellence','Recognition for intelligence','Children aid career','Professional artistic success']);
  add(5,11,'5th Lord in 11th House','The 5th house lord in the 11th house connects creativity and intellect to gains, ambitions, and social networks. The native finds joy in creative collaborations or speculative gains, often with intelligent children or supportive friends.',['Creative gains abundant','Children bring prosperity','Speculative success','Intellectual social network','Ambitions fulfilled creatively']);
  add(5,12,'5th Lord in 12th House','The 5th house lord in the 12th house ties creativity and intellect to losses, spirituality, or foreign lands. The native finds joy in spiritual or foreign creative pursuits, often facing delays with children or artistic projects.',['Spiritual creativity','Foreign artistic success','Delays in children','Inner creative growth','Liberation through intellect']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 6TH HOUSE LORD (Ripu Lord / Service, Enemies, Health, Debts)
  // ═══════════════════════════════════════════════════════════════════════════
  add(6,1,'6th Lord in 1st House','The 6th house lord in the 1st house ties service and competition to the self. The native is hardworking, resilient, and often faces challenges that shape their identity. They value overcoming obstacles and may excel in service-oriented fields. Health requires constant effort to maintain.',['Fighting spirit dominant','Health requires attention','Service shapes identity','Enemy-defeating nature','Resilience and hard work']);
  add(6,2,'6th Lord in 2nd House','The 6th house lord in the 2nd house connects service and competition to wealth and speech. The native earns through hard work or overcoming challenges, often in service-related fields. They value resilience and may face financial disputes or health expenses.',['Earnings through effort','Sharp speech possible','Financial challenges overcome','Service income source','Health affects finances']);
  add(6,3,'6th Lord in 3rd House','The 6th house lord in the 3rd house ties service and competition to courage, siblings, and skills. The native applies effort to overcome obstacles, often with sibling involvement, excelling in competitive or service-oriented skills.',['Competitive sibling dynamics','Courage in challenges','Service through skills','Effort overcomes obstacles','Sports or martial arts talent']);
  add(6,4,'6th Lord in 4th House','The 6th house lord in the 4th house connects service and competition to home, mother, and emotional security. The native works hard to maintain domestic stability, often facing property disputes or family challenges.',['Property disputes possible','Domestic hard work','Maternal health concerns','Service within family','Home challenges build strength']);
  add(6,5,'6th Lord in 5th House','The 6th house lord in the 5th house ties service and competition to creativity, children, and intellect. The native applies effort to creative pursuits or children, often facing delays or challenges in these areas. They value resilience.',['Delays in children possible','Creative blocks overcome','Service in education','Hard-won creative success','Competitive intellectual spirit']);
  add(6,6,'6th Lord in 6th House','The 6th house lord in the 6th house is a strong placement for service, competition, and health management. The native excels in overcoming enemies or obstacles, thriving in service-oriented or competitive fields. They triumph over adversity.',['Enemy-defeating ability','Service excellence','Health discipline','Competitive mastery','Victory over obstacles']);
  add(6,7,'6th Lord in 7th House','The 6th house lord in the 7th house connects service and competition to partnerships and marriage. The native faces challenges in relationships, often working hard to maintain harmony with their spouse or partners.',['Marital challenges possible','Legal disputes with partners','Service in partnerships','Hard work maintains relationships','Health tied to relational stress']);
  add(6,8,'6th Lord in 8th House','The 6th house lord in the 8th house ties service and competition to transformation, occult, and sudden events. The native overcomes obstacles through resilience, often excelling in transformative fields like healing or research. This is Vipareeta Raja Yoga possibility.',['Viparita Raja Yoga possible','Healing and transformative service','Hidden enemies overcome','Resilience through crises','Financial gains through obstacles']);
  add(6,9,'6th Lord in 9th House','The 6th house lord in the 9th house connects service and competition to luck, spirituality, and higher learning. The native overcomes challenges through wisdom or travel, often excelling in service-oriented teaching or philosophy.',['Service in spiritual fields','Fortune through obstacles','Health wisdom gains','Philosophical resilience','Teaching as service']);
  add(6,10,'6th Lord in 10th House','The 6th house lord in the 10th house ties service and competition to career and status. The native excels in service-oriented or competitive professions (e.g., law, medicine), gaining recognition through hard work.',['Service-oriented career success','Medical or legal profession','Recognition through hard work','Work challenges strengthen','Competitive career triumph']);
  add(6,11,'6th Lord in 11th House','The 6th house lord in the 11th house connects service and competition to gains, ambitions, and social networks. The native achieves desires through hard work or teamwork, often overcoming social challenges.',['Gains through perseverance','Service income flows','Hard-won social success','Resilient ambitions','Obstacles fuel prosperity']);
  add(6,12,'6th Lord in 12th House','The 6th house lord in the 12th house ties service and competition to losses, spirituality, or foreign lands. The native overcomes challenges through spiritual or foreign efforts. This is Vipareeta Raja Yoga placement — enemies destroy each other.',['Viparita Raja Yoga strong','Enemies self-destruct','Foreign service and victory','Spiritual healing overcomes illness','Liberation through service']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 7TH HOUSE LORD (Kalatra Lord / Marriage, Partnerships, Public)
  // ═══════════════════════════════════════════════════════════════════════════
  add(7,1,'7th Lord in 1st House','The 7th house lord in the 1st house ties partnerships directly to the native\'s self-identity and personality. The individual\'s life revolves around relationships, often defining themselves through their spouse or business partners. They are charming, diplomatic, and seek harmony in all personal interactions.',['Charming diplomatic personality','Life shaped by partnerships','Attractive appearance','Marriage brings identity','Public popularity and appeal']);
  add(7,2,'7th Lord in 2nd House','The 7th house lord in the 2nd house connects partnerships to wealth, family, and speech. The native gains financial stability or resources through marriage or business alliances, often relying on their spouse or partners for material security. They speak diplomatically.',['Wealthy spouse brings prosperity','Diplomatic speech','Partnership gains financial','Family benefits from alliances','Financial security via marriage']);
  add(7,3,'7th Lord in 3rd House','The 7th house lord in the 3rd house ties partnerships to courage, siblings, and communication skills. The native collaborates with their spouse or business partners in ventures requiring effort, such as media, writing, or short-term projects.',['Partnership in communication','Spouse aids initiatives','Sibling role in marriage','Active relational teamwork','Short-term business alliances']);
  add(7,4,'7th Lord in 4th House','The 7th house lord in the 4th house connects partnerships to home, mother, and emotional security. The native finds comfort and stability through marriage or alliances, often building a harmonious domestic life with their spouse\'s support.',['Spouse brings domestic peace','Property through partnerships','Mother supports marriage','Emotional home harmony','Partnership is foundation']);
  add(7,5,'7th Lord in 5th House','The 7th house lord in the 5th house ties partnerships to creativity, children, and romance. The native enjoys a romantic and creative bond with their spouse or partners, often collaborating on artistic or intellectual pursuits.',['Romantic creative partnership','Children strengthen bonds','Spouse inspires creativity','Joyful romantic life','Partnership in creative ventures']);
  add(7,6,'7th Lord in 6th House','The 7th house lord in the 6th house connects partnerships to service, competition, and obstacles. The native faces challenges in relationships, often working hard to maintain harmony with their spouse or partners in competitive fields.',['Marital challenges require effort','Partner disputes overcome','Health tied to relationships','Service-oriented partnerships','Legal issues with partners possible']);
  add(7,7,'7th Lord in 7th House','The 7th house lord in the 7th house is a powerful placement for partnerships and marriage. The native excels in forming strong, balanced relationships, valuing harmony and cooperation above all. Their spouse or partners play a central role in their life.',['Excellent marriage prospects','Balanced harmonious partnerships','Public dealings success','Fair-minded and diplomatic','Life partner mirroring strengths']);
  add(7,8,'7th Lord in 8th House','The 7th house lord in the 8th house ties partnerships to transformation, occult, and sudden events. The native\'s relationships undergo deep changes, often involving their spouse or partners in intense, transformative experiences.',['Transformative marriage','Joint finances deep exploration','Sudden partnership changes','Occult shared interests','Profound relational growth']);
  add(7,9,'7th Lord in 9th House','The 7th house lord in the 9th house connects partnerships to luck, spirituality, and higher learning. The native finds harmony through a spouse or partners who share their philosophical or spiritual beliefs, valuing wisdom in relationships.',['Fortunate marriage','Spouse shares beliefs','Partnership brings fortune','Foreign alliances benefit','Wisdom in relationships']);
  add(7,10,'7th Lord in 10th House','The 7th house lord in the 10th house ties partnerships to career and public status. The native achieves professional success through their spouse or business alliances, valuing relationships that enhance their reputation.',['Career success through partnerships','Spouse enhances status','Business alliances drive fame','Diplomatic career excellence','Public recognition through alliances']);
  add(7,11,'7th Lord in 11th House','The 7th house lord in the 11th house connects partnerships to gains, ambitions, and social networks. The native achieves their desires through alliances with friends or partners, valuing relationships that bring collective success.',['Partnership brings abundant gains','Spouse supports ambitions','Social prosperity through alliances','Shared goals fulfilled','Network through partnerships']);
  add(7,12,'7th Lord in 12th House','The 7th house lord in the 12th house ties partnerships to losses, spirituality, or foreign lands. The native may form alliances abroad or in spiritual contexts, valuing detachment or privacy in relationships. Partnerships may involve sacrifice or distance.',['Foreign spouse possible','Spiritual partnerships','Partnership requires sacrifice','Distant or private relationships','Liberation through letting go']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 8TH HOUSE LORD (Ayu Lord / Transformation, Longevity, Occult)
  // ═══════════════════════════════════════════════════════════════════════════
  add(8,1,'8th Lord in 1st House','The 8th house lord in the 1st house ties transformation to the self. The native undergoes significant personal changes, often through intense experiences that shape their identity. They are drawn to the occult or mysteries, valuing depth over superficiality. Health may be fragile, prone to sudden issues.',['Profound personal transformation','Occult and mystical interest','Health vulnerabilities','Deep secretive nature','Resilience through life crises']);
  add(8,2,'8th Lord in 2nd House','The 8th house lord in the 2nd house connects transformation to wealth and family. The native experiences sudden financial ups and downs, often gaining through inheritance or hidden sources. Their speech may probe secrets and family matters involve hidden tensions.',['Inheritance of wealth','Sudden financial shifts','Speech probes secrets','Family hidden dynamics','Financial transformation']);
  add(8,3,'8th Lord in 3rd House','The 8th house lord in the 3rd house ties transformation to courage, siblings, and skills. The native applies intense effort in research or mysteries. Siblings may face upheavals, and their communication style is penetrating and probing.',['Research and investigative skills','Sibling transformation','Intense communication','Skills applied to occult','Courage through crises']);
  add(8,4,'8th Lord in 4th House','The 8th house lord in the 4th house connects transformation to home, mother, and emotional security. The native may experience upheavals in domestic life, sudden property changes, or maternal health issues. They find hidden comfort in transformation.',['Domestic upheavals possible','Property from unexpected sources','Mother health challenges','Hidden home dynamics','Transformation of domestic life']);
  add(8,5,'8th Lord in 5th House','The 8th house lord in the 5th house ties transformation to creativity, children, and intellect. The native finds joy in deep research or mystical pursuits. Speculative gains are possible but risky. Children may face challenges.',['Occult intellect','Risky speculation','Delays or challenges with children','Deep creative transformation','Research brings joy']);
  add(8,6,'8th Lord in 6th House','The 8th house lord in the 6th house connects transformation to service and enemies. This is Vipareeta Raja Yoga — obstacles and enemies are transformed into victories. The native gains strength through healing and service.',['Viparita Raja Yoga','Hidden enemies become friends','Healing profession success','Transformation through service','Victory over chronic issues']);
  add(8,7,'8th Lord in 7th House','The 8th house lord in the 7th house ties transformation to partnerships and marriage. Relationships undergo intense transformation, and the native may face sudden changes in marriage or partnerships. Joint finances may fluctuate.',['Intense transformative marriage','Partnership upheavals','Joint finances challenging','Depth in relationships','Growth through relational crises']);
  add(8,8,'8th Lord in 8th House','The 8th house lord in the 8th house is a powerful but intense placement for longevity, transformation, and occult. The native has exceptional resilience, deep interest in mysteries, and possible psychic abilities. Longevity is generally favored.',['Strong longevity indicator','Occult mastery','Psychic and intuitive abilities','Transformation through depth','Research and investigative excellence']);
  add(8,9,'8th Lord in 9th House','The 8th house lord in the 9th house connects transformation to luck, spirituality, and higher learning. The native finds fortune through deep spiritual inquiry or occult studies. Father may face health challenges. Transformation serves spiritual growth.',['Spiritual transformation','Occult wisdom as fortune','Father\'s health may be challenged','Hidden spiritual knowledge','Fortune through depth']);
  add(8,10,'8th Lord in 10th House','The 8th house lord in the 10th house ties transformation to career and status. The native excels in fields involving change or depth (e.g., research, crisis management). Their status undergoes dramatic shifts, tied to hidden or intense efforts.',['Career in research or crisis management','Status transformation','Hidden professional efforts','Sudden career upheavals','Fame through intense work']);
  add(8,11,'8th Lord in 11th House','The 8th house lord in the 11th house connects transformation to gains, ambitions, and social networks. The native achieves ambitions through deep changes or hidden means. Gains may come unexpectedly or through inheritance.',['Unexpected gains possible','Transformation brings prosperity','Hidden income sources','Gains through depth and research','Social upheavals then success']);
  add(8,12,'8th Lord in 12th House','The 8th house lord in the 12th house ties transformation to losses, spirituality, or foreign lands. This is Vipareeta Raja Yoga — transformation and losses cancel each other. The native gains through spiritual practices and may have exceptional longevity.',['Viparita Raja Yoga strong','Spiritual liberation potential','Exceptional longevity possible','Occult expertise abroad','Hidden wisdom gains']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 9TH HOUSE LORD (Dharma Lord / Fortune, Spirituality, Father)
  // ═══════════════════════════════════════════════════════════════════════════
  add(9,1,'9th Lord in 1st House','The 9th house lord in the 1st house connects fortune and spirituality to the self. The native is blessed with immense luck, wisdom, and a strong sense of purpose. They radiate positivity and are guided by dharmic principles. Father may be influential in shaping their identity.',['Highly fortunate personality','Dharmic and righteous nature','Father shapes identity','Philosophical wisdom','Luck in all endeavors']);
  add(9,2,'9th Lord in 2nd House','The 9th house lord in the 2nd house ties fortune to wealth, family, and speech. The native earns through fortunate means, often in fields requiring wisdom or communication. Their speech is inspiring and their family is blessed.',['Wealth through fortune','Wise and inspiring speech','Prosperous family','Teaching and speaking income','Lucky financial life']);
  add(9,3,'9th Lord in 3rd House','The 9th house lord in the 3rd house connects fortune and spirituality to courage, siblings, and skills. The native applies effort in teaching, travel, or philosophical pursuits, often with fortunate outcomes. Their voice is wise and motivating.',['Fortune through effort and skills','Wise communication','Sibling fortune','Travel brings luck','Writing and teaching blessed']);
  add(9,4,'9th Lord in 4th House','The 9th house lord in the 4th house ties fortune to home, mother, and emotional security. The native finds fortune through domestic stability, and their home is blessed. Their mother is wise and fortunate. Property gains are highly favored.',['Blessed home environment','Fortunate and wise mother','Property gains through luck','Spiritual home','Education and wisdom at home']);
  add(9,5,'9th Lord in 5th House','The 9th house lord in the 5th house connects fortune and spirituality to creativity, children, and intellect. The native finds joy in teaching, travel, or philosophical pursuits, often blessed with intelligent children. This is an excellent Dharma-Putra yoga.',['Excellent dharma-putra yoga','Intelligent fortunate children','Creative spiritual expression','Fortune through education','Speculative luck']);
  add(9,6,'9th Lord in 6th House','The 9th house lord in the 6th house ties fortune to service, competition, and obstacles. The native overcomes challenges through wisdom or travel, excelling in service-oriented teaching or philosophy. Fortune comes through dedicated service.',['Fortune through service','Wisdom overcomes obstacles','Spiritual approach to challenges','Health improves with faith','Teaching in service fields']);
  add(9,7,'9th Lord in 7th House','The 9th house lord in the 7th house connects fortune and spirituality to partnerships and marriage. The native finds harmony through a spouse or partners who share their philosophical or spiritual beliefs. Foreign alliances are beneficial.',['Fortunate marriage','Spouse shares spiritual values','Fortune through partnerships','Foreign alliances bring luck','Wisdom in relationships']);
  add(9,8,'9th Lord in 8th House','The 9th house lord in the 8th house ties fortune to transformation, longevity, and occult. The native finds fortune through deep spiritual inquiry or occult studies. This is a spiritually powerful but materially challenging placement.',['Spiritual occult fortune','Deep philosophical transformation','Longevity through spirituality','Fortune through hidden knowledge','Mystic spiritual seeker']);
  add(9,9,'9th Lord in 9th House','The 9th house lord in the 9th house is a highly favorable placement for luck, spirituality, and wisdom. The native is blessed with immense fortune, spiritual depth, and a strong connection to father or gurus. They thrive in higher learning or travel.',['Exceptional fortune','Deep spirituality','Blessed father and guru','Higher education mastery','Travel and philosophy blessed']);
  add(9,10,'9th Lord in 10th House','The 9th house lord in the 10th house ties luck to career and status. The native achieves professional success through fortunate circumstances, often guided by father or higher wisdom. They value integrity in work.',['Career blessed by fortune','Father influences career','Reputation for integrity','Status through dharma','Professional wisdom recognized']);
  add(9,11,'9th Lord in 11th House','The 9th house lord in the 11th house connects luck to gains, ambitions, and social networks. The native achieves desires through fortunate alliances or social efforts, valuing wisdom in friendships. Gains come through divine favor.',['Fortunate gains','Desires fulfilled through luck','Wise social network','Blessed ambitions','Fortune through friends']);
  add(9,12,'9th Lord in 12th House','The 9th house lord in the 12th house ties luck to losses, spirituality, or foreign lands. The native finds fortune through spiritual pursuits or foreign experiences, valuing detachment. They may sacrifice material gains for higher wisdom.',['Fortune through spirituality','Foreign luck and travel','Moksha-oriented fortune','Spiritual detachment as luck','Wisdom beyond material']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 10TH HOUSE LORD (Karma Lord / Career, Status, Authority)
  // ═══════════════════════════════════════════════════════════════════════════
  add(10,1,'10th Lord in 1st House','The 10th house lord in the 1st house ties career and status directly to the self. The native\'s identity is defined by their professional achievements. They are highly ambitious, authoritative, and achieve significant public recognition. Health and vitality are channeled toward career success.',['Strong career identity','Public authority and fame','Ambitious and disciplined','Professional excellence','Leadership recognized']);
  add(10,2,'10th Lord in 2nd House','The 10th house lord in the 2nd house connects career to wealth, family, and speech. The native\'s professional success directly impacts their financial stability, often earning through authoritative or public-facing roles. They value recognition through resources and use eloquent speech to enhance their status.',['Career brings financial prosperity','Authoritative eloquent speech','Family legacy through career','Status enhances wealth','Public-facing profession success']);
  add(10,3,'10th Lord in 3rd House','The 10th house lord in the 3rd house ties career to courage, siblings, and communication skills. The native excels in professions requiring effort or media (e.g., journalism, marketing), valuing recognition through initiative and teamwork. Siblings may support their career.',['Media and communication career','Career through persistent effort','Sibling career support','Initiative brings recognition','Writing and publishing success']);
  add(10,4,'10th Lord in 4th House','The 10th house lord in the 4th house connects career to home, mother, and emotional security. The native\'s professional life is tied to domestic stability, often succeeding in fields like real estate or education. Their mother or home environment influences their career choices.',['Real estate or educational career','Mother influences profession','Domestic and career balance','Property through career','Status builds home security']);
  add(10,5,'10th Lord in 5th House','The 10th house lord in the 5th house ties career to creativity, children, and intellect. The native excels in creative or speculative professions (e.g., arts, teaching), valuing recognition through self-expression or mentorship. Their children may inspire or contribute to their status.',['Creative profession success','Recognition for intellect','Children support career','Speculative career gains','Artistic excellence recognized']);
  add(10,6,'10th Lord in 6th House','The 10th house lord in the 6th house connects career to service, competition, and obstacles. The native succeeds in service-oriented or competitive fields (e.g., law, healthcare), valuing recognition through overcoming challenges. Career involves hard-fought victories.',['Service profession excellence','Law medicine military success','Career through competition','Status earned through struggle','Resilience builds reputation']);
  add(10,7,'10th Lord in 7th House','The 10th house lord in the 7th house ties career to partnerships and public dealings. The native\'s professional success depends on alliances, often thriving in business or legal partnerships. Their spouse or partners significantly influence their status.',['Business partnership career','Spouse enhances career','Public dealing profession','Diplomatic career success','Alliance-based professional fame']);
  add(10,8,'10th Lord in 8th House','The 10th house lord in the 8th house connects career to transformation, occult, and sudden events. The native excels in fields involving change or depth (e.g., research, crisis management). Their status undergoes dramatic shifts, often tied to hidden or intense efforts.',['Research and investigation career','Career transformations','Hidden professional talents','Crisis management expertise','Status through intense work']);
  add(10,9,'10th Lord in 9th House','The 10th house lord in the 9th house ties career to luck, spirituality, and higher learning. The native achieves professional success through fortunate circumstances or wisdom-based fields. Their father or beliefs shape their career path. This is an excellent yoga.',['Extremely fortunate career','Dharmic profession','Father guides career','Teaching and philosophy career','Status blessed by fortune']);
  add(10,10,'10th Lord in 10th House','The 10th house lord in the 10th house is a powerful placement for career and status. The native excels in their chosen profession, valuing recognition through authority and hard work. They are ambitious, disciplined, and thrive in public roles.',['Exceptional career excellence','Authority and fame','Disciplined professional','Public prominence','Lasting career success']);
  add(10,11,'10th Lord in 11th House','The 10th house lord in the 11th house connects career to gains, ambitions, and social networks. The native achieves professional success through teamwork or influential connections, valuing recognition through collective efforts. Gains come through career achievements.',['Career brings abundant gains','Social network drives success','Collective professional achievement','Prosperity through status','Ambitions fulfilled via career']);
  add(10,12,'10th Lord in 12th House','The 10th house lord in the 12th house ties career to losses, spirituality, or foreign lands. The native\'s professional life may involve sacrifice or foreign work (e.g., NGOs, international roles). They face career setbacks but find success in isolation or spiritual fields.',['Foreign or NGO career','Career through sacrifice','Unconventional profession','Status through spiritual service','Career abroad possible']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 11TH HOUSE LORD (Labha Lord / Gains, Ambitions, Social Networks)
  // ═══════════════════════════════════════════════════════════════════════════
  add(11,1,'11th Lord in 1st House','The 11th house lord in the 1st house ties gains to the self. The native\'s ambitions shape their identity, valuing personal effort in achieving prosperity. They attract supportive networks and thrive socially, with health reflecting fulfillment from success.',['Ambitious personality','Gains through personal effort','Supportive social network','Prosperity shapes identity','Social fulfillment']);
  add(11,2,'11th Lord in 2nd House','The 11th house lord in the 2nd house connects gains to wealth and family. The native achieves financial prosperity through social networks or ambitions, valuing resources as a measure of success. Their speech attracts opportunities.',['Financial prosperity','Speech attracts opportunities','Family prospers through gains','Social wealth building','Legacy through achievements']);
  add(11,3,'11th Lord in 3rd House','The 11th house lord in the 3rd house ties gains to courage, siblings, and skills. The native achieves ambitions through effort or communication, often with sibling support, valuing success through teamwork. Their skills attract prosperity.',['Gains through communication','Sibling support for success','Skills bring prosperity','Teamwork achieves ambitions','Initiative earns gains']);
  add(11,4,'11th Lord in 4th House','The 11th house lord in the 4th house connects gains to home, mother, and emotional security. The native\'s ambitions bring domestic prosperity, often through property or family support. Their mother may aid their goals.',['Domestic prosperity','Property gains','Mother aids ambitions','Gains enhance home comfort','Community property success']);
  add(11,5,'11th Lord in 5th House','The 11th house lord in the 5th house ties gains to creativity, children, and intellect. The native achieves ambitions through creative pursuits or progeny, valuing success through self-expression. Their children may bring prosperity.',['Creative gains','Children bring prosperity','Speculative success','Intellectual achievements rewarded','Joy from prosperous creativity']);
  add(11,6,'11th Lord in 6th House','The 11th house lord in the 6th house connects gains to service, competition, and obstacles. The native achieves ambitions through overcoming challenges, often in service fields. Gains come after persistent effort.',['Hard-won gains','Service brings prosperity','Perseverance over obstacles','Competition yields success','Health-related income possible']);
  add(11,7,'11th Lord in 7th House','The 11th house lord in the 7th house ties gains to partnerships and public dealings. The native achieves ambitions through alliances or spouse support, valuing success through collaboration. Social prosperity comes via partnerships.',['Partnership brings gains','Spouse supports ambitions','Business alliance prosperity','Social gains through alliances','Cooperative success']);
  add(11,8,'11th Lord in 8th House','The 11th house lord in the 8th house connects gains to transformation, occult, and sudden events. The native achieves ambitions through deep changes or hidden means. Gains may come unexpectedly or through inheritance.',['Unexpected gains','Inheritance prosperity','Hidden income sources','Transformation yields gains','Occult financial insight']);
  add(11,9,'11th Lord in 9th House','The 11th house lord in the 9th house ties gains to luck, spirituality, and higher learning. The native achieves ambitions through fortunate circumstances or wisdom. Social prosperity aligns with beliefs, and health benefits from optimism.',['Fortunate gains','Wisdom brings prosperity','Travel yields income','Philosophical social success','Divine favor in ambitions']);
  add(11,10,'11th Lord in 10th House','The 11th house lord in the 10th house connects gains to career and status. The native achieves ambitions through professional success, valuing recognition through social influence. Their career brings prosperity.',['Career brings abundant gains','Social recognition','Professional prosperity','Status yields fulfillment','Ambitions realized through career']);
  add(11,11,'11th Lord in 11th House','The 11th house lord in the 11th house is a powerful placement for gains and ambitions. The native excels in achieving desires through social networks, valuing success through collective efforts. They attract abundant prosperity.',['Exceptional gains and prosperity','Social network excellence','Desires easily fulfilled','Community support abundant','Ambitions realized with ease']);
  add(11,12,'11th Lord in 12th House','The 11th house lord in the 12th house ties gains to losses, spirituality, or foreign lands. The native achieves ambitions through sacrifice or distant efforts. Prosperity may come indirectly, and health is tied to emotional peace.',['Foreign gains possible','Gains through sacrifice','Spiritual prosperity','Indirect income sources','Liberation brings ultimate gain']);

  // ═══════════════════════════════════════════════════════════════════════════
  // 12TH HOUSE LORD (Vyaya Lord / Losses, Spirituality, Liberation)
  // ═══════════════════════════════════════════════════════════════════════════
  add(12,1,'12th Lord in 1st House','The 12th house lord in the 1st house ties losses to the self. The native may sacrifice personal desires for spiritual growth, valuing detachment over ego. They are drawn to isolation or foreign experiences, with health reflecting emotional depth.',['Spiritual identity','Sacrifices shape personality','Foreign travels likely','Introspective nature','Health requires attention']);
  add(12,2,'12th Lord in 2nd House','The 12th house lord in the 2nd house connects losses to wealth and family. The native may face financial setbacks or sacrifices for others, valuing spiritual wealth over material gain. Their speech reflects detachment.',['Financial sacrifices','Spiritual wealth over material','Family expenses high','Speech of detachment','Resources flow outward']);
  add(12,3,'12th Lord in 3rd House','The 12th house lord in the 3rd house ties losses to courage, siblings, and skills. The native may sacrifice efforts or face setbacks in communication, valuing detachment in action. Siblings may be distant.',['Sibling distance possible','Communication sacrificed','Skills for inner growth','Efforts lead to spirituality','Foreign short travel']);
  add(12,4,'12th Lord in 4th House','The 12th house lord in the 4th house connects losses to home, mother, and emotional security. The native may sacrifice domestic stability or face separation from home, valuing spiritual peace over attachment. Their mother may be distant.',['Domestic sacrifice','Foreign home possible','Mother may be distant','Property losses risk','Inner peace over attachment']);
  add(12,5,'12th Lord in 5th House','The 12th house lord in the 5th house ties losses to creativity, children, and intellect. The native may sacrifice creative pursuits or face delays in progeny, valuing spiritual growth over expression. Their intellect seeks liberation.',['Delays in children','Creative sacrifice for spirituality','Spiritual intellect','Moksha through creativity','Past karma affects progeny']);
  add(12,6,'12th Lord in 6th House','The 12th house lord in the 6th house connects losses to service, enemies, and health. This creates Vipareeta Raja Yoga — enemies and health issues transform into spiritual strength. The native gains through service and sacrifice.',['Viparita Raja Yoga','Enemies become weak','Health challenges become strength','Service yields liberation','Spiritual resilience']);
  add(12,7,'12th Lord in 7th House','The 12th house lord in the 7th house ties losses to partnerships and marriage. The native may sacrifice relationships or face distance from partners, valuing spiritual growth over attachment. Their spouse may be linked to foreign lands.',['Foreign spouse possible','Marriage requires sacrifice','Spiritual partnership','Partners may be distant','Liberation through relationships']);
  add(12,8,'12th Lord in 8th House','The 12th house lord in the 8th house connects losses to transformation and occult. This is Vipareeta Raja Yoga — both 8th and 12th house themes intensify but ultimately cancel harmful effects. Spiritual depth and occult mastery are indicated.',['Viparita Raja Yoga strong','Occult and spiritual mastery','Liberation through transformation','Mystical practices beneficial','Eventual spiritual victory']);
  add(12,9,'12th Lord in 9th House','The 12th house lord in the 9th house ties losses to luck, spirituality, and higher learning. The native sacrifices material gains for spiritual wisdom, valuing detachment in beliefs or travel. Their father may be distant but provides spiritual blessings.',['Spiritual fortune','Father may be distant','Wisdom through detachment','Foreign spiritual journeys','Liberation as ultimate dharma']);
  add(12,10,'12th Lord in 10th House','The 12th house lord in the 10th house connects losses to career and status. The native sacrifices professional ambitions for spiritual or foreign pursuits. Their career may involve setbacks, but they find success in unconventional or distant paths.',['Career through sacrifice','Foreign profession','Unconventional status','Service-oriented work','Status through detachment']);
  add(12,11,'12th Lord in 11th House','The 12th house lord in the 11th house ties losses to gains, ambitions, and social networks. The native sacrifices ambitions or social ties for spiritual growth, valuing liberation over prosperity. Gains may be elusive but fulfillment comes through detachment.',['Gains through sacrifice','Social detachment needed','Spiritual fulfillment over wealth','Liberation over prosperity','Indirect gains from letting go']);
  add(12,12,'12th Lord in 12th House','The 12th house lord in the 12th house is a potent placement for losses, spirituality, and liberation. The native thrives in isolation, foreign lands, or spiritual pursuits, valuing detachment above all. They embrace sacrifice willingly, and health reflects inner peace.',['Exceptional spiritual depth','Isolation brings peace','Liberation and moksha',  'Foreign residence blessed','Complete spiritual surrender']);

  // Insert in batches
  const batchSize = 50;
  for (let i = 0; i < rows.length; i += batchSize) {
    await knex('house_lord_interpretations').insert(rows.slice(i, i + batchSize));
  }

  console.log(`✅  Inserted ${rows.length} house lord interpretations (${rows.length === 144 ? 'COMPLETE 12×12' : 'PARTIAL'})`);
};
