exports.seed = async (knex) => {
  await knex('remedy_puja_steps').del();
  await knex('remedy_problems').del();
  await knex('remedy_planets').del();

  // ── Section 1: Planet → Ishta Devata + Mantras ─────────────────────────────
  await knex('remedy_planets').insert([
    {
      planet: 'Sun',
      planet_hi: 'सूर्य',
      ishta_devata_en: 'Lord Rama / Surya Narayan',
      ishta_devata_hi: 'भगवान राम / सूर्य नारायण',
      mantras_en: JSON.stringify(['Surya Upanishad (primary Vedic text for Sun worship and solar energy activation)']),
      mantras_hi: JSON.stringify(['सूर्य उपनिषद (सूर्य पूजा एवं सौर ऊर्जा सक्रियण के लिए प्राथमिक वैदिक ग्रंथ)']),
      special_notes_en: 'Surya Upanishad is the primary Vedic text for Sun worship. Recite facing East in Brahma Muhurat for best results.',
      special_notes_hi: 'सूर्य उपनिषद सूर्य उपासना का प्राथमिक वैदिक ग्रंथ है। सर्वोत्तम परिणाम के लिए ब्रह्म मुहूर्त में पूर्व दिशा में मुख करके पाठ करें।',
      tradition: 'vedic',
    },
    {
      planet: 'Moon',
      planet_hi: 'चंद्र',
      ishta_devata_en: 'Lord Krishna / Shiva',
      ishta_devata_hi: 'भगवान कृष्ण / शिव',
      mantras_en: JSON.stringify([
        'Sri Rudram — Namakam & Chamakam (~34 minutes)',
        'Vastu Suktam — 1001 times for 90 days facing East (for Vastu Dosh)',
      ]),
      mantras_hi: JSON.stringify([
        'श्री रुद्रम् — नमकम् और चमकम् (लगभग ३४ मिनट)',
        'वास्तु सूक्तम् — ९० दिनों तक १००१ बार पूर्व दिशा में (वास्तुदोष के लिए)',
      ]),
      special_notes_en: 'For Vastu Dosh: Place a Parad or Narmadeshwar Shiv Linga and recite Vastu Suktam 1001 times daily for 90 consecutive days, facing East.',
      special_notes_hi: 'वास्तुदोष के लिए: पारद या नर्मदेश्वर शिव लिंग स्थापित करें और ९० दिनों तक प्रतिदिन पूर्व दिशा में मुख करके वास्तु सूक्तम् का १००१ बार पाठ करें।',
      tradition: 'vedic',
    },
    {
      planet: 'Mars',
      planet_hi: 'मंगल',
      ishta_devata_en: 'Hanuman / Kartikeya / Narsimha',
      ishta_devata_hi: 'हनुमान / कार्तिकेय / नरसिंह',
      mantras_en: JSON.stringify([
        'Hanuman Bahuk — for diseases and health issues',
        'Rog Nivaran Suktam — for disease relief',
        'Rinn Mochan Mangal Stotra — for debts and financial burden',
        'Pragya Vivardhan Stotra — for miscarriage, abortion, anger, and aggression',
      ]),
      mantras_hi: JSON.stringify([
        'हनुमान बाहुक — रोगों एवं स्वास्थ्य समस्याओं के लिए',
        'रोग निवारण सूक्तम् — रोग मुक्ति के लिए',
        'ऋण मोचन मंगल स्तोत्र — ऋण एवं आर्थिक बोझ के लिए',
        'प्रज्ञा विवर्धन स्तोत्र — गर्भपात, क्रोध एवं आक्रामकता के लिए',
      ]),
      special_notes_en: 'Mars remedies are highly specific by problem. Choose Hanuman Bahuk for disease, Rinn Mochan Mangal Stotra for debts, and Pragya Vivardhan Stotra for anger/miscarriage.',
      special_notes_hi: 'मंगल उपाय समस्या के अनुसार चुनें। रोग के लिए हनुमान बाहुक, ऋण के लिए ऋण मोचन मंगल स्तोत्र, और क्रोध/गर्भपात के लिए प्रज्ञा विवर्धन स्तोत्र।',
      tradition: 'pauranik',
    },
    {
      planet: 'Mercury',
      planet_hi: 'बुध',
      ishta_devata_en: 'Lord Vishnu',
      ishta_devata_hi: 'भगवान विष्णु',
      mantras_en: JSON.stringify([
        'Vishnu Suktam',
        'Narayan Suktam',
        'Purusha Suktam',
      ]),
      mantras_hi: JSON.stringify([
        'विष्णु सूक्तम्',
        'नारायण सूक्तम्',
        'पुरुष सूक्तम्',
      ]),
      special_notes_en: 'All three suktams are Vedic in origin. Recite facing East. These strengthen communication, intelligence, and business abilities.',
      special_notes_hi: 'तीनों सूक्तम् वैदिक हैं। पूर्व दिशा में मुख करके पाठ करें। ये संचार, बुद्धि एवं व्यवसाय को बलवर्धन करते हैं।',
      tradition: 'vedic',
    },
    {
      planet: 'Jupiter',
      planet_hi: 'बृहस्पति',
      ishta_devata_en: 'Vishnu / Brihaspati',
      ishta_devata_hi: 'विष्णु / बृहस्पति',
      mantras_en: JSON.stringify([
        'Vishnu Suktam',
        'Narayan Suktam',
        'Purusha Suktam',
        'Medha Suktam — for intelligence and wisdom',
        'Navgraha Suktam — THE most powerful among all suktams (can be used for any Navagraha issue)',
      ]),
      mantras_hi: JSON.stringify([
        'विष्णु सूक्तम्',
        'नारायण सूक्तम्',
        'पुरुष सूक्तम्',
        'मेधा सूक्तम् — बुद्धि और ज्ञान के लिए',
        'नवग्रह सूक्तम् — सभी सूक्तमों में सर्वाधिक शक्तिशाली (किसी भी ग्रह दोष के लिए उपयोगी)',
      ]),
      special_notes_en: 'Navgraha Suktam is considered the most powerful among all suktams and can be recited for ANY Navagraha-related issue — not only Jupiter.',
      special_notes_hi: 'नवग्रह सूक्तम् को सभी सूक्तमों में सर्वाधिक शक्तिशाली माना जाता है और यह किसी भी नवग्रह समस्या के लिए उपयोगी है।',
      tradition: 'vedic',
    },
    {
      planet: 'Venus',
      planet_hi: 'शुक्र',
      ishta_devata_en: 'Lakshmi / Parvati',
      ishta_devata_hi: 'लक्ष्मी / पार्वती',
      mantras_en: JSON.stringify([
        'Sri Suktam — for wealth and prosperity',
        'Devi Suktam',
      ]),
      mantras_hi: JSON.stringify([
        'श्री सूक्तम् — सम्पत्ति और समृद्धि के लिए',
        'देवी सूक्तम्',
      ]),
      special_notes_en: 'Sri Suktam is the primary remedy for wealth, luxury, relationships, and Venus-related matters. Recite on Fridays for best results.',
      special_notes_hi: 'श्री सूक्तम् धन, वैभव, संबंध और शुक्र से जुड़े विषयों का प्रमुख उपाय है। शुक्रवार को पाठ करने से श्रेष्ठ फल मिलता है।',
      tradition: 'vedic',
    },
    {
      planet: 'Saturn',
      planet_hi: 'शनि',
      ishta_devata_en: 'Shani / Bhairava / Rudra',
      ishta_devata_hi: 'शनि / भैरव / रुद्र',
      mantras_en: JSON.stringify([
        'Sri Rudram — Namakam & Chamakam (~34 minutes)',
      ]),
      mantras_hi: JSON.stringify([
        'श्री रुद्रम् — नमकम् और चमकम् (लगभग ३४ मिनट)',
      ]),
      special_notes_en: 'Sri Rudram is shared between Moon (Krishna/Shiva) and Saturn (Shani/Bhairava/Rudra). For Sade Sati or Saturn afflictions, consistent daily recitation is most effective.',
      special_notes_hi: 'श्री रुद्रम् चंद्र और शनि दोनों का उपाय है। साढ़ेसाती या शनि दोष के लिए प्रतिदिन नियमित पाठ सर्वाधिक प्रभावशाली है।',
      tradition: 'vedic',
    },
    {
      planet: 'Rahu',
      planet_hi: 'राहु',
      ishta_devata_en: 'Durga / Kali',
      ishta_devata_hi: 'दुर्गा / काली',
      mantras_en: JSON.stringify([
        'Durga Suktam',
        'Durga Kavach',
      ]),
      mantras_hi: JSON.stringify([
        'दुर्गा सूक्तम्',
        'दुर्गा कवच',
      ]),
      special_notes_en: 'Rahu is pacified through Durga and Kali worship. Durga Kavach provides protection against Rahu-related fears, illusions, and sudden negative events.',
      special_notes_hi: 'राहु को दुर्गा और काली उपासना से शांत किया जाता है। दुर्गा कवच राहु जनित भय, भ्रम और अचानक नकारात्मक घटनाओं से रक्षा करता है।',
      tradition: 'pauranik',
    },
    {
      planet: 'Ketu',
      planet_hi: 'केतु',
      ishta_devata_en: 'Ganesha',
      ishta_devata_hi: 'गणेश',
      mantras_en: JSON.stringify([
        'Ganapati Atharva Sheersha',
        'Ganapati Prarthna',
        'Mayuresh Stotra',
      ]),
      mantras_hi: JSON.stringify([
        'गणपति अथर्वशीर्ष',
        'गणपति प्रार्थना',
        'मयूरेश स्तोत्र',
      ]),
      special_notes_en: 'Ganesha is the Ishta Devata for Ketu. Ganapati Atharva Sheersha is the most powerful Vedic text for Ketu remediation. Always begin every puja with Ganapati Prarthna.',
      special_notes_hi: 'गणेश केतु के इष्ट देवता हैं। गणपति अथर्वशीर्ष केतु उपाय के लिए सर्वाधिक शक्तिशाली वैदिक ग्रंथ है। प्रत्येक पूजा का आरंभ गणपति प्रार्थना से करें।',
      tradition: 'both',
    },
  ]);

  // ── Section 7: Problem → Mantra Reference ──────────────────────────────────
  await knex('remedy_problems').insert([
    {
      problem_en: 'Diseases & Health Issues',
      problem_hi: 'रोग एवं स्वास्थ्य समस्याएं',
      planet: 'Mars',
      devata_en: 'Hanuman',
      devata_hi: 'हनुमान',
      mantras_en: JSON.stringify(['Hanuman Bahuk', 'Rog Nivaran Suktam']),
      mantras_hi: JSON.stringify(['हनुमान बाहुक', 'रोग निवारण सूक्तम्']),
      notes_en: 'Hanuman Bahuk was composed by Tulsidas for relief from physical ailments. Rog Nivaran Suktam directly addresses disease removal.',
      notes_hi: 'हनुमान बाहुक की रचना तुलसीदास ने शारीरिक रोगों से मुक्ति के लिए की थी। रोग निवारण सूक्तम् सीधे रोग निवारण के लिए है।',
    },
    {
      problem_en: 'Debts & Financial Burden',
      problem_hi: 'ऋण एवं आर्थिक बोझ',
      planet: 'Mars',
      devata_en: 'Hanuman / Kartikeya',
      devata_hi: 'हनुमान / कार्तिकेय',
      mantras_en: JSON.stringify(['Rinn Mochan Mangal Stotra']),
      mantras_hi: JSON.stringify(['ऋण मोचन मंगल स्तोत्र']),
      notes_en: 'Rinn Mochan Mangal Stotra specifically addresses liberation from debt and financial burdens. Recite on Tuesdays for amplified effect.',
      notes_hi: 'ऋण मोचन मंगल स्तोत्र विशेष रूप से ऋण और आर्थिक बोझ से मुक्ति के लिए है। मंगलवार को पाठ करने से विशेष फल मिलता है।',
    },
    {
      problem_en: 'Miscarriage & Abortion Prevention',
      problem_hi: 'गर्भपात निवारण',
      planet: 'Mars',
      devata_en: 'Narsimha',
      devata_hi: 'नरसिंह',
      mantras_en: JSON.stringify(['Pragya Vivardhan Stotra']),
      mantras_hi: JSON.stringify(['प्रज्ञा विवर्धन स्तोत्र']),
      notes_en: 'Pragya Vivardhan Stotra invokes Narsimha energy for protection, strength, and resolution of Mars-related reproductive challenges.',
      notes_hi: 'प्रज्ञा विवर्धन स्तोत्र नरसिंह की शक्ति को सुरक्षा, बल और मंगल जनित प्रजनन समस्याओं के निवारण के लिए आह्वान करता है।',
    },
    {
      problem_en: 'Anger & Aggression',
      problem_hi: 'क्रोध एवं आक्रामकता',
      planet: 'Mars',
      devata_en: 'Narsimha',
      devata_hi: 'नरसिंह',
      mantras_en: JSON.stringify(['Pragya Vivardhan Stotra']),
      mantras_hi: JSON.stringify(['प्रज्ञा विवर्धन स्तोत्र']),
      notes_en: 'Uncontrolled anger and aggression are signs of afflicted Mars. Pragya Vivardhan Stotra transforms raw Mars energy into protective, conscious strength.',
      notes_hi: 'अनियंत्रित क्रोध और आक्रामकता पीड़ित मंगल के लक्षण हैं। प्रज्ञा विवर्धन स्तोत्र मंगल की कच्ची ऊर्जा को सुरक्षात्मक और सचेत बल में बदलता है।',
    },
    {
      problem_en: 'Vastu Dosh',
      problem_hi: 'वास्तु दोष',
      planet: 'Moon',
      devata_en: 'Shiva',
      devata_hi: 'शिव',
      mantras_en: JSON.stringify([
        'Vastu Suktam — 1001 repetitions daily for 90 days, facing East',
        'Place Parad or Narmadeshwar Shiv Linga in the home',
      ]),
      mantras_hi: JSON.stringify([
        'वास्तु सूक्तम् — ९० दिनों तक प्रतिदिन १००१ बार, पूर्व दिशा में मुख करके',
        'घर में पारद या नर्मदेश्वर शिव लिंग स्थापित करें',
      ]),
      notes_en: 'Vastu Dosh requires the full 90-day sadhana cycle (not 43 days). The Parad or Narmadeshwar Shiv Linga is placed as a physical remedy. Facing East is mandatory.',
      notes_hi: 'वास्तुदोष के लिए पूरे ९० दिन का साधना चक्र आवश्यक है (४३ दिन नहीं)। पारद या नर्मदेश्वर शिव लिंग भौतिक उपाय के रूप में स्थापित किया जाता है। पूर्व दिशा अनिवार्य है।',
    },
    {
      problem_en: 'Wealth & Prosperity',
      problem_hi: 'धन एवं समृद्धि',
      planet: 'Venus',
      devata_en: 'Lakshmi',
      devata_hi: 'लक्ष्मी',
      mantras_en: JSON.stringify(['Sri Suktam']),
      mantras_hi: JSON.stringify(['श्री सूक्तम्']),
      notes_en: 'Sri Suktam is the Vedic hymn of Goddess Lakshmi, directly addressing wealth, prosperity, and abundance. Friday mornings are especially potent for this recitation.',
      notes_hi: 'श्री सूक्तम् देवी लक्ष्मी का वैदिक स्तुतिगान है जो धन, समृद्धि और वैभव को सीधे संबोधित करता है। शुक्रवार की सुबह इस पाठ के लिए विशेष रूप से प्रभावशाली है।',
    },
    {
      problem_en: 'Intelligence & Learning',
      problem_hi: 'बुद्धि एवं विद्या',
      planet: 'Jupiter',
      devata_en: 'Brihaspati',
      devata_hi: 'बृहस्पति',
      mantras_en: JSON.stringify(['Medha Suktam']),
      mantras_hi: JSON.stringify(['मेधा सूक्तम्']),
      notes_en: 'Medha Suktam is the Vedic hymn specifically for intelligence, sharp memory, and learning ability. Students, researchers, and teachers benefit greatly from this.',
      notes_hi: 'मेधा सूक्तम् विशेष रूप से बुद्धि, तीव्र स्मरणशक्ति और विद्याग्रहण क्षमता के लिए वैदिक स्तोत्र है। विद्यार्थी, शोधकर्ता और शिक्षक इससे विशेष लाभ पाते हैं।',
    },
  ]);

  // ── Section 6: Daily Puja Sequence ─────────────────────────────────────────
  await knex('remedy_puja_steps').insert([
    {
      step_key: '0',
      sort_order: 0,
      action_en: 'Ganesh Invocation (Before Everything)',
      action_hi: 'गणेश आह्वान (सबसे पहले)',
      description_en: 'Perform Ganapati Prarthna OR recite Ganapati Gayatri Mantra 9 times. Ganesha must be invoked first as the remover of obstacles and the lord of all beginnings. This step is MANDATORY before any puja.',
      description_hi: 'गणपति प्रार्थना करें अथवा गणपति गायत्री मंत्र ९ बार जपें। गणेश को विघ्नहर्ता एवं आदि देव के रूप में सर्वप्रथम आह्वान करना अनिवार्य है। यह चरण प्रत्येक पूजा से पूर्व अनिवार्य है।',
      is_conditional: false,
    },
    {
      step_key: '1',
      sort_order: 1,
      action_en: 'Ishta Devata Mantra',
      action_hi: 'इष्ट देवता मंत्र',
      description_en: 'Recite the mantra or suktam of the Ishta Devata corresponding to the afflicted or relevant planet in your chart. This is the core remedial step.',
      description_hi: 'अपनी कुंडली में पीड़ित या संबंधित ग्रह के इष्ट देवता का मंत्र/सूक्तम् पाठ करें। यह मुख्य उपाय चरण है।',
      is_conditional: false,
    },
    {
      step_key: '2',
      sort_order: 2,
      action_en: 'Lagna Lord Devata Mantra',
      action_hi: 'लग्नेश देवता मंत्र',
      description_en: 'Recite the mantra of the Ishta Devata of the Lagna Lord (Ascendant lord). This strengthens the foundation of the entire birth chart and supports the individual\'s overall vitality.',
      description_hi: 'लग्नेश (लग्न के स्वामी ग्रह) के इष्ट देवता का मंत्र पाठ करें। यह सम्पूर्ण जन्मकुंडली की नींव को दृढ़ करता है और व्यक्ति की समग्र जीवनशक्ति को बल देता है।',
      is_conditional: false,
    },
    {
      step_key: '3',
      sort_order: 3,
      action_en: 'Atmakarak Graha Mantra',
      action_hi: 'आत्मकारक ग्रह मंत्र',
      description_en: 'Recite the mantra of the Ishta Devata of the Atmakarak planet — the planet at the highest degree in the chart, representing the soul\'s purpose and karmic direction.',
      description_hi: 'आत्मकारक ग्रह के इष्ट देवता का मंत्र पाठ करें। आत्मकारक वह ग्रह है जो कुंडली में सर्वाधिक अंश पर हो और आत्मा के उद्देश्य एवं कार्मिक दिशा का प्रतिनिधित्व करता है।',
      is_conditional: false,
    },
    {
      step_key: 'tc',
      sort_order: 4,
      action_en: 'Shakti Pujan (Conditional)',
      action_hi: 'शक्ति पूजन (शर्त आधारित)',
      description_en: 'Perform Shakti Pujan (Durga Suktam / Durga Kavach / Medha Suktam / Devi Suktam) ONLY IF the Divine Feminine (Shakti) has NOT already appeared as the Ishta Devata in Steps 1, 2, or 3. This ensures Shakti is always honoured without unnecessary repetition.',
      description_hi: 'शक्ति पूजन (दुर्गा सूक्तम् / दुर्गा कवच / मेधा सूक्तम् / देवी सूक्तम्) तभी करें जब दिव्य शक्ति (माँ) चरण १, २ या ३ में इष्ट देवता के रूप में न आई हो। इससे अनावश्यक पुनरावृत्ति से बचा जाता है और शक्ति का सम्मान भी सुनिश्चित होता है।',
      is_conditional: true,
    },
  ]);
};
