'use strict';
// Source: AstroAnsh Class 11 and 12 Premium Notes — Yogas and Doshas.pdf

exports.seed = async function (knex) {
  await knex('yogas_library').del();
  await knex('doshas_library').del();

  // ──────────────────────────────────────────────────────────────────
  // YOGAS (12 yogas from PDF)
  // ──────────────────────────────────────────────────────────────────
  await knex('yogas_library').insert([
    {
      name: 'Gajakesari Yoga',
      name_hi: 'गजकेसरी योग',
      category: 'power',
      definition_en: 'Formed by the mutual Kendra relationship between Jupiter and Moon, blessing the native with the qualities of an elephant (stability, wealth) and a lion (leadership, dominance).',
      definition_hi: 'बृहस्पति और चंद्रमा के परस्पर केंद्र संबंध से बनता है, जो जातक को हाथी (स्थिरता, धन) और सिंह (नेतृत्व, प्रभुत्व) के गुण प्रदान करता है।',
      formation_en: 'Jupiter and Moon must be in Kendra positions (1st, 4th, 7th, or 10th house) from each other. Mutual Kendra placement or Kendra aspect is sufficient. Stronger when both are in own, exalted, or friendly signs.',
      formation_hi: 'बृहस्पति और चंद्रमा एक-दूसरे से केंद्र भाव (1, 4, 7 या 10वें भाव) में स्थित होने चाहिए। परस्पर केंद्र स्थिति या केंद्र दृष्टि पर्याप्त है।',
      symptoms_en: 'Strong moral character; naturally commanding presence; strong intuitive intelligence combined with Jupiter\'s wisdom.',
      symptoms_hi: 'दृढ़ नैतिक चरित्र; स्वाभाविक रूप से प्रभावशाली व्यक्तित्व; बृहस्पति की बुद्धिमत्ता के साथ तीव्र सहजज्ञान।',
      effects_en: 'Bestows intelligence, wisdom, name, fame, and wealth. Native becomes influential, respected, and admired. Strong financial success, political power, and social influence.',
      effects_hi: 'बुद्धि, विवेक, नाम, यश और धन प्रदान करता है। जातक समाज में प्रभावशाली, सम्मानित और प्रतिष्ठित बनता है।',
      cancellation_en: 'Weakened when Moon is debilitated in Scorpio, Jupiter is debilitated in Capricorn, both afflicted by Rahu-Ketu axis, or combination in Dusthana houses (6th, 8th, 12th).',
      cancellation_hi: 'योग कमजोर होता है जब चंद्रमा वृश्चिक में नीच हो, बृहस्पति मकर में नीच हो, या दोनों राहु-केतु से पीड़ित हों।',
      source: 'BPHS',
    },
    {
      name: 'Budh-Aditya Yoga',
      name_hi: 'बुध-आदित्य योग',
      category: 'intellect',
      definition_en: 'Formed by the conjunction of Sun (Surya/Aditya) and Mercury (Budha) in the same house, merging solar authority with Mercury\'s intelligence and communication ability.',
      definition_hi: 'सूर्य और बुध की एक ही भाव में युति से बनता है। सौर ऊर्जा एवं अधिकार को बुध की बुद्धि, संवाद-कौशल के साथ जोड़ता है।',
      formation_en: 'Sun and Mercury must be conjunct in the same house. Mercury must NOT be within 3° of the Sun (combust). Most potent in Gemini, Virgo, or Leo.',
      formation_hi: 'सूर्य और बुध एक ही भाव में युत होने चाहिए। बुध सूर्य से 3° के भीतर नहीं होना चाहिए।',
      symptoms_en: 'Sharp analytical thinking; excellent command over language; prominent in communication-based professions.',
      symptoms_hi: 'तीव्र विश्लेषणात्मक सोच; भाषा पर उत्कृष्ट अधिकार; संचार-आधारित व्यवसायों में प्रमुखता।',
      effects_en: 'Enhances intellect, sharp memory, and calculative mind. Excellent results in education, writing, teaching, media, politics, and business.',
      effects_hi: 'बुद्धि, तीव्र स्मरण शक्ति और गणनात्मक मन को बढ़ाता है। शिक्षा, लेखन, मीडिया, राजनीति में उत्कृष्ट परिणाम।',
      cancellation_en: 'Weakened when Mercury is combust (within 3°), Sun is debilitated in Libra, or Mercury is simultaneously retrograde and combust.',
      cancellation_hi: 'जब बुध अस्त (3° के भीतर) हो, सूर्य तुला में नीच हो, या बुध एक साथ वक्री और अस्त हो तब योग कमजोर होता है।',
      source: 'BPHS',
    },
    {
      name: 'Neech Bhanga Raj Yoga',
      name_hi: 'नीच भंग राज योग',
      category: 'power',
      definition_en: 'Occurs when a debilitated planet\'s weakness is cancelled by specific planetary conditions, transforming debilitation into a powerful Raj Yoga. Grants great success after overcoming struggles.',
      definition_hi: 'नीच ग्रह की कमजोरी विशेष ग्रह-स्थितियों द्वारा रद्द हो जाने पर उत्पन्न होता है, जिससे नीचता एक शक्तिशाली राज योग में परिवर्तित हो जाती है।',
      formation_en: 'Any ONE: (1) Lord of debilitation sign in Kendra from Lagna/Moon; (2) Debilitated planet receives aspect from its exalted counterpart; (3) Planet exalted in debilitation sign is in Kendra; (4) Debilitated planet conjunct/aspected by its dispositor.',
      formation_hi: 'कोई एक: (1) नीच राशि का स्वामी केंद्र में; (2) नीच ग्रह को उच्च ग्रह की दृष्टि; (3) नीच राशि का उच्च ग्रह केंद्र में; (4) नीच ग्रह अपने स्वामी के साथ युत।',
      symptoms_en: 'Native faces significant hardships in early/mid-life. After struggle period, dramatic reversal of fortune occurs.',
      symptoms_hi: 'जातक प्रारंभिक या मध्य जीवन में महत्वपूर्ण कठिनाइयों का सामना करता है। संघर्ष के बाद भाग्य में नाटकीय परिवर्तन आता है।',
      effects_en: 'Grants great success, power, and social recognition after initial struggles. Bestows respect, wealth, political success, and victory over enemies.',
      effects_hi: 'प्रारंभिक संघर्ष के बाद महान सफलता, शक्ति और सामाजिक मान्यता प्रदान करता है। सम्मान, धन और शत्रुओं पर विजय।',
      cancellation_en: 'Cancelled if no cancellation condition is met, or if debilitated planet is also combust, retrograde, or in 6th/8th/12th without supporting influence.',
      cancellation_hi: 'रद्द होता है यदि भंग की शर्त पूरी न हो, या नीच ग्रह अस्त, वक्री हो, या बिना सहायक प्रभाव के 6/8/12 में हो।',
      source: 'BPHS',
    },
    {
      name: 'Saraswati Yoga',
      name_hi: 'सरस्वती योग',
      category: 'wisdom',
      definition_en: 'Formed by the combined influence of Jupiter, Venus, and Mercury — the three planets of wisdom, creativity, and intelligence. Bestows blessings of Goddess Saraswati.',
      definition_hi: 'बृहस्पति, शुक्र और बुध — ज्ञान, रचनात्मकता और बुद्धि के तीन ग्रहों के संयुक्त प्रभाव से बनता है। देवी सरस्वती का आशीर्वाद प्रदान करता है।',
      formation_en: 'Jupiter, Venus, and Mercury must conjoin or mutually aspect each other in a Kendra (1,4,7,10), Trikona (1,5,9), or 2nd house. All three should be free from severe malefic affliction.',
      formation_hi: 'बृहस्पति, शुक्र और बुध केंद्र (1,4,7,10), त्रिकोण (1,5,9) या द्वितीय भाव में परस्पर युत या दृष्टि में होने चाहिए।',
      symptoms_en: 'Natural artistic ability visible from early age; exceptional eloquence with wisdom, charm, and persuasion.',
      symptoms_hi: 'प्रारंभिक आयु से ही प्राकृतिक कलात्मक क्षमता; असाधारण वाकपटुता।',
      effects_en: 'Grants extraordinary intellect, artistic skill, literary prowess, and oratory ability. Native may become a scholar, writer, musician, poet, or distinguished teacher.',
      effects_hi: 'असाधारण बुद्धि, कलात्मक कौशल, साहित्यिक प्रतिभा प्रदान करता है। जातक विद्वान, लेखक, संगीतज्ञ या शिक्षक बन सकते हैं।',
      cancellation_en: 'Weakened when any of the three planets is debilitated, combust, or placed in 6th/8th/12th under malefic influence.',
      cancellation_hi: 'जब इनमें से कोई ग्रह नीच, अस्त हो, या पाप प्रभाव में 6, 8 या 12वें भाव में हो।',
      source: 'BPHS',
    },
    {
      name: 'Kalaneedhi Yoga',
      name_hi: 'कलानीधि योग',
      category: 'wealth',
      definition_en: 'Literally "treasure of the arts" — formed when Venus or Jupiter are in the 2nd or 5th house from Lagna and receive Mercury\'s aspect. Associated with refined taste, prosperity, and artistic excellence.',
      definition_hi: '"कलाओं का खजाना" — शुक्र या बृहस्पति लग्न से द्वितीय या पंचम भाव में हों और बुध की दृष्टि प्राप्त करें।',
      formation_en: 'Venus or Jupiter in the 2nd or 5th house from Lagna. Mercury must cast its aspect on Venus or Jupiter in those houses.',
      formation_hi: 'शुक्र या बृहस्पति लग्न से द्वितीय या पंचम भाव में। बुध उन भावों में शुक्र या बृहस्पति पर दृष्टि डाले।',
      symptoms_en: 'Natural attraction to beauty, music, fine arts, and luxury. Pleasant and attractive personality, refined manners.',
      symptoms_hi: 'सौंदर्य, संगीत, ललित कला और विलासिता के प्रति प्राकृतिक आकर्षण। सुखद और आकर्षक व्यक्तित्व।',
      effects_en: 'Brings wealth, prosperity, good looks, luxury, and artistic talent. Native enjoys harmonious family life and earns social fame.',
      effects_hi: 'धन, समृद्धि, सुंदर रूप, विलासिता और कलात्मक प्रतिभा लाता है। सौहार्दपूर्ण पारिवारिक जीवन।',
      cancellation_en: 'Weakened when Venus or Jupiter are debilitated or afflicted, or when Mercury is combust or weak.',
      cancellation_hi: 'जब शुक्र या बृहस्पति नीच या पीड़ित हों, या बुध अस्त या निर्बल हो।',
      source: 'BPHS',
    },
    {
      name: 'Chandra-Mangal Laxmi Yoga',
      name_hi: 'चंद्र-मंगल लक्ष्मी योग',
      category: 'wealth',
      definition_en: 'Formed by the conjunction or mutual aspect of Moon and Mars. Moon represents mind, mother, and wealth; Mars represents action, energy, and real estate. Creates a dynamic wealth-generating combination.',
      definition_hi: 'चंद्रमा और मंगल की युति या परस्पर दृष्टि से बनता है। चंद्रमा मन, माता और धन का प्रतिनिधित्व करता है; मंगल क्रिया, ऊर्जा और अचल संपत्ति का।',
      formation_en: 'Moon and Mars in conjunction (same house) or mutual aspect from each other. Strongest when Moon is in waxing phase (Shukla Paksha) and both planets are free from malefic affliction.',
      formation_hi: 'चंद्रमा और मंगल युति (एक ही भाव) में या परस्पर दृष्टि में। शुक्ल पक्ष में सबसे बलवान।',
      symptoms_en: 'Bold, energetic, decisive personality — acts quickly without hesitation. Strong attraction to real estate and tangible assets.',
      symptoms_hi: 'साहसी, ऊर्जावान और निर्णायक व्यक्तित्व। अचल संपत्ति और भूमि के प्रति तीव्र आकर्षण।',
      effects_en: 'Brings immense financial gains, property, and material assets. Native is energetic, courageous, and a quick decision-maker — qualities of Goddess Laxmi\'s grace.',
      effects_hi: 'अपार वित्तीय लाभ, संपत्ति और भौतिक संपदा लाता है। जातक ऊर्जावान, साहसी और तीव्र निर्णायक होता है।',
      cancellation_en: 'Weakened when Moon is debilitated in Scorpio (especially Krishna Paksha), Mars debilitated in Cancer, or conjunction/aspect in Dusthana houses.',
      cancellation_hi: 'जब चंद्रमा वृश्चिक में नीच हो, मंगल कर्क में नीच हो, या युति/दृष्टि दुष्टान भावों में हो।',
      source: 'BPHS',
    },
    {
      name: 'Dhan Yoga',
      name_hi: 'धन योग',
      category: 'wealth',
      definition_en: 'Wealth-producing yogas formed by relationships of lords of wealth-signifying houses (2nd, 5th, 9th, 11th). Governs financial prosperity and material abundance. Includes sub-types: Laxmi Yoga, Adhi Yoga, Maha Dhan Yoga.',
      definition_hi: 'धन-संकेतक भावों (2, 5, 9, 11) के स्वामियों के संबंधों से बनने वाले धन-उत्पादक ग्रह-संयोजनों का समूह।',
      formation_en: 'A) Dhan Yoga: mutual relationship (conjunction/aspect/exchange) of lords of 2nd, 5th, 9th, 11th. B) Laxmi Yoga: 9th lord exalted in Kendra/Trikona with strong Lagna lord. C) Adhi Yoga: Jupiter/Venus/Mercury in 6th/7th/8th from Moon. D) Maha Dhan Yoga: 2nd and 11th lords strongly connected with benefics.',
      formation_hi: 'A) धन योग: 2,5,9,11 के स्वामी परस्पर। B) लक्ष्मी योग: नवमेश उच्च केंद्र/त्रिकोण में। C) अधि योग: शुभ ग्रह चंद्र से 6/7/8 में। D) महाधन योग: 2 और 11 के स्वामी शुभ ग्रहों से बलवान संबंध।',
      symptoms_en: 'Multiple income sources; financial intelligence; consistent wealth accumulation; material prosperity visible in lifestyle.',
      symptoms_hi: 'आय के कई स्रोत; वित्तीय बुद्धिमत्ता; निरंतर धन संचय; जीवनशैली में भौतिक समृद्धि।',
      effects_en: 'Brings immense wealth, property, prosperity, and social fame. Extraordinary accumulation in Maha Dhan — native lives a king-like lifestyle.',
      effects_hi: 'अपार धन, संपत्ति, समृद्धि और सामाजिक यश लाता है। महाधन में असाधारण संचय।',
      cancellation_en: 'Weakened when malefics afflict the 2nd, 5th, 9th, or 11th houses, or when Lagna lord or 9th lord are weak or debilitated.',
      cancellation_hi: 'जब पाप ग्रह 2, 5, 9 या 11वें भाव को पीड़ित करें, या लग्नेश या नवमेश निर्बल या नीच हों।',
      source: 'BPHS',
    },
    {
      name: 'Raj Yoga',
      name_hi: 'राज योग',
      category: 'power',
      definition_en: 'The king of all auspicious Yogas — grants power, authority, success, and high social standing. Formed by mutual association of Kendra lords (lords of power) and Trikona lords (lords of fortune).',
      definition_hi: 'राज योग ज्योतिष में सभी शुभ योगों का राजा है — शक्ति, अधिकार, सफलता और उच्च सामाजिक स्थान प्रदान करता है।',
      formation_en: 'Kendra lords (1st, 4th, 7th, 10th house lords) must conjoin or aspect the Trikona lords (1st, 5th, 9th house lords). Stronger when planets are in own/exalted/friendly signs in Kendra or Trikona.',
      formation_hi: 'केंद्र स्वामी (1,4,7,10) त्रिकोण स्वामियों (1,5,9) के साथ युत या दृष्टि में। अपनी राशि, उच्च या मित्र राशि में अधिक बलवान।',
      symptoms_en: 'Natural leadership ability; progressive career with recognition at each step.',
      symptoms_hi: 'प्राकृतिक नेतृत्व क्षमता; हर कदम पर मान्यता के साथ प्रगतिशील करियर।',
      effects_en: 'Bestows power, authority, success, leadership, and prosperity. Native gains fame, holds high positions, and earns widespread recognition.',
      effects_hi: 'शक्ति, अधिकार, सफलता, नेतृत्व और समृद्धि प्रदान करता है। जातक यश प्राप्त करता है और उच्च पदों पर रहता है।',
      cancellation_en: 'Cancelled when it forms in Dusthana houses, or when involved planets are debilitated, combust, or retrograde without supporting strength.',
      cancellation_hi: 'जब दुष्टान भावों में बने, या संबंधित ग्रह निर्बल हों।',
      source: 'BPHS',
    },
    {
      name: 'Vipreet Raj Yoga',
      name_hi: 'विपरीत राज योग',
      category: 'power',
      definition_en: 'Literally "opposite Raj Yoga" — success comes through adversity, loss, or opposition. Formed when Dusthana lords occupy their own Dusthana houses, purging negativity through itself. Three sub-types: Harsha, Sarala, Vimala.',
      definition_hi: '"विपरीत राज योग" — सफलता प्रतिकूलता के माध्यम से आती है। दुष्टान स्वामियों के दुष्टान भावों में स्थित होने से बनता है।',
      formation_en: 'Harsha Yoga: 6th lord in 8th or 12th. Sarala Yoga: 8th lord in 6th or 12th. Vimala Yoga: 12th lord in 6th or 8th.',
      formation_hi: 'हर्ष योग: षष्ठेश 8 या 12 में। सरल योग: अष्टमेश 6 या 12 में। विमल योग: द्वादशेश 6 या 8 में।',
      symptoms_en: 'Native endures periods of hardship and opposition before rising. Strong capacity to recover from setbacks.',
      symptoms_hi: 'जातक उठने से पहले कठिनाई और विरोध की अवधि सहता है। असफलताओं से उबरने की मजबूत क्षमता।',
      effects_en: 'Grants success, wealth, and power after facing struggles, obstacles, or downfall. Native gains strength to overcome enemies and rise above adverse conditions.',
      effects_hi: 'संघर्ष के बाद सफलता, धन और शक्ति। शत्रुओं पर विजय और प्रतिकूल परिस्थितियों से ऊपर उठना।',
      cancellation_en: 'Weakened when Dusthana lords are inherently weak or debilitated, or when Lagna and its lord are also weak.',
      cancellation_hi: 'जब दुष्टान स्वामी स्वाभाविक रूप से कमजोर या नीच हों, या लग्न और लग्नेश निर्बल हों।',
      source: 'BPHS',
    },
    {
      name: 'Parivartan Yoga',
      name_hi: 'परिवर्तन योग',
      category: 'general',
      definition_en: 'Sign Exchange Yoga — formed when two planets occupy each other\'s signs, creating a powerful mutual reception. Both planets act as if conjunct. Three types: Raj (Kendra-Trikona), Dhan (wealth houses), Dusthana (harmful exchange).',
      definition_hi: 'राशि विनिमय योग — दो ग्रह एक-दूसरे की राशियों में हों। तीन प्रकार: राज (केंद्र-त्रिकोण), धन (धन भाव), दुष्टान।',
      formation_en: 'Two planets must occupy each other\'s own signs (e.g., Mars in Libra while Venus is in Aries). Raj Parivartan: Kendra-Trikona lords exchange. Dhan Parivartan: wealth house lords exchange. Dusthana Parivartan: Dusthana lords exchange (harmful).',
      formation_hi: 'दो ग्रह एक-दूसरे की स्वामित्व वाली राशियों में हों। राज: केंद्र-त्रिकोण विनिमय। धन: धन भाव विनिमय। दुष्टान: हानिकारक।',
      symptoms_en: 'Significantly strengthens both involved houses. Auspicious exchanges bring fortune, wealth, authority; Dusthana exchanges bring difficulties.',
      symptoms_hi: 'विनिमय में शामिल दोनों भावों को महत्वपूर्ण रूप से मजबूत करता है।',
      effects_en: 'Raj Parivartan: bestows authority, fortune, and success. Dhan Parivartan: generates financial prosperity. Dusthana: generally harmful, brings misery and losses.',
      effects_hi: 'राज परिवर्तन: अधिकार, भाग्य और सफलता। धन परिवर्तन: वित्तीय समृद्धि। दुष्टान: सामान्यतः हानिकारक।',
      cancellation_en: 'Dusthana Parivartan gives harmful results unless both Dusthana lords are strong or the Vipreet Raj conditions apply.',
      cancellation_hi: 'दुष्टान परिवर्तन हानिकारक परिणाम देता है जब तक विपरीत राज की शर्तें लागू न हों।',
      source: 'BPHS',
    },
    {
      name: 'Guru-Aditya Yoga',
      name_hi: 'गुरु-आदित्य योग',
      category: 'wisdom',
      definition_en: 'Formed by the conjunction of Jupiter and Sun in the same house. Combines the Sun\'s radiance, authority, and soul-power with Jupiter\'s wisdom, spirituality, and ethical knowledge.',
      definition_hi: 'बृहस्पति और सूर्य की एक ही भाव में युति से बनता है। सूर्य की दीप्ति, अधिकार और आत्म-शक्ति को बृहस्पति की बुद्धिमत्ता, आध्यात्मिकता के साथ जोड़ता है।',
      formation_en: 'Jupiter and Sun must be conjunct in the same house. Most powerful when placed in Leo (Sun\'s sign), Sagittarius/Pisces (Jupiter\'s signs), or Cancer (Jupiter\'s exaltation).',
      formation_hi: 'बृहस्पति और सूर्य किसी भी राशि में युत (एक ही भाव) में होने चाहिए। सिंह, धनु, मीन या कर्क में सबसे शक्तिशाली।',
      symptoms_en: 'Deeply principled nature — truthful, ethical, spiritually inclined. Respect and authority in religious, academic, or governmental fields.',
      symptoms_hi: 'गहरे सिद्धांतवादी स्वभाव — सत्यनिष्ठ, नैतिक और आध्यात्मिक रूप से झुका। धार्मिक, शैक्षणिक या सरकारी क्षेत्रों में सम्मान।',
      effects_en: 'Native becomes learned, respected, spiritually wise, and truthful — a natural advisor. Brings authority in religious institutions, academia, or government service.',
      effects_hi: 'जातक विद्वान, सम्मानित, आध्यात्मिक रूप से बुद्धिमान बनता है। धार्मिक संस्थाओं, शिक्षा जगत या सरकारी सेवा में अधिकार।',
      cancellation_en: 'Weakened when Sun is debilitated in Libra, Jupiter is debilitated in Capricorn, or both afflicted by Rahu-Ketu axis.',
      cancellation_hi: 'जब सूर्य तुला में नीच हो, बृहस्पति मकर में नीच हो, या दोनों राहु-केतु से पीड़ित हों।',
      source: 'BPHS',
    },
    {
      name: 'Shatru Hanta Yoga',
      name_hi: 'शत्रु हंत योग',
      category: 'victory',
      definition_en: 'Literally "destroyer of enemies" — grants the capacity to identify, confront, and overcome all opposition: personal enemies, professional rivals, legal adversaries, and internal obstacles. Bestows exceptional courage, strategic intelligence, and tenacity.',
      definition_hi: '"शत्रुओं का संहारक" — जातक को विरोध के सभी रूपों पर विजय प्राप्त करने की क्षमता प्रदान करता है।',
      formation_en: '6th lord in 12th house from its position; OR Mars in 6th in own/exalted sign; OR 6th lord conjunct/aspected by Mars; OR Sun in 6th house in Leo; OR strong Lagna lord conjunct/aspecting 6th house.',
      formation_hi: 'षष्ठेश 12 में; मंगल 6 में अपनी/उच्च राशि में; षष्ठेश मंगल से युत/दृष्ट; सूर्य 6 में सिंह में; बलवान लग्नेश षष्ठ के साथ युत/दृष्टि।',
      symptoms_en: 'Naturally competitive — thrives under pressure. Enemies eventually submit, withdraw, or are decisively defeated. Strong instinct for identifying threats and tactical timing.',
      symptoms_hi: 'स्वाभाविक रूप से प्रतिस्पर्धी। शत्रु अंततः समर्पण करते या पराजित होते हैं। खतरों को पहचानने की मजबूत प्रवृत्ति।',
      effects_en: 'Victory over enemies; freedom from chronic illness, debts, and litigation; success in competitive fields (politics, law, military, sports). Strong recovery from setbacks.',
      effects_hi: 'शत्रुओं पर विजय; दीर्घकालिक बीमारी, ऋण से मुक्ति; प्रतिस्पर्धी क्षेत्रों में सफलता।',
      cancellation_en: 'Weakened when 6th lord is debilitated/combust, or Lagna lord is simultaneously weak, or strong malefics heavily afflict Mars and 6th house.',
      cancellation_hi: 'जब षष्ठेश नीच, अस्त हो, या लग्नेश कमजोर हो, या पाप ग्रह मंगल और 6 भाव को पीड़ित करें।',
      source: 'BPHS',
    },
  ]);

  // ──────────────────────────────────────────────────────────────────
  // DOSHAS (13 doshas from PDF)
  // ──────────────────────────────────────────────────────────────────
  await knex('doshas_library').insert([
    {
      name: 'Pitru Dosha',
      name_hi: 'पितृ दोष',
      category: 'karmic',
      definition_en: 'A karmic imbalance caused by unsatisfied or troubled ancestral souls. Not merely a "curse" but a reflection of unresolved karmic debts from past lives. Manifests through affliction of the 9th house, its lord, and the Sun.',
      definition_hi: 'असंतुष्ट या परेशान पितृ आत्माओं के कारण होने वाला कार्मिक असंतुलन। पूर्वजन्मों के अनसुलझे कार्मिक ऋणों का प्रतिबिंब।',
      formation_en: '9th house or its lord afflicted by malefics (Saturn, Rahu, Ketu, Mars). Sun (Karaka for father/ancestors) weak, debilitated, or heavily afflicted. Rahu or Ketu placed in the 9th house creates strong Pitru Dosha.',
      formation_hi: '9वां भाव या उसका स्वामी पाप ग्रहों से पीड़ित। सूर्य कमजोर, नीच या पीड़ित। 9वें भाव में राहु या केतु।',
      symptoms_en: 'Persistent unexplained obstacles despite effort. Difficulties in relationship with father or paternal family. Repeated delays in progeny, marriage, or key life milestones.',
      symptoms_hi: 'प्रयास के बावजूद निरंतर और अस्पष्टीकृत बाधाएं। पिता या पितृ परिवार के साथ संबंधों में कठिनाइयां।',
      effects_en: 'Conflicts with father or father figures; possibility of father\'s early death. Family disharmony, delayed progeny, recurring generational problems. Financial instability and career obstacles.',
      effects_hi: 'पिता के साथ मतभेद; पारिवारिक अशांति; संतान में विलंब; वित्तीय अस्थिरता।',
      technical_note_en: 'Pitru Dosha is primarily a karmic imbalance from past-life actions — not a deliberate curse. Its effects vary based on Sun\'s strength, 9th lord placement, and the nature of afflicting planets.',
      technical_note_hi: 'पितृ दोष मुख्यतः पूर्वजन्म के कर्म से उत्पन्न कार्मिक असंतुलन है। इसके प्रभाव सूर्य, 9वें भाव के स्वामी की शक्ति के आधार पर भिन्न होते हैं।',
      source: 'BPHS',
    },
    {
      name: 'Surya-Shani Vish Dosha',
      name_hi: 'सूर्य-शनि विष दोष',
      category: 'vish',
      definition_en: 'Formed by the conjunction of Sun (ego, authority, father) and Saturn (discipline, karma, limitation) in the same house. Sun and Saturn are natural enemies — their conjunction creates inner and outer conflict.',
      definition_hi: 'सूर्य (अहंकार, अधिकार, पिता) और शनि (अनुशासन, कर्म, सीमा) की युति से बनता है। सूर्य और शनि स्वाभाविक शत्रु हैं — उनकी युति आंतरिक और बाह्य संघर्ष उत्पन्न करती है।',
      formation_en: 'Sun and Saturn must be conjunct in the same house. Stronger when in 1st, 9th, or 10th house.',
      formation_hi: 'सूर्य और शनि एक ही भाव में युत। 1, 9 या 10वें भाव में अधिक प्रबल।',
      symptoms_en: 'Strained or distant relationship with father and authority figures. Constant internal battle between ambition (Sun) and caution (Saturn).',
      symptoms_hi: 'पिता और अधिकारियों के साथ तनावपूर्ण सबंध। महत्वाकांक्षा और सावधानी के बीच निरंतर संघर्ष।',
      effects_en: 'Strained relationship with father, bosses, and authority figures; frequent clashes. Career delays, obstacles in gaining recognition. Health vulnerabilities related to eyes, bones, joints, and heart.',
      effects_hi: 'पिता, बॉस और अधिकारियों से तनाव; करियर में विलंब; आंखों, हड्डियों, जोड़ों और हृदय से संबंधित स्वास्थ्य समस्याएं।',
      technical_note_en: 'Fundamentally a life-lesson in balancing ego with discipline. The friction between solar pride and Saturnine structure, when understood correctly, produces extraordinary perseverance and professional mastery.',
      technical_note_hi: 'यह दोष मूलतः अहंकार को अनुशासन के साथ संतुलित करने का जीवन-पाठ है।',
      source: 'BPHS',
    },
    {
      name: 'Mangal-Shani Vish Dosha',
      name_hi: 'मंगल-शनि विष दोष',
      category: 'vish',
      definition_en: 'Formed by the conjunction of Mars (fire, aggression, energy) and Saturn (restriction, delays, discipline). Mars wants to act; Saturn delays and restricts. This conflict generates explosive anger and erratic action.',
      definition_hi: 'मंगल (अग्नि, आक्रामकता) और शनि (प्रतिबंध, विलंब) की युति से बनता है। मंगल कार्य करना चाहता है; शनि विलंब करता है।',
      formation_en: 'Mars and Saturn conjunct in the same house. More severe in fire signs (Aries, Leo, Sagittarius) or action houses (1st, 3rd, 10th).',
      formation_hi: 'मंगल और शनि एक ही भाव में युत। अग्नि राशियों (मेष, सिंह, धनु) या 1, 3, 10 में अधिक गंभीर।',
      symptoms_en: 'Explosive, uncontrollable anger that surfaces unexpectedly. Proneness to accidents, injuries, and sudden physical trauma.',
      symptoms_hi: 'विस्फोटक, अनियंत्रित क्रोध। दुर्घटनाओं, चोटों की प्रवृत्ति।',
      effects_en: 'Extreme frustration, anger management issues, and impulsive decisions with harmful consequences. High risk of accidents, surgeries, injuries. Property disputes, marital conflicts, legal troubles.',
      effects_hi: 'अत्यधिक निराशा, क्रोध प्रबंधन समस्याएं। दुर्घटनाओं का उच्च जोखिम। संपत्ति विवाद, वैवाहिक संघर्ष।',
      technical_note_en: 'When both planets are strong in dignified signs, this combination can also produce great engineering ability, physical stamina, and disciplined force.',
      technical_note_hi: 'जब दोनों ग्रह उच्च राशियों में हों, यह महान इंजीनियरिंग क्षमता और अनुशासित शक्ति भी दे सकता है।',
      source: 'BPHS',
    },
    {
      name: 'Moon-Shani Vish Dosha',
      name_hi: 'चंद्र-शनि विष दोष',
      category: 'vish',
      definition_en: 'Formed by the conjunction of Moon (emotions, mind, mother) and Saturn (restriction, karma, sorrow). The Moon represents the flowing, sensitive mind; Saturn represents cold constriction. Creates emotional heaviness and restriction.',
      definition_hi: 'चंद्रमा (भावनाएं, मन, माता) और शनि (प्रतिबंध, कर्म, दुख) की युति से बनता है। भावनात्मक भार और प्रतिबंध उत्पन्न करता है।',
      formation_en: 'Moon and Saturn conjunct in the same house. Intensifies when Moon is in Krishna Paksha (waning), debilitated in Scorpio, or Saturn in enemy sign.',
      formation_hi: 'चंद्रमा और शनि एक ही भाव में युत। कृष्ण पक्ष में, या चंद्र वृश्चिक में नीच हो तो तीव्र।',
      symptoms_en: 'Persistent feelings of loneliness, emotional isolation, and unexplained melancholy. Troubled or distant relationship with mother.',
      symptoms_hi: 'एकाकीपन, भावनात्मक अलगाव और अस्पष्टीकृत उदासी। माता के साथ परेशान सबंध।',
      effects_en: 'Depression, chronic loneliness, emotional heaviness, and pessimistic outlook. Challenges with mother and maternal family. Delays in marriage and career; emotional decisions that harm long-term outcomes.',
      effects_hi: 'अवसाद, दीर्घकालिक एकाकीपन, भावनात्मक भार। माता और मातृ परिवार से चुनौतियां। विवाह और करियर में विलंब।',
      technical_note_en: 'Also called Shrapit Dasha Dosha. Its effects intensify during Saturn or Moon dashas. Spiritual practice and service can significantly mitigate this dosha.',
      technical_note_hi: 'इसे श्रापित दशा दोष भी कहा जाता है। शनि या चंद्र दशा में प्रभाव तीव्र होते हैं।',
      source: 'BPHS',
    },
    {
      name: 'Amavasya Dosha',
      name_hi: 'अमावस्या दोष',
      category: 'luminary',
      definition_en: 'Arises when a native is born on the New Moon day (Amavasya Tithi) — when Sun and Moon are conjunct in very close degrees. The Moon is entirely invisible, creating a merged, unilluminated combination that weakens both soul-force (Sun) and mind-force (Moon) simultaneously.',
      definition_hi: 'जब जातक का जन्म अमावस्या तिथि पर हो — सूर्य और चंद्रमा अत्यंत निकट युति में। दोनों ज्योतिर्मयों का विलीन, अप्रकाशित संयोजन।',
      formation_en: 'Native born on Amavasya Tithi when Sun and Moon are in same sign within ~12°. Strongest when exact same degree, neither planet receives benefic aspect. Intensifies in 6th/8th/12th house. Reduced when Jupiter aspects the conjunction.',
      formation_hi: 'अमावस्या तिथि पर जन्म — सूर्य और चंद्र एक राशि में ~12° के भीतर। जब बृहस्पति युति पर दृष्टि डाले तो कम होता है।',
      symptoms_en: 'Pervasive inner darkness or lack of direction. Emotional volatility between high confidence and deep self-doubt. Difficulty maintaining clarity under pressure.',
      symptoms_hi: 'आंतरिक अंधकार या दिशाहीनता। उच्च आत्मविश्वास और गहरे आत्म-संदेह के बीच अस्थिरता।',
      effects_en: 'Reduced physical vitality and life-force. Weak self-confidence and indecisiveness. Confusion in key decisions. Strained relationship with both parents simultaneously. May unconsciously seek external validation.',
      effects_hi: 'शारीरिक जीवन शक्ति में कमी। कमजोर आत्मविश्वास। दोनों माता-पिता के साथ तनाव। बाहरी अनुमोदन पर निर्भरता।',
      technical_note_en: 'Must be evaluated in context of the full chart. Strongly placed Jupiter aspecting the luminaries, or exalted Sun/Moon, can significantly reduce impact. The Dasha sequence governs when effects manifest.',
      technical_note_hi: 'संपूर्ण कुंडली के संदर्भ में मूल्यांकन आवश्यक। बृहस्पति की दृष्टि या उच्च सूर्य/चंद्र प्रभाव कम कर सकते हैं।',
      source: 'BPHS',
    },
    {
      name: 'Angarak Dosha',
      name_hi: 'अंगारक दोष',
      category: 'vish',
      definition_en: 'Literally "coal of fire" — formed by the conjunction of Mars and Rahu in the same house. Rahu amplifies and distorts Mars\' energy, transforming natural courage and directness into aggression, recklessness, and impulsive behavior.',
      definition_hi: '"आग का कोयला" — मंगल और राहु की युति से बनता है। राहु मंगल की ऊर्जा को बढ़ाकर आक्रामकता और लापरवाही में परिवर्तित करता है।',
      formation_en: 'Mars and Rahu conjunct in the same house. More severe in fire signs or in the Lagna, 4th, or 7th house.',
      formation_hi: 'मंगल और राहु एक ही भाव में युत। अग्नि राशियों में, या लग्न, 4 या 7वें भाव में अधिक गंभीर।',
      symptoms_en: 'Impulsive, aggressive behavior frequently causing self-harm or conflict. Tendency toward sudden, unexpected accidents and physical danger.',
      symptoms_hi: 'आवेगपूर्ण, आक्रामक व्यवहार। अचानक, अप्रत्याशित दुर्घटनाओं की प्रवृत्ति।',
      effects_en: 'Aggression, recklessness, and criminal tendencies when severely afflicted. Sudden accidents, impulsive financial losses, unexpected crises. Marital discord, relationship disputes.',
      effects_hi: 'आक्रामकता, लापरवाही। अचानक दुर्घटनाएं, वित्तीय हानि। वैवाहिक कलह।',
      technical_note_en: 'When placed in the 3rd, 6th, or 11th house, the aggressive energy can be channeled productively into competitive fields like sports, military, or surgery.',
      technical_note_hi: '3, 6, 11वें भाव में यह ऊर्जा खेल, सैन्य, या शल्य-चिकित्सा में उत्पादक रूप से काम कर सकती है।',
      source: 'BPHS',
    },
    {
      name: 'Shaapit Dosha',
      name_hi: 'शापित दोष',
      category: 'karmic',
      definition_en: 'Literally "cursed combination" — formed by the conjunction of Saturn and Rahu. One of the most severe karmic Doshas, representing deep accumulated negative karma from past lives that manifests as pervasive obstacles, fears, and blockages across all areas of life.',
      definition_hi: '"शापित संयोजन" — शनि और राहु की युति। पूर्वजन्मों के गहरे संचित नकारात्मक कर्म का प्रतिनिधित्व।',
      formation_en: 'Saturn and Rahu conjunct in the same house. Intensifies when in Kendra (1,4,7,10) or the 9th house.',
      formation_hi: 'शनि और राहु एक ही भाव में युत। केंद्र (1,4,7,10) या 9वें भाव में तीव्र।',
      symptoms_en: 'Inexplicable, pervasive fear and anxiety across multiple life areas. Pattern of delayed results — hard work not yielding proportionate outcomes.',
      symptoms_hi: 'अस्पष्टीकृत, व्यापक भय और चिंता। विलंबित परिणामों का पैटर्न — कठिन परिश्रम आनुपातिक परिणाम नहीं देता।',
      effects_en: 'Past-life karmic burden as persistent delays, obstacles, and unexplained suffering. Pervasive fear, lack of peace, persistent feelings of being blocked. Family disharmony and recurring relational problems.',
      effects_hi: 'पूर्वजन्म का कार्मिक बोझ निरंतर विलंब और बाधाओं के रूप में। व्यापक भय, शांति की कमी। पारिवारिक अशांति।',
      technical_note_en: 'This dosha often requires both external remedies (Saturn/Rahu mantras, charity) and internal transformation to fully mitigate.',
      technical_note_hi: 'इस दोष को कम करने के लिए बाह्य उपाय (शनि/राहु मंत्र, दान) और आंतरिक परिवर्तन दोनों आवश्यक हैं।',
      source: 'BPHS',
    },
    {
      name: 'Surya Grahan Dosha',
      name_hi: 'सूर्य ग्रहण दोष',
      category: 'grahan',
      definition_en: 'Formed when the Sun is eclipsed by Rahu or Ketu in the birth chart. The Sun represents the soul and life-force — its affliction by the Rahu-Ketu axis causes significant psychological and physical vulnerabilities.',
      definition_hi: 'जब सूर्य जन्म कुंडली में राहु या केतु द्वारा ग्रहण किए जाते हैं। सूर्य आत्मा और जीवन-शक्ति का प्रतिनिधित्व करता है।',
      formation_en: 'Sun conjunct with Rahu or Ketu in the same house (Solar Eclipse configuration in the birth chart).',
      formation_hi: 'सूर्य एक ही भाव में राहु या केतु के साथ युत (सूर्य ग्रहण विन्यास)।',
      symptoms_en: 'Sudden, unexpected reversals in life. Psychological stress and difficulty maintaining mental clarity.',
      symptoms_hi: 'जीवन में अचानक, अप्रत्याशित उलटफेर। मनोवैज्ञानिक तनाव और मानसिक स्पष्टता बनाए रखने में कठिनाई।',
      effects_en: 'Weak vitality, sudden ups and downs, and unpredictable life events. Father\'s health challenges and troubled paternal relationship.',
      effects_hi: 'कमजोर जीवन शक्ति, अचानक उतार-चढ़ाव। पिता की स्वास्थ्य चुनौतियां और परेशान माता-पिता संबंध।',
      technical_note_en: 'Rahu conjunction with Sun tends toward sudden rises followed by equally sudden falls. Ketu conjunction brings past-life karma, detachment, and spiritual tendencies but reduces worldly vitality.',
      technical_note_hi: 'राहु के साथ सूर्य की युति अचानक उत्थान और पतन देती है। केतु के साथ पूर्वजन्म का कर्म और आध्यात्मिक प्रवृत्ति।',
      source: 'BPHS',
    },
    {
      name: 'Chandra Grahan Dosha',
      name_hi: 'चंद्र ग्रहण दोष',
      category: 'grahan',
      definition_en: 'Formed when the Moon is eclipsed by Rahu or Ketu in the birth chart. The Moon represents the mind and emotions — its affliction causes significant psychological vulnerability, mental instability, and troubled maternal relationships.',
      definition_hi: 'जब चंद्रमा जन्म कुंडली में राहु या केतु द्वारा ग्रहण किए जाते हैं। चंद्रमा मन और भावनाओं का प्रतिनिधित्व करता है।',
      formation_en: 'Moon conjunct with Rahu or Ketu in the same house (Lunar Eclipse configuration).',
      formation_hi: 'चंद्रमा एक ही भाव में राहु या केतु के साथ युत (चंद्र ग्रहण विन्यास)।',
      symptoms_en: 'Psychological stress and anxiety; difficulty maintaining mental clarity; sudden reversals.',
      symptoms_hi: 'मनोवैज्ञानिक तनाव; मानसिक स्पष्टता बनाए रखने में कठिनाई; अचानक उलटफेर।',
      effects_en: 'Emotional instability, mental confusion, and psychological vulnerability. Mother\'s health challenges and troubled maternal relationship.',
      effects_hi: 'भावनात्मक अस्थिरता, मानसिक भ्रम। माता की स्वास्थ्य चुनौतियां और परेशान मातृ संबंध।',
      technical_note_en: 'Rahu with Moon often produces highly creative, imaginative minds that can also become prone to illusions or addictions. Ketu with Moon brings psychic ability and past-life emotional memory but emotional detachment.',
      technical_note_hi: 'राहु के साथ चंद्र रचनात्मक मन देता है लेकिन भ्रम की प्रवृत्ति। केतु के साथ मानसिक क्षमता और भावनात्मक स्मृति।',
      source: 'BPHS',
    },
    {
      name: 'Guru Chandaal Dosha',
      name_hi: 'गुरु चांडाल दोष',
      category: 'karmic',
      definition_en: 'Formed by the conjunction of Jupiter (wisdom, ethics, dharma) and Rahu or Ketu. Rahu contaminates Jupiter\'s pure wisdom, causing the native to pursue knowledge through unethical, misguided, or taboo-breaking paths.',
      definition_hi: 'बृहस्पति (ज्ञान, नैतिकता) और राहु या केतु की युति से बनता है। राहु बृहस्पति के शुद्ध ज्ञान को दूषित करता है।',
      formation_en: 'Jupiter conjunct with Rahu or Ketu in the same house. More severe when Jupiter is in enemy sign, or in the 1st, 5th, 9th, or 12th house.',
      formation_hi: 'बृहस्पति राहु या केतु के साथ एक ही भाव में युत। 1, 5, 9 या 12वें भाव में अधिक गंभीर।',
      symptoms_en: 'Drawn to unorthodox or ethically questionable knowledge. Tendency to disrespect teachers, gurus, and traditional wisdom.',
      symptoms_hi: 'अपरंपरागत या नैतिक रूप से संदिग्ध ज्ञान की ओर आकर्षण। शिक्षकों और गुरुओं का अनादर।',
      effects_en: 'Misguided wisdom — pursuit of harmful ideologies or wrong company. Tendency toward immoral behavior in matters of knowledge and relationships. Delays in marriage, wealth instability, disrespect toward teachers.',
      effects_hi: 'भटका हुआ ज्ञान — हानिकारक विचारधाराओं का अनुसरण। विवाह में विलंब, धन में अस्थिरता।',
      technical_note_en: 'Ketu with Jupiter often produces saints, mystics, and those who transcend conventional wisdom rather than misuse it. The negative expression is more associated with Rahu-Jupiter.',
      technical_note_hi: 'केतु के साथ बृहस्पति संत, रहस्यवादी उत्पन्न करता है। नकारात्मक अभिव्यक्ति मुख्यतः राहु-गुरु से है।',
      source: 'BPHS',
    },
    {
      name: 'Venus-Mangal Vish Dosha',
      name_hi: 'शुक्र-मंगल विष दोष',
      category: 'vish',
      definition_en: 'Formed by the conjunction of Venus (love, relationships, sensuality) and Mars (passion, physical energy). The affliction distorts Venus\' natural qualities of love into uncontrolled desire and obsessive attraction.',
      definition_hi: 'शुक्र (प्रेम, संबंध) और मंगल (जुनून, शारीरिक ऊर्जा) की युति से बनता है। अनियंत्रित इच्छा और जुनूनी आकर्षण।',
      formation_en: 'Venus and Mars conjunct in the same house.',
      formation_hi: 'शुक्र और मंगल एक ही भाव में युत।',
      symptoms_en: 'Strong, uncontrollable romantic or physical attractions that override judgment. Secretive behavior in matters of love.',
      symptoms_hi: 'मजबूत, अनियंत्रित रोमांटिक आकर्षण। प्रेम और संबंधों में गुप्त व्यवहार।',
      effects_en: 'Multiple romantic relationships, tendency toward extra-marital affairs. Financial losses through romantic misjudgments. Social scandals and reputational damage.',
      effects_hi: 'कई रोमांटिक संबंध, विवाहेतर संबंधों की प्रवृत्ति। वित्तीय हानि। सामाजिक घोटाले।',
      technical_note_en: 'In fire signs or the 5th house, this combination can also produce intense artistic creativity and performance energy. The dosha expression depends heavily on the house placement and overall chart strength.',
      technical_note_hi: 'अग्नि राशियों या 5वें भाव में यह कलात्मक रचनात्मकता भी दे सकता है।',
      source: 'BPHS',
    },
    {
      name: 'Venus-Rahu Vish Dosha',
      name_hi: 'शुक्र-राहु विष दोष',
      category: 'vish',
      definition_en: 'Formed by the conjunction of Venus and Rahu. Rahu\'s obsessive nature combines with Venus\' relationship energy, producing unconventional, obsessive, or illicit attractions and relationship patterns.',
      definition_hi: 'शुक्र और राहु की युति से बनता है। राहु की जुनूनी प्रकृति शुक्र की संबंध ऊर्जा के साथ मिलकर अपरंपरागत या अवैध आकर्षण उत्पन्न करती है।',
      formation_en: 'Venus and Rahu conjunct in the same house.',
      formation_hi: 'शुक्र और राहु एक ही भाव में युत।',
      symptoms_en: 'Obsessive, unconventional romantic attractions. May pursue taboo or forbidden relationships across boundaries (caste, religion, age).',
      symptoms_hi: 'जुनूनी, अपरंपरागत रोमांटिक आकर्षण। वर्जित संबंधों की प्रवृत्ति।',
      effects_en: 'Multiple relationships, illicit affairs, social scandals. Financial instability through relationships. Foreign partners or unconventional marriage situations.',
      effects_hi: 'कई संबंध, अवैध प्रेम प्रसंग, सामाजिक घोटाले। संबंधों के माध्यम से वित्तीय अस्थिरता।',
      technical_note_en: 'Venus-Rahu can produce extraordinary sensory experiences, artistic innovation, and cross-cultural creativity when channeled well. Many artists, performers, and visionaries have this combination.',
      technical_note_hi: 'शुक्र-राहु अच्छी तरह से प्रसारित होने पर असाधारण कलात्मक नवाचार दे सकता है।',
      source: 'BPHS',
    },
    {
      name: 'Kemdrum Dosha',
      name_hi: 'केमद्रुम दोष',
      category: 'luminary',
      definition_en: 'Formed when the Moon stands completely alone — with no planets in the 2nd or 12th house from it, leaving it without direct planetary companionship. Since Moon governs the mind and emotional stability, its isolation creates emotional abandonment and instability.',
      definition_hi: 'जब चंद्रमा पूरी तरह अकेला खड़ा हो — चंद्र से 2 या 12वें भाव में कोई ग्रह नहीं। मन और भावनात्मक स्थिरता की अकेलापन।',
      formation_en: 'Moon must have NO planets in the 2nd or 12th house from its position (Rahu/Ketu excluded). Less effective if Moon receives benefic aspect or benefics are in Kendra/Trikona.',
      formation_hi: 'चंद्र की स्थिति से 2 या 12वें भाव में कोई ग्रह नहीं (राहु-केतु बाहर)। शुभ दृष्टि या शुभ ग्रह केंद्र में हों तो कम प्रभावी।',
      symptoms_en: 'Persistent feeling of being unsupported — emotionally, socially, or materially. Emotional sensitivity and vulnerability.',
      symptoms_hi: 'असमर्थित होने की निरंतर भावना। भावनात्मक संवेदनशीलता और कमजोरी।',
      effects_en: 'Financial hardship, emotional instability, and pattern of struggling despite effort. Lack of family support, feelings of loneliness. Struggles in childhood and emotional burdens carried through life.',
      effects_hi: 'आर्थिक कठिनाई, भावनात्मक अस्थिरता। पारिवारिक सहायता की कमी, एकाकीपन। बचपन में संघर्ष।',
      technical_note_en: 'Frequently overstated in popular Jyotish. If Moon receives benefic aspects, or if benefics occupy Kendra/Trikona positions, the negative effects reduce considerably. Evaluate the complete chart before pronouncing this Dosha.',
      technical_note_hi: 'लोकप्रिय ज्योतिष में अक्सर अतिरंजित। शुभ दृष्टि से नकारात्मक प्रभाव काफी कम होते हैं। संपूर्ण कुंडली का मूल्यांकन आवश्यक।',
      source: 'BPHS',
    },
    {
      name: 'Paap Kartari Dosha',
      name_hi: 'पाप कर्तरी दोष',
      category: 'general',
      definition_en: 'Literally "scissors of malefics" — occurs when a planet or house is hemmed between malefic planets on both sides. The planet/house is "cut" from both sides, restricting its natural significations.',
      definition_hi: '"पापग्रहों की कैंची" — जब कोई ग्रह या भाव दोनों ओर पाप ग्रहों के बीच फंसा हो। ग्रह/भाव के स्वाभाविक कारकत्व को प्रतिबंधित करता है।',
      formation_en: 'Malefics (Saturn, Mars, Rahu, Ketu, afflicted Sun) in both the house immediately before (N-1) AND the house immediately after (N+1) a particular house. Most severe when Lagna, Moon, or Sun is hemmed.',
      formation_hi: 'किसी भाव के ठीक पहले (N-1) और ठीक बाद (N+1) पाप ग्रह। लग्न, चंद्र या सूर्य पर सबसे गंभीर।',
      symptoms_en: 'Significations of hemmed house feel blocked despite sincere effort. If Lagna hemmed: constant constriction of health, confidence, freedom. If 7th hemmed: persistent obstacles in marriage and partnerships.',
      symptoms_hi: 'घिरे भाव के कारकत्व ईमानदार प्रयास के बावजूद अवरुद्ध। लग्न घिरा: स्वास्थ्य, आत्मविश्वास प्रभावित।',
      effects_en: 'Hemmed house loses strength to deliver positive significations. Persistent feelings of being trapped. A hemmed planet produces its significations in a distorted or delayed manner.',
      effects_hi: 'घिरा भाव सकारात्मक कारकत्व देने में संघर्ष करता है। फंसे होने की निरंतर भावना। ग्रह विकृत रूप से परिणाम देता है।',
      technical_note_en: 'Shubh Kartari Yoga is the direct antidote — benefics hemming a house protect and elevate it. The Dasha of malefic planets responsible for the Kartari intensifies effects during their operational periods.',
      technical_note_hi: 'शुभ कर्तरी योग सीधा प्रतिकार है। कर्तरी के लिए जिम्मेदार पाप ग्रहों की दशा प्रभावों को तीव्र करती है।',
      source: 'BPHS',
    },
  ]);
};
