'use strict';
// Seed: AstroAnsh Class 1 Premium Notes
// Ch.1 Vedas & Vedangas | Ch.2 6 Angas of Jyotish | Ch.3 5 Uses of Jyotish
// Ch.4-5 Karma Theory | Ch.6 Hora System | Ch.7-8 Graha Deep & BPHS attributes

exports.seed = async function (knex) {
  await knex('jyotish_basics').del();

  await knex('jyotish_basics').insert([

    // ── Ch.1 — 4 Vedas (admin reference) ──────────────────────────────────────
    {
      category: 'veda', item_key: 'veda_rigveda', sort_order: 1, admin_only: true,
      name_en: 'Rigveda', name_hi: 'ऋग्वेद',
      description_en: 'Oldest and most sacred of the four Vedas. Contains 10,552 hymns (Richas) to the Devas. Primary source of Vedic philosophy, cosmology, and worship. Divided into 10 Mandalas.',
      description_hi: 'चार वेदों में सबसे प्राचीन और पवित्र। इसमें देवताओं को समर्पित 10,552 ऋचाएं (मंत्र) हैं। वैदिक दर्शन, ब्रह्माण्ड विज्ञान एवं उपासना का प्राथमिक स्रोत। 10 मण्डलों में विभाजित।',
      extra_data: JSON.stringify({ hymns: 10552, mandalas: 10, upaveda: 'Ayurveda' }),
    },
    {
      category: 'veda', item_key: 'veda_samaveda', sort_order: 2, admin_only: true,
      name_en: 'Samaveda', name_hi: 'सामवेद',
      description_en: 'Veda of melodies and chants. Most of its 1,875 verses are drawn from the Rigveda, set to musical notation (Saman). Foundation of Indian classical music and ritual chanting.',
      description_hi: 'सुर और संगीत का वेद। इसके 1,875 मंत्र मुख्यतः ऋग्वेद से लिए गए हैं जिन्हें सांगीतिक रूप (साम) में निर्धारित किया गया है। भारतीय शास्त्रीय संगीत एवं यज्ञ गान की नींव।',
      extra_data: JSON.stringify({ hymns: 1875, upaveda: 'Gandharva Veda (Music)' }),
    },
    {
      category: 'veda', item_key: 'veda_yajurveda', sort_order: 3, admin_only: true,
      name_en: 'Yajurveda', name_hi: 'यजुर्वेद',
      description_en: 'Veda of ritual formulas and prose. Contains mantras for Yagna (fire sacrifices). Divided into Krishna (Black) Yajurveda and Shukla (White) Yajurveda. Practical guide for ritual priests (Adhvaryu).',
      description_hi: 'अनुष्ठान सूत्रों और गद्य का वेद। यज्ञ (अग्नि अनुष्ठान) के मंत्र इसमें हैं। कृष्ण यजुर्वेद और शुक्ल यजुर्वेद में विभाजित। अध्वर्यु पुरोहितों के लिए व्यावहारिक मार्गदर्शिका।',
      extra_data: JSON.stringify({ branches: ['Krishna Yajurveda', 'Shukla Yajurveda'], upaveda: 'Dhanur Veda (Archery/Martial)' }),
    },
    {
      category: 'veda', item_key: 'veda_atharvaveda', sort_order: 4, admin_only: true,
      name_en: 'Atharvaveda', name_hi: 'अथर्ववेद',
      description_en: 'Veda of practical knowledge — healing, herbs, daily life, and protection. Contains spells, incantations, and remedies. Closest to daily human experience. Incorporates both Vedic and folk traditions.',
      description_hi: 'व्यावहारिक ज्ञान का वेद — चिकित्सा, जड़ी-बूटियाँ, दैनिक जीवन और सुरक्षा। इसमें मंत्र, अनुष्ठान एवं उपाय हैं। दैनिक मानव अनुभव के सबसे निकट। वैदिक और लोक परंपराओं का समागम।',
      extra_data: JSON.stringify({ hymns: 5977, upaveda: 'Sthapatya Veda (Architecture/Vastu)' }),
    },

    // ── Ch.1 — 6 Vedangas (limbs of Veda) ────────────────────────────────────
    {
      category: 'vedanga', item_key: 'vedanga_shiksha', sort_order: 1, admin_only: true,
      name_en: 'Shiksha — Phonetics', name_hi: 'शिक्षा — स्वरशास्त्र',
      description_en: 'Science of correct pronunciation and phonetics of Vedic mantras. Deals with accent (Svaras), quantity, stress, and euphonic combination. Ensures mantras are chanted with perfect intonation for maximum effect.',
      description_hi: 'वैदिक मंत्रों के शुद्ध उच्चारण और स्वरशास्त्र का विज्ञान। स्वर, मात्रा, बल और संधि विषयक नियम। मंत्रों को सही आरोह-अवरोह से उच्चारित करने के लिए ताकि अधिकतम प्रभाव हो।',
      extra_data: JSON.stringify({ function: 'Nose (Nasal cavity) of the Veda — Vedic phonetics' }),
    },
    {
      category: 'vedanga', item_key: 'vedanga_kalpa', sort_order: 2, admin_only: true,
      name_en: 'Kalpa — Ritual Procedure', name_hi: 'कल्प — अनुष्ठान विधि',
      description_en: 'Science of ritual procedures and ceremonial rites. Includes Shrauta Sutras (major yajnas), Grihya Sutras (domestic rituals), Dharma Sutras (social duties), and Shulba Sutras (geometry for altar construction).',
      description_hi: 'अनुष्ठान प्रक्रियाओं और कर्मकांडों का विज्ञान। इसमें श्रौत सूत्र (महायज्ञ), गृह्य सूत्र (घरेलू संस्कार), धर्म सूत्र (सामाजिक कर्तव्य) और शुल्ब सूत्र (वेदी रचना ज्यामिति) शामिल हैं।',
      extra_data: JSON.stringify({ function: 'Hands of the Veda — actions and rituals' }),
    },
    {
      category: 'vedanga', item_key: 'vedanga_vyakarana', sort_order: 3, admin_only: true,
      name_en: 'Vyakarana — Grammar', name_hi: 'व्याकरण — संस्कृत व्याकरण',
      description_en: 'Sanskrit grammar. Panini\'s Ashtadhyayi (8-chapter grammar text) is its pinnacle. Ensures correct formation of words and sentences in Vedic and classical Sanskrit. Makes the language precise and unambiguous.',
      description_hi: 'संस्कृत व्याकरण। पाणिनि का अष्टाध्यायी (8 अध्याय की व्याकरण पुस्तक) इसका शिखर है। वैदिक और शास्त्रीय संस्कृत में शब्दों और वाक्यों के सही गठन को सुनिश्चित करता है।',
      extra_data: JSON.stringify({ function: 'Mouth of the Veda — precise language', key_text: 'Panini Ashtadhyayi (3977 sutras)' }),
    },
    {
      category: 'vedanga', item_key: 'vedanga_nirukta', sort_order: 4, admin_only: true,
      name_en: 'Nirukta — Etymology', name_hi: 'निरुक्त — शब्द व्युत्पत्ति',
      description_en: 'Science of word etymology and meaning. Yaska\'s Nirukta is the foundational text. Explains the origin, derivation, and deeper meaning of Vedic words and mantras. Critical for correct interpretation of sacred texts.',
      description_hi: 'शब्द व्युत्पत्ति और अर्थ का विज्ञान। यास्क का निरुक्त मूल ग्रंथ है। वैदिक शब्दों और मंत्रों की उत्पत्ति, व्युत्पत्ति और गहरे अर्थ की व्याख्या करता है।',
      extra_data: JSON.stringify({ function: 'Ears of the Veda — understanding meaning', key_text: 'Yaska Nirukta' }),
    },
    {
      category: 'vedanga', item_key: 'vedanga_chhandas', sort_order: 5, admin_only: true,
      name_en: 'Chhandas — Meter/Prosody', name_hi: 'छन्दस् — वैदिक छंद',
      description_en: 'Science of Vedic meters (Chhandas). Defines rhythmic structure of Vedic verses — Gayatri (24 syllables), Trishtubh (44), Jagati (48), Anushtubh (32), Pankti (40), etc. Each meter carries specific vibrational energy.',
      description_hi: 'वैदिक छंदों का विज्ञान। वैदिक पदों की लयात्मक संरचना परिभाषित करता है — गायत्री (24 अक्षर), त्रिष्टुभ् (44), जगती (48), अनुष्टुभ् (32), पंक्ति (40) आदि। प्रत्येक छंद विशिष्ट ऊर्जा धारण करता है।',
      extra_data: JSON.stringify({ function: 'Feet of the Veda — rhythmic movement', key_meters: ['Gayatri', 'Trishtubh', 'Jagati', 'Anushtubh'] }),
    },
    {
      category: 'vedanga', item_key: 'vedanga_jyotish', sort_order: 6, admin_only: true,
      name_en: 'Jyotish — Astronomy & Astrology', name_hi: 'ज्योतिष — खगोल एवं ज्योतिष',
      description_en: 'The eyes of the Vedas. Science of time (Kala Vidya) — determines correct timing for all Vedic rituals. Encompasses astronomy, mathematics, and astrology. Only Vedanga that continues as a living practice today.',
      description_hi: 'वेदों की आँखें। काल विद्या — सभी वैदिक अनुष्ठानों के लिए शुभ समय निर्धारित करती है। खगोल विज्ञान, गणित और ज्योतिष को समाहित करती है। एकमात्र वेदांग जो आज भी जीवंत परंपरा के रूप में है।',
      extra_data: JSON.stringify({ function: 'Eyes of the Veda — light and time', note: 'Most practical of all Vedangas' }),
    },

    // ── Ch.2 — 6 Angas of Jyotish ─────────────────────────────────────────────
    {
      category: 'jyotish_anga', item_key: 'anga_gola', sort_order: 1, admin_only: true,
      name_en: 'Gola — Spherical Astronomy', name_hi: 'गोल — गोलीय खगोल',
      description_en: 'Astronomical branch dealing with the celestial sphere, planetary movements, and mathematical computation of positions. Foundation of all Jyotish calculations. Includes understanding of ecliptic, equator, zodiac, and planetary orbits.',
      description_hi: 'खगोलीय शाखा जो आकाशीय गोल, ग्रह गति और स्थिति की गणितीय गणना से संबंधित है। सभी ज्योतिष गणनाओं की नींव। क्रांतिवृत्त, भूमध्य रेखा, राशिचक्र और ग्रह कक्षाओं की समझ।',
    },
    {
      category: 'jyotish_anga', item_key: 'anga_ganita', sort_order: 2, admin_only: true,
      name_en: 'Ganita — Mathematical Astronomy', name_hi: 'गणित — गणितीय खगोल',
      description_en: 'Mathematical computations for astronomy — calculating planetary longitudes, sidereal time, Julian Day numbers, and Panchang elements. This is the computational engine of Jyotish.',
      description_hi: 'खगोल विज्ञान की गणितीय गणनाएं — ग्रह रेखांश, सायन काल, जूलियन दिन संख्या और पंचांग तत्वों की गणना। यह ज्योतिष का गणनात्मक इंजन है।',
    },
    {
      category: 'jyotish_anga', item_key: 'anga_jataka', sort_order: 3, admin_only: false,
      name_en: 'Jataka — Natal Astrology', name_hi: 'जातक — जन्म ज्योतिष',
      description_en: 'Birth chart astrology. Interpreting the horoscope cast for the moment of birth to understand personality, health, career, relationships, and life events. The most widely practised branch. Source of Kundli reading.',
      description_hi: 'जन्म कुंडली ज्योतिष। जन्म के क्षण की कुंडली का विश्लेषण करके व्यक्तित्व, स्वास्थ्य, करियर, संबंध और जीवन घटनाओं को समझना। सर्वाधिक प्रचलित शाखा। कुंडली पठन का स्रोत।',
    },
    {
      category: 'jyotish_anga', item_key: 'anga_prashna', sort_order: 4, admin_only: true,
      name_en: 'Prashna — Horary Astrology', name_hi: 'प्रश्न — प्रश्न ज्योतिष',
      description_en: 'Chart cast for the exact moment a question is asked. Does not require birth data — uses the moment of enquiry instead. Answers specific questions about events, objects, or outcomes. Powerful for immediate practical concerns.',
      description_hi: 'प्रश्न पूछे जाने के ठीक समय की कुंडली। जन्म डेटा की आवश्यकता नहीं — प्रश्न के समय का उपयोग होता है। विशिष्ट घटनाओं, वस्तुओं या परिणामों के बारे में उत्तर देता है।',
    },
    {
      category: 'jyotish_anga', item_key: 'anga_muhurta', sort_order: 5, admin_only: false,
      name_en: 'Muhurta — Electional Astrology', name_hi: 'मुहूर्त — शुभ समय चयन',
      description_en: 'Selection of auspicious timing for important actions — marriage, business start, travel, surgery, house entry. Ensures activities begin under favourable planetary configurations for best outcomes.',
      description_hi: 'महत्वपूर्ण कार्यों के लिए शुभ समय का चयन — विवाह, व्यापार प्रारंभ, यात्रा, शल्य चिकित्सा, गृह प्रवेश। सर्वोत्तम परिणाम के लिए अनुकूल ग्रह स्थितियों में कार्य प्रारंभ सुनिश्चित करता है।',
    },
    {
      category: 'jyotish_anga', item_key: 'anga_nimitta', sort_order: 6, admin_only: true,
      name_en: 'Nimitta — Omens & Signs', name_hi: 'निमित्त — शकुन शास्त्र',
      description_en: 'Science of omens, signs, and natural phenomena as indicators of upcoming events. Includes interpretation of bird behaviour, twitching of body parts (Anga Spandan), natural events, and spontaneous occurrences as divine signals.',
      description_hi: 'शकुन, संकेत और प्राकृतिक घटनाओं का विज्ञान जो आगामी घटनाओं के सूचक हैं। पक्षी व्यवहार, शरीर के अंगों का फड़कना (अंग स्पंदन), प्राकृतिक घटनाएं और दैव संकेतों की व्याख्या।',
    },

    // ── Ch.3 — 5 Uses of Jyotish ──────────────────────────────────────────────
    {
      category: 'jyotish_use', item_key: 'use_trikaal', sort_order: 1, admin_only: false,
      name_en: 'Trikaal Darshan — Knowledge of Three Times', name_hi: 'त्रिकाल दर्शन — तीन कालों का ज्ञान',
      description_en: 'Understanding past, present, and future through planetary analysis. Jyotish reveals the timing of major life events — past karmas expressed as life experiences, current transit impacts, and future possibilities.',
      description_hi: 'ग्रह विश्लेषण के माध्यम से भूत, वर्तमान और भविष्य का ज्ञान। ज्योतिष जीवन की प्रमुख घटनाओं का समय प्रकट करता है — विगत कर्म जीवन अनुभवों में व्यक्त, वर्तमान गोचर प्रभाव और भावी संभावनाएं।',
    },
    {
      category: 'jyotish_use', item_key: 'use_karma', sort_order: 2, admin_only: false,
      name_en: 'Karma Understanding — Reading Prarabdha', name_hi: 'कर्म समझ — प्रारब्ध कर्म पठन',
      description_en: 'Jyotish decodes the prarabdha karma — the portion of accumulated karma activated in this life. The D1 chart is the operating karma map. Houses 6, 8, 12 show karmic debts; yogas show karmic rewards.',
      description_hi: 'ज्योतिष प्रारब्ध कर्म को समझने में सहायक है — संचित कर्म का वह हिस्सा जो इस जन्म में सक्रिय है। D1 कुंडली कर्म का नक्शा है। भाव 6, 8, 12 कर्मिक ऋण दिखाते हैं; योग कर्मिक पुरस्कार।',
    },
    {
      category: 'jyotish_use', item_key: 'use_muhurta', sort_order: 3, admin_only: false,
      name_en: 'Muhurta — Choosing Right Action Time', name_hi: 'मुहूर्त — सही समय पर कार्य',
      description_en: 'Using planetary cycles to find the optimal timing for important actions. Even a good karma can produce delayed or reduced results if begun at an inauspicious time. Muhurta maximises success probability.',
      description_hi: 'महत्वपूर्ण कार्यों के लिए इष्टतम समय खोजने के लिए ग्रह चक्रों का उपयोग। अच्छा कर्म भी अशुभ समय पर प्रारंभ होने से विलंबित या कम परिणाम दे सकता है।',
    },
    {
      category: 'jyotish_use', item_key: 'use_prashna', sort_order: 4, admin_only: true,
      name_en: 'Prashna — Answering Questions', name_hi: 'प्रश्न — प्रश्नों का उत्तर',
      description_en: 'Using the moment of question as a chart to answer specific queries. Especially useful when birth data is unavailable or uncertain. Real-time planetary positions provide the answer to the question asked.',
      description_hi: 'विशिष्ट प्रश्नों के उत्तर के लिए प्रश्न के क्षण को कुंडली के रूप में उपयोग। जन्म डेटा अनुपलब्ध या अनिश्चित होने पर विशेष उपयोगी।',
    },
    {
      category: 'jyotish_use', item_key: 'use_nimitta', sort_order: 5, admin_only: true,
      name_en: 'Nimitta — Reading Cosmic Signs', name_hi: 'निमित्त — ब्रह्मांडीय संकेत पठन',
      description_en: 'Reading spontaneous signs and omens as cosmic communication. Birds, animals, body sensations, environmental events — all can carry messages when observed with a trained eye in the right context.',
      description_hi: 'स्वतःस्फूर्त संकेतों और शकुनों को ब्रह्मांडीय संचार के रूप में पढ़ना। पक्षी, जानवर, शारीरिक संवेदनाएं, पर्यावरणीय घटनाएं — प्रशिक्षित दृष्टि से सही संदर्भ में सभी संदेश वहन कर सकते हैं।',
    },

    // ── Ch.4-5 — Karma Theory ─────────────────────────────────────────────────
    {
      category: 'karma_type', item_key: 'karma_sanchit', sort_order: 1, admin_only: false,
      name_en: 'Sanchit Karma — Total Accumulated Karma', name_hi: 'संचित कर्म — संपूर्ण संचित कर्म',
      description_en: 'The entire storehouse of karmas accumulated across all past lifetimes. Too vast to experience in one life. Visible in the 12th house (dissolution/past lives) and D60 (Shashtiamsha) chart. Represented by the causal body (Karan Shareer).',
      description_hi: 'सभी पिछले जन्मों में संचित कर्मों का सम्पूर्ण भण्डार। एक जीवन में भोगने के लिए बहुत विशाल। 12वें भाव (विघटन/पूर्व जन्म) और D60 (षष्ट्यांश) कुंडली में दृश्य। कारण शरीर से संबंधित।',
      extra_data: JSON.stringify({ jyotish_house: 12, varga: 'D60', body: 'Karan Shareer (Causal Body)' }),
    },
    {
      category: 'karma_type', item_key: 'karma_prarabdha', sort_order: 2, admin_only: false,
      name_en: 'Prarabdha Karma — Activated Birth Karma', name_hi: 'प्रारब्ध कर्म — सक्रिय जन्म कर्म',
      description_en: 'The portion of Sanchit karma activated for this birth. This IS the D1 birth chart. Shows what must be experienced in this lifetime — cannot be changed, only understood and navigated wisely. Represented by the subtle body (Sukshma Shareer).',
      description_hi: 'संचित कर्म का वह भाग जो इस जन्म के लिए सक्रिय हुआ। यही D1 जन्म कुंडली है। इस जीवन में जो अनुभव करना है वह दिखाता है — बदला नहीं जा सकता, केवल समझकर बुद्धिमानी से नेविगेट किया जा सकता है। सूक्ष्म शरीर से संबंधित।',
      extra_data: JSON.stringify({ jyotish_house: 'D1 entire chart', varga: 'D1', body: 'Sukshma Shareer (Subtle Body)' }),
    },
    {
      category: 'karma_type', item_key: 'karma_kriyaman', sort_order: 3, admin_only: false,
      name_en: 'Kriyaman Karma — Current Free-will Actions', name_hi: 'क्रियमान कर्म — वर्तमान स्वतन्त्र कर्म',
      description_en: 'Karma being created NOW through current actions, thoughts, and choices. This is where free will operates. Seen through Gochar (current transits). Positive Kriyaman karma can soften Prarabdha. Represented by the physical body (Sthool Shareer).',
      description_hi: 'वर्तमान कार्यों, विचारों और चुनावों के माध्यम से अभी बनाया जा रहा कर्म। यहीं स्वतंत्र इच्छा काम करती है। गोचर (वर्तमान ग्रह स्थिति) के माध्यम से देखा जाता है। सकारात्मक क्रियमान कर्म प्रारब्ध को कम कर सकता है। स्थूल शरीर से संबंधित।',
      extra_data: JSON.stringify({ jyotish_indicator: 'Gochar (transits)', body: 'Sthool Shareer (Physical Body)', free_will: true }),
    },

    // ── Ch.6 — Hora System ────────────────────────────────────────────────────
    {
      category: 'hora_rule', item_key: 'hora_overview', sort_order: 1, admin_only: false,
      name_en: 'Hora System Overview', name_hi: 'होरा प्रणाली अवलोकन',
      description_en: 'The day is divided into 24 Horas (planetary hours), each ~60 minutes. The first Hora of each day is ruled by the day\'s lord. Subsequent Horas follow the Chaldean order: Sun → Venus → Mercury → Moon → Saturn → Jupiter → Mars (repeating).',
      description_hi: 'दिन को 24 होराओं (ग्रह घंटों) में विभाजित किया गया है, प्रत्येक लगभग 60 मिनट। प्रत्येक दिन की पहली होरा उस दिन के स्वामी से संचालित होती है। बाद की होराएं कल्डियन क्रम में: सूर्य → शुक्र → बुध → चंद्र → शनि → बृहस्पति → मंगल (पुनरावृत्ति)।',
      extra_data: JSON.stringify({
        chaldean_order: ['Sun', 'Venus', 'Mercury', 'Moon', 'Saturn', 'Jupiter', 'Mars'],
        day_lords: { Sunday: 'Sun', Monday: 'Moon', Tuesday: 'Mars', Wednesday: 'Mercury', Thursday: 'Jupiter', Friday: 'Venus', Saturday: 'Saturn' },
        note: 'Each Hora is approx 60 min. Start from sunrise. 8th Hora = next hour after 7 = same lord as day lord shift.',
      }),
    },
    {
      category: 'hora_rule', item_key: 'hora_effects', sort_order: 2, admin_only: false,
      name_en: 'Hora Effects per Planet', name_hi: 'ग्रह अनुसार होरा प्रभाव',
      description_en: 'Each planetary Hora carries its lord\'s energy: Sun Hora — government work, authority, father, health. Moon Hora — family, women, mind, water. Mars Hora — action, surgery, courage, disputes. Mercury Hora — business, travel, communication. Jupiter Hora — teaching, spirituality, wealth expansion. Venus Hora — arts, love, luxury. Saturn Hora — labour, agriculture, old matters.',
      description_hi: 'प्रत्येक ग्रह होरा अपने स्वामी की ऊर्जा धारण करती है: सूर्य होरा — सरकारी काम, अधिकार, पिता, स्वास्थ्य। चंद्र होरा — परिवार, महिलाएं, मन, जल। मंगल होरा — क्रिया, शल्य, साहस, विवाद। बुध होरा — व्यापार, यात्रा, संचार। बृहस्पति होरा — शिक्षण, आध्यात्म, धन विस्तार। शुक्र होरा — कला, प्रेम, विलासिता। शनि होरा — श्रम, कृषि, पुराने विषय।',
      extra_data: JSON.stringify({
        Sun: 'Government, authority, father, health, fire, copper, bones',
        Moon: 'Family, women, mind, water, silver, travel, emotions',
        Mars: 'Action, surgery, courage, disputes, property, brothers',
        Mercury: 'Business, travel, writing, communication, intellect',
        Jupiter: 'Teaching, spirituality, wealth, wisdom, children, guru',
        Venus: 'Arts, love, luxury, vehicles, relationships, beauty',
        Saturn: 'Labour, agriculture, old matters, chronic issues, delays',
      }),
    },

    // ── Ch.7-8 — Graha BPHS Deep Attributes ──────────────────────────────────
    {
      category: 'graha_bphs', item_key: 'graha_sun_bphs', sort_order: 1, admin_only: false,
      name_en: 'Surya (Sun) — BPHS Attributes', name_hi: 'सूर्य — BPHS गुण',
      description_en: 'Natural Malefic. Atma Karaka. Signifies: soul, father, authority, government, king, bone, heart, right eye, east direction. Best house: 10th (Digbala). Friendly: Moon, Mars, Jupiter. Enemies: Saturn, Venus. Neutral: Mercury. Vimshottari period: 6 years. Colour: Copper/Rust. Metal: Gold. Day: Sunday.',
      description_hi: 'नैसर्गिक क्रूर। आत्मकारक। कारकत्व: आत्मा, पिता, अधिकार, सरकार, राजा, हड्डी, हृदय, दायीं आँख, पूर्व दिशा। सर्वश्रेष्ठ भाव: 10वाँ (दिग्बल)। मित्र: चंद्र, मंगल, बृहस्पति। शत्रु: शनि, शुक्र। तटस्थ: बुध। विंशोत्तरी: 6 वर्ष। रंग: ताम्र। धातु: सोना। दिन: रविवार।',
      extra_data: JSON.stringify({
        natural_nature: 'malefic',
        atmakaraka_type: 'Atma (Soul)',
        karakatva: ['Soul', 'Father', 'Authority', 'Government', 'King', 'Bone', 'Heart', 'Right Eye', 'East'],
        digbala_house: 10,
        friends: ['Moon', 'Mars', 'Jupiter'],
        enemies: ['Saturn', 'Venus'],
        neutral: ['Mercury'],
        vimshottari_years: 6,
        exaltation: 'Aries 10°',
        debilitation: 'Libra 10°',
        own_sign: 'Leo',
        moolatrikona: 'Leo 0–20°',
        body_part: ['Heart', 'Bone', 'Right Eye', 'Stomach', 'Head'],
      }),
    },
    {
      category: 'graha_bphs', item_key: 'graha_moon_bphs', sort_order: 2, admin_only: false,
      name_en: 'Chandra (Moon) — BPHS Attributes', name_hi: 'चंद्र — BPHS गुण',
      description_en: 'Natural Benefic (strong when waxing/full). Mind Karaka. Signifies: mind, mother, water, emotions, milk, silver, pearls, chest, lungs, blood, left eye. Best house: 4th (Digbala). Friendly: Sun, Mercury. Enemies: None. Neutral: Mars, Jupiter, Venus, Saturn. Vimshottari: 10 years.',
      description_hi: 'नैसर्गिक शुभ (वृद्ध/पूर्णिमा पर शक्तिशाली)। मन कारक। कारकत्व: मन, माता, जल, भावनाएं, दूध, चाँदी, मोती, छाती, फेफड़े, रक्त, बायीं आँख। सर्वश्रेष्ठ भाव: 4वाँ (दिग्बल)। मित्र: सूर्य, बुध। शत्रु: कोई नहीं। तटस्थ: मंगल, बृहस्पति, शुक्र, शनि। विंशोत्तरी: 10 वर्ष।',
      extra_data: JSON.stringify({
        natural_nature: 'benefic_conditional',
        karakatva: ['Mind', 'Mother', 'Water', 'Emotions', 'Milk', 'Silver', 'Pearls', 'Chest', 'Blood', 'Left Eye'],
        digbala_house: 4,
        friends: ['Sun', 'Mercury'],
        enemies: [],
        neutral: ['Mars', 'Jupiter', 'Venus', 'Saturn'],
        vimshottari_years: 10,
        exaltation: 'Taurus 3°',
        debilitation: 'Scorpio 3°',
        own_sign: 'Cancer',
        moolatrikona: 'Taurus 4–20°',
        strength_condition: 'Strong when waxing (Shukla Paksha); weak when waning (Krishna Paksha)',
      }),
    },
    {
      category: 'graha_bphs', item_key: 'graha_mars_bphs', sort_order: 3, admin_only: false,
      name_en: 'Mangala (Mars) — BPHS Attributes', name_hi: 'मंगल — BPHS गुण',
      description_en: 'Natural Malefic. Bhoomi (land) Karaka. Signifies: courage, energy, brothers, land/property, blood, muscles, surgery, weapons, police, fire. Best house: 10th (Digbala). Friendly: Sun, Moon, Jupiter. Enemies: Mercury. Neutral: Venus, Saturn. Vimshottari: 7 years. Causes Mangal Dosha from 1,2,4,7,8,12.',
      description_hi: 'नैसर्गिक क्रूर। भूमि कारक। कारकत्व: साहस, ऊर्जा, भाई, भूमि/संपत्ति, रक्त, मांसपेशियाँ, शल्य, शस्त्र, पुलिस, अग्नि। सर्वश्रेष्ठ भाव: 10वाँ (दिग्बल)। मित्र: सूर्य, चंद्र, बृहस्पति। शत्रु: बुध। तटस्थ: शुक्र, शनि। विंशोत्तरी: 7 वर्ष। भाव 1,2,4,7,8,12 से मंगल दोष।',
      extra_data: JSON.stringify({
        natural_nature: 'malefic',
        karakatva: ['Courage', 'Energy', 'Brothers', 'Land', 'Property', 'Blood', 'Muscles', 'Surgery', 'Police', 'Fire', 'Weapons'],
        digbala_house: 10,
        special_aspects: [4, 7, 8],
        friends: ['Sun', 'Moon', 'Jupiter'],
        enemies: ['Mercury'],
        neutral: ['Venus', 'Saturn'],
        vimshottari_years: 7,
        exaltation: 'Capricorn 28°',
        debilitation: 'Cancer 28°',
        own_sign: ['Aries', 'Scorpio'],
        moolatrikona: 'Aries 0–12°',
        mangal_dosha_houses: [1, 2, 4, 7, 8, 12],
      }),
    },
    {
      category: 'graha_bphs', item_key: 'graha_mercury_bphs', sort_order: 4, admin_only: false,
      name_en: 'Budha (Mercury) — BPHS Attributes', name_hi: 'बुध — BPHS गुण',
      description_en: 'Natural Benefic (when alone/with benefics). Buddhi Karaka. Signifies: intelligence, communication, business, education, writing, nervous system, skin, discrimination, wit. Best house: 1st (Digbala). Friends: Sun, Venus. Enemies: Moon. Neutral: Mars, Jupiter, Saturn. Vimshottari: 17 years.',
      description_hi: 'नैसर्गिक शुभ (अकेले/शुभ ग्रहों के साथ)। बुद्धि कारक। कारकत्व: बुद्धि, संचार, व्यापार, शिक्षा, लेखन, तंत्रिका तंत्र, त्वचा, विवेक, चातुर्य। सर्वश्रेष्ठ भाव: 1वाँ (दिग्बल)। मित्र: सूर्य, शुक्र। शत्रु: चंद्र। तटस्थ: मंगल, बृहस्पति, शनि। विंशोत्तरी: 17 वर्ष।',
      extra_data: JSON.stringify({
        natural_nature: 'benefic_conditional',
        karakatva: ['Intelligence', 'Communication', 'Business', 'Education', 'Writing', 'Nervous System', 'Skin', 'Trade'],
        digbala_house: 1,
        friends: ['Sun', 'Venus'],
        enemies: ['Moon'],
        neutral: ['Mars', 'Jupiter', 'Saturn'],
        vimshottari_years: 17,
        exaltation: 'Virgo 15°',
        debilitation: 'Pisces 15°',
        own_sign: ['Gemini', 'Virgo'],
        moolatrikona: 'Virgo 16–20°',
        note: 'Becomes malefic when conjunct malefics (Papa-kartari)',
      }),
    },
    {
      category: 'graha_bphs', item_key: 'graha_jupiter_bphs', sort_order: 5, admin_only: false,
      name_en: 'Guru (Jupiter) — BPHS Attributes', name_hi: 'गुरु/बृहस्पति — BPHS गुण',
      description_en: 'Greatest Natural Benefic. Jeeva Karaka (life). Signifies: wisdom, dharma, religion, children, wealth, teacher/guru, liver, hips, fat, ears, expansion. Best house: 1st (Digbala). Friendly with all except Mercury and Venus. Vimshottari: 16 years. Aspects: 5th, 7th, 9th.',
      description_hi: 'सर्वश्रेष्ठ नैसर्गिक शुभ। जीव कारक। कारकत्व: ज्ञान, धर्म, संतान, धन, गुरु, यकृत, कूल्हे, चर्बी, कान, विस्तार। सर्वश्रेष्ठ भाव: 1वाँ (दिग्बल)। बुध और शुक्र को छोड़कर सभी के मित्र। विंशोत्तरी: 16 वर्ष। दृष्टि: 5वाँ, 7वाँ, 9वाँ।',
      extra_data: JSON.stringify({
        natural_nature: 'benefic',
        karakatva: ['Wisdom', 'Dharma', 'Children', 'Wealth', 'Guru/Teacher', 'Liver', 'Hips', 'Expansion', 'Religion', 'Grace'],
        digbala_house: 1,
        special_aspects: [5, 7, 9],
        friends: ['Sun', 'Moon', 'Mars'],
        enemies: ['Mercury', 'Venus'],
        neutral: ['Saturn'],
        vimshottari_years: 16,
        exaltation: 'Cancer 5°',
        debilitation: 'Capricorn 5°',
        own_sign: ['Sagittarius', 'Pisces'],
        moolatrikona: 'Sagittarius 0–10°',
        special_note: 'Neechabhanga Raj Yoga: when debilitated Jupiter is aspected by exalted planet',
      }),
    },
    {
      category: 'graha_bphs', item_key: 'graha_venus_bphs', sort_order: 6, admin_only: false,
      name_en: 'Shukra (Venus) — BPHS Attributes', name_hi: 'शुक्र — BPHS गुण',
      description_en: 'Natural Benefic. Kalatra Karaka (spouse). Signifies: love, beauty, art, marriage, luxury, vehicles, creativity, semen, reproductive organs, throat, kidneys, south-east. Best house: 4th (Digbala). Friendly: Mercury, Saturn. Enemies: Sun, Moon. Neutral: Mars, Jupiter. Vimshottari: 20 years.',
      description_hi: 'नैसर्गिक शुभ। कलत्र कारक (जीवनसाथी)। कारकत्व: प्रेम, सौंदर्य, कला, विवाह, विलासिता, वाहन, सृजनशीलता, वीर्य, प्रजनन अंग, गला, गुर्दे, दक्षिण-पूर्व। सर्वश्रेष्ठ भाव: 4वाँ (दिग्बल)। मित्र: बुध, शनि। शत्रु: सूर्य, चंद्र। तटस्थ: मंगल, बृहस्पति। विंशोत्तरी: 20 वर्ष।',
      extra_data: JSON.stringify({
        natural_nature: 'benefic',
        karakatva: ['Love', 'Beauty', 'Art', 'Marriage', 'Spouse', 'Luxury', 'Vehicles', 'Creativity', 'Semen', 'Reproductive', 'Throat', 'Kidneys'],
        digbala_house: 4,
        friends: ['Mercury', 'Saturn'],
        enemies: ['Sun', 'Moon'],
        neutral: ['Mars', 'Jupiter'],
        vimshottari_years: 20,
        exaltation: 'Pisces 27°',
        debilitation: 'Virgo 27°',
        own_sign: ['Taurus', 'Libra'],
        moolatrikona: 'Libra 0–15°',
      }),
    },
    {
      category: 'graha_bphs', item_key: 'graha_saturn_bphs', sort_order: 7, admin_only: false,
      name_en: 'Shani (Saturn) — BPHS Attributes', name_hi: 'शनि — BPHS गुण',
      description_en: 'Greatest Natural Malefic. Ayu Karaka (longevity). Signifies: karma, discipline, delays, service, servants, iron, oil, bones, joints, chronic diseases, detachment, old age, west direction. Best house: 7th (Digbala). Aspects 3rd, 7th, 10th. Vimshottari: 19 years. Causes Sade Sati over 7.5 years.',
      description_hi: 'सर्वश्रेष्ठ नैसर्गिक क्रूर। आयु कारक। कारकत्व: कर्म, अनुशासन, विलंब, सेवा, नौकर, लोहा, तेल, हड्डियाँ, जोड़, पुराने रोग, वैराग्य, बुढ़ापा, पश्चिम दिशा। सर्वश्रेष्ठ भाव: 7वाँ (दिग्बल)। दृष्टि: 3वाँ, 7वाँ, 10वाँ। विंशोत्तरी: 19 वर्ष। 7.5 वर्ष की साढ़ेसाती।',
      extra_data: JSON.stringify({
        natural_nature: 'malefic',
        karakatva: ['Karma', 'Discipline', 'Delays', 'Service', 'Iron', 'Oil', 'Bones', 'Joints', 'Chronic Disease', 'Detachment', 'Old Age', 'Longevity'],
        digbala_house: 7,
        special_aspects: [3, 7, 10],
        friends: ['Mercury', 'Venus'],
        enemies: ['Sun', 'Moon', 'Mars'],
        neutral: ['Jupiter'],
        vimshottari_years: 19,
        exaltation: 'Libra 20°',
        debilitation: 'Aries 20°',
        own_sign: ['Capricorn', 'Aquarius'],
        moolatrikona: 'Aquarius 0–20°',
        sade_sati: '7.5 year transit over natal Moon sign (one sign before, Moon sign, one sign after)',
      }),
    },
    {
      category: 'graha_bphs', item_key: 'graha_rahu_bphs', sort_order: 8, admin_only: false,
      name_en: 'Rahu — BPHS Attributes', name_hi: 'राहु — BPHS गुण',
      description_en: 'Shadow planet (Chhaya Graha). Always retrograde. Signifies: obsessions, foreign lands, technology, unconventional paths, illusions, amplification, sudden gains, epidemics, smoke, poison. Behaves like Saturn. Aspects: 5th, 7th, 9th. Vimshottari: 18 years. Exaltation debated: Taurus or Gemini.',
      description_hi: 'छाया ग्रह। सदा वक्री। कारकत्व: जुनून, विदेश, प्रौद्योगिकी, अपरंपरागत मार्ग, भ्रम, प्रवर्धन, अचानक लाभ, महामारी, धुआँ, विष। शनि जैसा व्यवहार। दृष्टि: 5वाँ, 7वाँ, 9वाँ। विंशोत्तरी: 18 वर्ष।',
      extra_data: JSON.stringify({
        natural_nature: 'malefic_shadow',
        karakatva: ['Obsessions', 'Foreign', 'Technology', 'Illusions', 'Sudden Gains', 'Epidemics', 'Amplification', 'Smoke', 'Poison'],
        special_aspects: [5, 7, 9],
        vimshottari_years: 18,
        exaltation: 'Taurus (debated: Gemini)',
        debilitation: 'Scorpio (debated: Sagittarius)',
        behaves_like: 'Saturn',
        always_retrograde: true,
        note: 'Amplifies the house and sign it occupies. North Node of Moon.',
      }),
    },
    {
      category: 'graha_bphs', item_key: 'graha_ketu_bphs', sort_order: 9, admin_only: false,
      name_en: 'Ketu — BPHS Attributes', name_hi: 'केतु — BPHS गुण',
      description_en: 'Shadow planet (Chhaya Graha). Always retrograde. Always 180° from Rahu. Signifies: spirituality, moksha, past life, detachment, occult, liberation, confusion, mysticism. Behaves like Mars. Aspects: 5th, 7th, 9th. Vimshottari: 7 years. Exaltation: Scorpio (debated).',
      description_hi: 'छाया ग्रह। सदा वक्री। सदा राहु से 180°। कारकत्व: आध्यात्मिकता, मोक्ष, पूर्व जन्म, वैराग्य, तंत्र, मुक्ति, भ्रम, रहस्यवाद। मंगल जैसा व्यवहार। दृष्टि: 5वाँ, 7वाँ, 9वाँ। विंशोत्तरी: 7 वर्ष।',
      extra_data: JSON.stringify({
        natural_nature: 'malefic_shadow',
        karakatva: ['Spirituality', 'Moksha', 'Past Life', 'Detachment', 'Occult', 'Liberation', 'Confusion', 'Mysticism'],
        special_aspects: [5, 7, 9],
        vimshottari_years: 7,
        exaltation: 'Scorpio (debated: Sagittarius)',
        debilitation: 'Taurus (debated: Gemini)',
        behaves_like: 'Mars',
        always_retrograde: true,
        note: 'South Node of Moon. Indicates past life expertise and sudden liberation from material ties.',
      }),
    },

  ]);
};
