// Seed 015 — Bhava Lord Interpretations (AstroAnsh Class 7 BPHS)
// Source: "AstroAnsh Class 7 Premium Notes.pdf" — 144 bilingual combinations
// Pattern: DELETE + INSERT (safe to re-run)

exports.seed = async function (knex) {
  await knex('house_lord_interpretations').del();

  const src = 'AstroAnsh Class 7 Premium Notes.pdf (BPHS)';

  // ── Lord metadata ────────────────────────────────────────────────────────────
  const LORDS = [
    { n: 1, en: 'Lagna Pati', hi: 'लग्नेश',
      sig_en: 'Self, Personality, Physical Body, Health, Appearance, and Life Force',
      sig_hi: 'व्यक्तित्व, शरीर, स्वास्थ्य, रूप-रंग और जीवनशक्ति' },
    { n: 2, en: 'Dhanesh',    hi: 'धनेश',
      sig_en: 'Wealth, Family, Speech, Food, Early Education, Face, and Accumulated Assets',
      sig_hi: 'धन, परिवार, वाणी, भोजन, प्रारंभिक शिक्षा, मुख और संचित संपत्ति' },
    { n: 3, en: 'Sahajesh',   hi: 'सहजेश',
      sig_en: 'Courage, Siblings, Communication, Short Travels, Hands, Skills, and Media',
      sig_hi: 'साहस, भाई-बहन, संचार, लघु यात्राएं, हस्त कौशल और मीडिया' },
    { n: 4, en: 'Matresh',    hi: 'मातृश',
      sig_en: 'Mother, Home, Land, Vehicles, Happiness, Education, and Inner Emotional Security',
      sig_hi: 'माता, गृह, भूमि, वाहन, सुख, शिक्षा और आंतरिक भावनात्मक सुरक्षा' },
    { n: 5, en: 'Putresh',    hi: 'पुत्रेश',
      sig_en: 'Children, Intelligence, Creativity, Speculation, Romance, Mantras, and Past-life Merit',
      sig_hi: 'संतान, बुद्धि, रचनात्मकता, सट्टा, प्रेम, मंत्र और पूर्वजन्म के पुण्य' },
    { n: 6, en: 'Ripesh',     hi: 'रिपेश',
      sig_en: 'Enemies, Debts, Diseases, Service, Litigation, Competition, and Daily Routine',
      sig_hi: 'शत्रु, ऋण, रोग, सेवा, मुकदमेबाजी, प्रतिस्पर्धा और दैनिक दिनचर्या' },
    { n: 7, en: 'Kalatresh',  hi: 'कलत्रेश',
      sig_en: 'Marriage, Partnerships, Business, Spouse, Public Image, and Foreign Relations',
      sig_hi: 'विवाह, साझेदारी, व्यापार, जीवनसाथी, सार्वजनिक छवि और विदेशी संबंध' },
    { n: 8, en: 'Ayushesh',   hi: 'आयुषेश',
      sig_en: 'Longevity, Hidden Matters, Inheritance, Occult Sciences, Transformation, and Sudden Events',
      sig_hi: 'आयु, छिपे विषय, विरासत, तंत्र-विज्ञान, रूपांतरण और अचानक घटनाएं' },
    { n: 9, en: 'Dharmesh',   hi: 'धर्मेश',
      sig_en: 'Fortune, Father, Religion, Philosophy, Long Journeys, Higher Learning, and Gurus',
      sig_hi: 'भाग्य, पिता, धर्म, दर्शन, दीर्घ यात्राएं, उच्च शिक्षा और गुरु' },
    { n:10, en: 'Karmesh',    hi: 'कर्मेश',
      sig_en: 'Career, Profession, Status, Authority, Government, Father, and Public Life',
      sig_hi: 'करियर, व्यवसाय, पद, अधिकार, सरकार, पिता और सार्वजनिक जीवन' },
    { n:11, en: 'Labhesh',    hi: 'लाभेश',
      sig_en: 'Gains, Income, Aspirations, Elder Siblings, Friends, Social Networks, and Fulfilment',
      sig_hi: 'लाभ, आय, आकांक्षाएं, बड़े भाई-बहन, मित्र, सामाजिक नेटवर्क और इच्छापूर्ति' },
    { n:12, en: 'Vyayesh',    hi: 'व्ययेश',
      sig_en: 'Loss, Expenditure, Foreign Lands, Isolation, Spirituality, Liberation, and Hidden Enemies',
      sig_hi: 'व्यय, हानि, विदेश, एकांत, आध्यात्मिकता, मोक्ष और छिपे शत्रु' },
  ];

  // ── Quality helper ───────────────────────────────────────────────────────────
  function eff(lord, house) {
    if (house === lord) return 'highly_positive';
    if ([1,5,9].includes(house)) return 'highly_positive';
    if ([4,7,10,11].includes(house)) return 'positive';
    // Viparita Raja Yoga combos get bumped up
    if ((lord===6||lord===8||lord===12) && (house===6||house===8||house===12) && house!==lord)
      return 'positive';
    if ([6,12].includes(house)) return 'negative';
    if (house===8) return 'negative';
    return 'neutral';
  }

  function vry(lord, house) {
    const d = [6,8,12];
    return d.includes(lord) && d.includes(house) && lord !== house;
  }

  // ── Data: [en, hi] per [lord][house]  (12×12) ────────────────────────────────
  // Index: D[lord-1][house-1] = [en, hi]
  const D = [
    // ─── 1st Lord ──────────────────────────────────────────────────────────────
    [
      ['The Lagna lord in the 1st house makes the native self-reliant, physically strong, confident, and endowed with a powerful personality. The native is blessed with good health and a commanding presence.','लग्नेश प्रथम भाव में हो तो जातक आत्मनिर्भर, बलशाली, आत्मविश्वासी और शक्तिशाली व्यक्तित्व वाला होता है। उसका स्वास्थ्य उत्तम रहता है और उसकी उपस्थिति प्रभावशाली होती है।'],
      ['The Lagna lord in the 2nd house gives financial prosperity, love of food and family, good speech, and accumulation of wealth. The native\'s identity is strongly connected to material security.','लग्नेश द्वितीय भाव में हो तो जातक को धन, परिवार, सुभाषिता और संपत्ति संचय का लाभ मिलता है। उसकी पहचान भौतिक सुरक्षा से गहराई से जुड़ी होती है।'],
      ['The Lagna lord in the 3rd house makes the native courageous, communicative, skilled in writing or media, and close to siblings. There is a keen interest in short travels and self-expression.','लग्नेश तृतीय भाव में हो तो जातक साहसी, वाकपटु, लेखन या मीडिया में कुशल और भाई-बहनों से निकट होता है। लघु यात्राओं और अभिव्यक्ति में विशेष रुचि होती है।'],
      ['The Lagna lord in the 4th house blesses the native with domestic happiness, a good mother, landed property, vehicles, and inner peace. The native finds identity in home and homeland.','लग्नेश चतुर्थ भाव में हो तो जातक को पारिवारिक सुख, माता का स्नेह, भूमि-संपत्ति, वाहन और आंतरिक शांति मिलती है। उसकी पहचान गृह और मातृभूमि से जुड़ी होती है।'],
      ['The Lagna lord in the 5th house gives intelligence, creativity, higher education, children, love affairs, and spiritual inclination. The native is artistic and academically inclined.','लग्नेश पंचम भाव में हो तो जातक को बुद्धि, रचनात्मकता, उच्च शिक्षा, संतान सुख, प्रेम और आध्यात्मिक प्रवृत्ति मिलती है। जातक कलात्मक और अकादमिक रूप से प्रतिभाशाली होता है।'],
      ['The Lagna lord in the 6th house creates health challenges, conflicts with enemies, legal disputes, and service-oriented work. However, it can also produce a strong fighter who overcomes all obstacles.','लग्नेश षष्ठ भाव में हो तो जातक को स्वास्थ्य समस्याएं, शत्रुओं से संघर्ष और कानूनी विवाद हो सकते हैं। परंतु यह जातक को एक कठोर योद्धा भी बना सकता है जो सभी बाधाओं पर विजय प्राप्त करता है।'],
      ['The Lagna lord in the 7th house emphasises marriage, partnerships, and public life. The native\'s identity revolves around relationships. This is favourable for business partnerships and a happy marriage.','लग्नेश सप्तम भाव में हो तो जातक का व्यक्तित्व विवाह, साझेदारी और सार्वजनिक जीवन के इर्द-गिर्द केंद्रित होता है। यह व्यापारिक साझेदारी और सुखी विवाह के लिए शुभ है।'],
      ['The Lagna lord in the 8th house brings sudden changes, occult interests, and transformations in life. The native may face chronic health issues or interest in research, secrets, and mysticism.','लग्नेश अष्टम भाव में हो तो जातक के जीवन में अचानक परिवर्तन, तांत्रिक रुचि और व्यापक रूपांतरण आते हैं। जातक को दीर्घकालिक स्वास्थ्य समस्याएं हो सकती हैं या वह रहस्यविद्या में रुचि रखता है।'],
      ['The Lagna lord in the 9th house is one of the most auspicious placements. The native is fortunate, religious, philosophical, and favoured by father and gurus. Long journeys and spiritual growth are indicated.','लग्नेश नवम भाव में हो तो यह सर्वाधिक शुभ स्थितियों में से एक है। जातक भाग्यशाली, धार्मिक, दार्शनिक और पिता-गुरु की कृपा पाने वाला होता है। दीर्घ यात्राएं और आध्यात्मिक उन्नति भी होती है।'],
      ['The Lagna lord in the 10th house gives a strong career, high status, fame, and authority. The native achieves great success through hard work and leadership. Rajayoga potential is very high.','लग्नेश दशम भाव में हो तो जातक को उत्कृष्ट करियर, उच्च पद, यश और अधिकार मिलते हैं। जातक परिश्रम और नेतृत्व से असाधारण सफलता प्राप्त करता है। राजयोग की प्रबल संभावना होती है।'],
      ['The Lagna lord in the 11th house produces gains, fulfilment of desires, large social network, and elder siblings\' support. Financial gains through networking and group activities are prominent.','लग्नेश एकादश भाव में हो तो जातक को लाभ, इच्छापूर्ति, विस्तृत सामाजिक नेटवर्क और बड़े भाई-बहनों का सहयोग मिलता है। नेटवर्किंग और सामूहिक गतिविधियों से आर्थिक लाभ विशेष होता है।'],
      ['The Lagna lord in the 12th house causes loss of self, isolation, spiritual liberation, or foreign settlements. The native may struggle with identity and health but finds solace in spiritual practice.','लग्नेश द्वादश भाव में हो तो जातक में आत्म-विलोपन, एकांत प्रियता, मोक्ष प्रवृत्ति या विदेश वास की प्रबल संभावना होती है। जातक पहचान और स्वास्थ्य में संघर्ष करता है, परंतु आध्यात्मिक साधना में सुकून पाता है।'],
    ],

    // ─── 2nd Lord ──────────────────────────────────────────────────────────────
    [
      ['The 2nd lord in the 1st house makes the native attractive, wealthy, and eloquent. The person naturally draws resources and is conscious of physical appearance.','धनेश प्रथम भाव में हो तो जातक आकर्षक, धनाढ्य और वाकपटु होता है। ऐसा व्यक्ति स्वाभाविक रूप से संसाधनों को आकर्षित करता है और शारीरिक रूप-रंग के प्रति सचेत रहता है।'],
      ['The 2nd lord in its own house is excellent for wealth, family harmony, and sweet speech. The native accumulates considerable assets and has a stable family life.','धनेश स्वयं द्वितीय भाव में हो तो यह धन, पारिवारिक सामंजस्य और मधुर वाणी के लिए उत्कृष्ट है। जातक पर्याप्त संपत्ति संचित करता है और उसका पारिवारिक जीवन स्थिर रहता है।'],
      ['The 2nd lord in the 3rd house produces income through communication, writing, media, and short travels. The native earns through siblings and has a persuasive, business-oriented speech.','धनेश तृतीय भाव में हो तो जातक संचार, लेखन, मीडिया और लघु यात्राओं से आय अर्जित करता है। भाई-बहनों से आर्थिक लाभ होता है और वाणी में व्यावसायिक कुशलता होती है।'],
      ['The 2nd lord in the 4th house brings wealth through real estate, agriculture, and mother\'s side. The native has a comfortable home, good vehicles, and emotional security connected to family wealth.','धनेश चतुर्थ भाव में हो तो जातक को संपत्ति, कृषि और माता पक्ष से धन मिलता है। जातक का घर सुखी, वाहन शुभ और पारिवारिक धन से भावनात्मक सुरक्षा मिलती है।'],
      ['The 2nd lord in the 5th house gives gains through speculation, stocks, education, children, and creative arts. The native may earn through entertainment or teaching.','धनेश पंचम भाव में हो तो जातक को सट्टा, शेयर, शिक्षा, संतान और रचनात्मक कलाओं से धन लाभ होता है। जातक मनोरंजन या शिक्षण से आय अर्जित कर सकता है।'],
      ['The 2nd lord in the 6th house leads to expenses on health, loans, and conflicts over money. Wealth may be earned through service, medicine, or legal work, but financial stability requires effort.','धनेश षष्ठ भाव में हो तो जातक को स्वास्थ्य पर व्यय, ऋण और धन संबंधी विवाद होते हैं। जातक सेवा, चिकित्सा या कानूनी कार्य से धन कमा सकता है, परंतु वित्तीय स्थिरता के लिए प्रयास करना पड़ता है।'],
      ['The 2nd lord in the 7th house brings income through partnerships, spouse\'s wealth, and business dealings. The spouse may be financially well-off and contribute significantly to family prosperity.','धनेश सप्तम भाव में हो तो साझेदारी, जीवनसाथी के धन और व्यापारिक लेन-देन से आय होती है। जीवनसाथी आर्थिक रूप से सम्पन्न हो सकता है और पारिवारिक समृद्धि में उल्लेखनीय योगदान करता है।'],
      ['The 2nd lord in the 8th house causes sudden financial gains or losses, inheritance, insurance, and hidden wealth. The native may deal with other people\'s money or have an erratic financial life.','धनेश अष्टम भाव में हो तो जातक को अचानक आर्थिक लाभ-हानि, विरासत, बीमा और छिपी संपत्ति की प्राप्ति होती है। जातक परकीय धन से संबंधित कार्यों में संलग्न हो सकता है और उसकी आर्थिक स्थिति अनिश्चित रह सकती है।'],
      ['The 2nd lord in the 9th house brings wealth from father, foreign lands, religious institutions, publishing, and higher education. The native is philosophically inclined and earns ethically.','धनेश नवम भाव में हो तो पिता, विदेश, धार्मिक संस्थाओं, प्रकाशन और उच्च शिक्षा से धन की प्राप्ति होती है। जातक दार्शनिक प्रवृत्ति का होता है और नैतिक तरीकों से आय अर्जित करता है।'],
      ['The 2nd lord in the 10th house produces earnings through career, government, and public status. The native\'s profession directly supports financial growth and family well-being.','धनेश दशम भाव में हो तो जातक करियर, सरकार और सार्वजनिक पद से धन अर्जित करता है। उसका व्यवसाय सीधे आर्थिक विकास और पारिवारिक कल्याण को समर्थन देता है।'],
      ['The 2nd lord in the 11th house is highly favourable for wealth accumulation, gains from elder siblings, large social circles, and fulfilment of financial goals.','धनेश एकादश भाव में हो तो यह धन संचय, बड़े भाई-बहनों से लाभ, विस्तृत सामाजिक दायरे और आर्थिक लक्ष्यों की पूर्ति के लिए अत्यंत शुभ है।'],
      ['The 2nd lord in the 12th house causes financial expenditures, loss of wealth, and possible foreign earnings. Money may flow out as quickly as it comes; foreign trade or spiritual spending is common.','धनेश द्वादश भाव में हो तो आर्थिक व्यय, धन हानि और संभावित विदेशी आय होती है। धन उतनी ही तेजी से चला जाता है जितनी जल्दी आता है; विदेश व्यापार या आध्यात्मिक व्यय सामान्य है।'],
    ],

    // ─── 3rd Lord ──────────────────────────────────────────────────────────────
    [
      ['The 3rd lord in the 1st house makes the native courageous, communicative, skilled with hands, and inclined towards sports and media. Sibling relationships strongly influence the personality.','तृतीयेश प्रथम भाव में हो तो जातक साहसी, संचारशील, हस्त-कुशल और खेल-मीडिया में रुचि रखने वाला होता है। भाई-बहनों का व्यक्तित्व पर गहरा प्रभाव होता है।'],
      ['The 3rd lord in the 2nd house links communication and siblings with wealth and family speech. The native may earn through writing, trading, or voice-related professions.','तृतीयेश द्वितीय भाव में हो तो संचार और भाई-बहनों का संबंध धन और पारिवारिक वाणी से बन जाता है। जातक लेखन, व्यापार या वाणी-संबंधी व्यवसायों से आय अर्जित कर सकता है।'],
      ['The 3rd lord in its own house powerfully strengthens courage, communication, sibling bonds, and self-expression. The native may excel in writing, journalism, or performing arts.','तृतीयेश स्वयं तृतीय भाव में हो तो साहस, संचार, भाई-बहन के बंधन और आत्म-अभिव्यक्ति प्रबल होती है। जातक लेखन, पत्रकारिता या प्रदर्शन कलाओं में उत्कृष्ट हो सकता है।'],
      ['The 3rd lord in the 4th house brings courage and skills into the domestic sphere. The native is protective of home and mother, and may work in real estate, hospitality, or home-based business.','तृतीयेश चतुर्थ भाव में हो तो साहस और कौशल का केंद्र गृह जीवन बन जाता है। जातक घर और माता का रक्षक होता है और संपत्ति, आतिथ्य या घर-आधारित व्यवसाय में कार्य कर सकता है।'],
      ['The 3rd lord in the 5th house combines communication skills with creativity, speculation, and children. The native may be a skilled writer of fiction, a performing artist, or an educator.','तृतीयेश पंचम भाव में हो तो संचार कौशल का मिलाप रचनात्मकता, सट्टे और संतान से होता है। जातक कुशल कथा-लेखक, प्रदर्शन कलाकार या शिक्षक हो सकता है।'],
      ['The 3rd lord in the 6th house creates conflicts with siblings, health issues related to hands or lungs, and competition in communication-based fields. The native fights hard and may work in healthcare or law.','तृतीयेश षष्ठ भाव में हो तो भाई-बहनों से मतभेद, हाथ या फेफड़ों संबंधी स्वास्थ्य समस्याएं और संचार क्षेत्रों में प्रतिस्पर्धा होती है। जातक कठोर संघर्षशील होता है और स्वास्थ्य सेवा या कानून में कार्यरत हो सकता है।'],
      ['The 3rd lord in the 7th house gives a communicative and skilled partner. Business success comes through partnerships in media, trade, or technology.','तृतीयेश सप्तम भाव में हो तो जीवनसाथी संचारशील और कुशल होता है। मीडिया, व्यापार या प्रौद्योगिकी में साझेदारी से व्यावसायिक सफलता मिलती है।'],
      ['The 3rd lord in the 8th house creates sudden events involving siblings, secretive communications, research, and interest in hidden knowledge. The native is resilient but may face unexpected setbacks.','तृतीयेश अष्टम भाव में हो तो भाई-बहनों से जुड़ी अचानक घटनाएं, गुप्त संचार, अनुसंधान और छिपे ज्ञान में रुचि होती है। जातक लचीला होता है, परंतु अप्रत्याशित झटकों का सामना करना पड़ सकता है।'],
      ['The 3rd lord in the 9th house brings courage into philosophy, religion, and long journeys. The native travels widely, writes about spirituality, or becomes a religious communicator.','तृतीयेश नवम भाव में हो तो साहस का रुझान दर्शन, धर्म और दीर्घ यात्राओं की ओर होता है। जातक व्यापक यात्राएं करता है, आध्यात्मिकता पर लिखता है, या धार्मिक संचारक बनता है।'],
      ['The 3rd lord in the 10th house produces a career in media, communication, writing, or technology. The native achieves public recognition through courageous professional actions.','तृतीयेश दशम भाव में हो तो मीडिया, संचार, लेखन या प्रौद्योगिकी में करियर बनता है। जातक साहसी व्यावसायिक कार्यों से सार्वजनिक ख्याति प्राप्त करता है।'],
      ['The 3rd lord in the 11th house brings gains through siblings, communication, and networking. The native achieves goals via media ventures, social groups, and group communications.','तृतीयेश एकादश भाव में हो तो भाई-बहनों, संचार और नेटवर्किंग से लाभ होता है। जातक मीडिया उद्यमों, सामाजिक समूहों और सामूहिक संचार के माध्यम से लक्ष्य प्राप्त करता है।'],
      ['The 3rd lord in the 12th house causes distance from siblings, expenses on travels, and communication about spirituality or foreign matters. The native may write about secret or spiritual topics.','तृतीयेश द्वादश भाव में हो तो भाई-बहनों से दूरी, यात्राओं पर व्यय और आध्यात्मिकता या विदेशी विषयों पर संचार होता है। जातक गुप्त या आध्यात्मिक विषयों पर लिख सकता है।'],
    ],

    // ─── 4th Lord ──────────────────────────────────────────────────────────────
    [
      ['The 4th lord in the 1st house makes the native emotionally expressive, attached to home, and deeply connected to mother. The native carries the energy of the family in their personality.','मातृश प्रथम भाव में हो तो जातक भावनात्मक रूप से अभिव्यक्तिशील, घर से जुड़ा और माता से गहराई से संबंधित होता है। जातक अपने व्यक्तित्व में पारिवारिक ऊर्जा लेकर चलता है।'],
      ['The 4th lord in the 2nd house brings family wealth, ancestral property, and land. The native accumulates wealth through real estate and is nourished by family traditions.','मातृश द्वितीय भाव में हो तो पारिवारिक धन, पैतृक संपत्ति और भूमि की प्राप्ति होती है। जातक अचल संपत्ति से धन संचित करता है और पारिवारिक परंपराओं से पोषित होता है।'],
      ['The 4th lord in the 3rd house creates courage in domestic affairs and short travels. The native may work in real estate communication, home improvement, or have a sibling closely connected to property.','मातृश तृतीय भाव में हो तो घरेलू मामलों और लघु यात्राओं में साहस आता है। जातक संपत्ति-संचार, गृह सुधार में कार्यरत हो सकता है या किसी भाई-बहन का संपत्ति से गहरा संबंध होता है।'],
      ['The 4th lord in its own house is excellent — it gives domestic happiness, a loving mother, a beautiful home, vehicles, and deep emotional contentment. The native is rooted and emotionally stable.','मातृश स्वयं चतुर्थ भाव में हो तो यह उत्कृष्ट स्थिति है — गृह सुख, स्नेहमयी माता, सुंदर घर, वाहन और गहरी भावनात्मक संतुष्टि मिलती है। जातक स्थिर और भावनात्मक रूप से संतुलित होता है।'],
      ['The 4th lord in the 5th house creates happiness through children and home-based creative activities. The native finds deep emotional fulfilment in teaching, arts, and relationship with children.','मातृश पंचम भाव में हो तो जातक को संतान, रचनात्मक गतिविधियों और शिक्षा से सुख मिलता है। जातक शिक्षण, कला और बच्चों के साथ संबंध में गहरी भावनात्मक संतुष्टि पाता है।'],
      ['The 4th lord in the 6th house may create issues with mother\'s health, domestic disputes, or loss of property. The native may also be employed in healthcare, real estate maintenance, or household services.','मातृश षष्ठ भाव में हो तो माता के स्वास्थ्य में समस्याएं, घरेलू विवाद या संपत्ति हानि हो सकती है। परंतु जातक स्वास्थ्य सेवा, संपत्ति रख-रखाव या घरेलू सेवाओं में कार्यरत भी हो सकता है।'],
      ['The 4th lord in the 7th house brings domestic happiness through marriage. The native seeks a partner who provides emotional security and a comfortable home life. Foreign settlement through marriage is possible.','मातृश सप्तम भाव में हो तो विवाह के माध्यम से गृह सुख की प्राप्ति होती है। जातक ऐसा साथी ढूंढता है जो भावनात्मक सुरक्षा और सुखी घरेलू जीवन प्रदान करे। विवाह के माध्यम से विदेश वास की संभावना है।'],
      ['The 4th lord in the 8th house creates sudden changes in home life, mother\'s health challenges, and hidden property. The native may inherit land but face family instability or ancestral secrets.','मातृश अष्टम भाव में हो तो गृह जीवन में अचानक परिवर्तन, माता के स्वास्थ्य में संकट और गुप्त संपत्ति होती है। जातक को भूमि की विरासत मिल सकती है, परंतु पारिवारिक अस्थिरता या पैतृक रहस्यों का सामना करना पड़ सकता है।'],
      ['The 4th lord in the 9th house brings a spiritual or highly educated mother, and the native finds emotional peace through religion, philosophy, and long pilgrimages. Ancestral land in foreign places is possible.','मातृश नवम भाव में हो तो माता आध्यात्मिक या उच्च शिक्षित होती है। जातक धर्म, दर्शन और तीर्थ यात्राओं में भावनात्मक शांति पाता है। विदेश में पैतृक भूमि की संभावना भी है।'],
      ['The 4th lord in the 10th house creates a strong connection between career and home. The native works in real estate, family business, or from home. Mother\'s influence on profession is significant.','मातृश दशम भाव में हो तो करियर और गृह जीवन के बीच मजबूत संबंध बनता है। जातक संपत्ति, पारिवारिक व्यवसाय या घर से काम करता है। माता का व्यवसाय पर महत्वपूर्ण प्रभाव होता है।'],
      ['The 4th lord in the 11th house brings gains through land, mother\'s network, and real estate. The native achieves aspirations related to domestic happiness and comfortable living.','मातृश एकादश भाव में हो तो भूमि, माता के नेटवर्क और संपत्ति से लाभ होता है। जातक गृह सुख और आरामदायक जीवन से संबंधित आकांक्षाएं पूरी करता है।'],
      ['The 4th lord in the 12th house indicates loss of property, separation from mother, or foreign settlement with land. The native finds emotional peace through isolation, retreat, or living abroad.','मातृश द्वादश भाव में हो तो संपत्ति हानि, माता से वियोग या विदेश में भूमि की संभावना होती है। जातक एकांत, साधना या विदेश वास में भावनात्मक शांति पाता है।'],
    ],

    // ─── 5th Lord ──────────────────────────────────────────────────────────────
    [
      ['The 5th lord in the 1st house makes the native highly intelligent, creative, and child-like in their enthusiasm. They are natural teachers and are admired for their intellect.','पुत्रेश प्रथम भाव में हो तो जातक अत्यधिक बुद्धिमान, रचनात्मक और अपने उत्साह में बाल-सुलभ होता है। वे स्वाभाविक शिक्षक होते हैं और अपनी बुद्धि के लिए सराहे जाते हैं।'],
      ['The 5th lord in the 2nd house creates wealth through intelligence, children\'s contributions, and creative pursuits. The native has an educated, creative family background.','पुत्रेश द्वितीय भाव में हो तो बुद्धि, संतान के योगदान और रचनात्मक प्रयासों से धन की प्राप्ति होती है। जातक का पारिवारिक वातावरण शिक्षित और रचनात्मक होता है।'],
      ['The 5th lord in the 3rd house blends creativity with communication and courage. The native may be a writer, artist, or performer, and benefits greatly from sibling support in creative endeavours.','पुत्रेश तृतीय भाव में हो तो रचनात्मकता का संचार और साहस के साथ मेल होता है। जातक लेखक, कलाकार या अभिनेता हो सकता है और रचनात्मक प्रयासों में भाई-बहनों के समर्थन से बहुत लाभ होता है।'],
      ['The 5th lord in the 4th house brings happiness through children and home-based creative activities. The native may teach at home, invest in education infrastructure, or have a deeply intellectual domestic environment.','पुत्रेश चतुर्थ भाव में हो तो संतान और घर-आधारित रचनात्मक गतिविधियों से सुख मिलता है। जातक घर पर पढ़ाई सिखा सकता है, शैक्षिक बुनियादी ढांचे में निवेश कर सकता है, या उसका घरेलू वातावरण गहराई से बौद्धिक हो सकता है।'],
      ['The 5th lord in its own house greatly empowers intelligence, romance, children, and spiritual practice. The native is blessed with gifted children, sharp intellect, and good luck.','पुत्रेश स्वयं पंचम भाव में हो तो बुद्धि, प्रेम, संतान और आध्यात्मिक साधना अत्यधिक प्रबल होती है। जातक पंचम भाव के समस्त कारकत्वों से सम्पन्न होता है: प्रतिभाशाली संतान, तीक्ष्ण बुद्धि और सौभाग्य।'],
      ['The 5th lord in the 6th house creates challenges in romance, children, and education. The native may face obstacles in having children or struggle in academic pursuits, but can succeed in competitive exams.','पुत्रेश षष्ठ भाव में हो तो प्रेम, संतान और शिक्षा में चुनौतियाँ होती हैं। जातक को संतान प्राप्ति में बाधाएं आ सकती हैं या शैक्षणिक प्रयासों में संघर्ष हो सकता है, परंतु प्रतिस्पर्धी परीक्षाओं में सफलता मिल सकती है।'],
      ['The 5th lord in the 7th house brings romance into marriage. The native marries for love and has an intellectually compatible partner. Business and speculative investments with spouse are common.','पुत्रेश सप्तम भाव में हो तो विवाह में प्रेम का समावेश होता है। जातक प्रेम-विवाह करता है और उसका जीवनसाथी बौद्धिक रूप से अनुकूल होता है। जीवनसाथी के साथ व्यापारिक और सट्टे संबंधी निवेश सामान्य होते हैं।'],
      ['The 5th lord in the 8th house creates interest in occult sciences, mystical subjects, and deep research. The native may face challenges with children but has profound spiritual wisdom and intuition.','पुत्रेश अष्टम भाव में हो तो तंत्र-विज्ञान, रहस्यमय विषयों और गहन शोध में रुचि होती है। जातक को संतान संबंधी चुनौतियाँ हो सकती हैं, परंतु उसके पास गहरी आध्यात्मिक बुद्धि और अंतर्ज्ञान होता है।'],
      ['The 5th lord in the 9th house (two trines meeting) is one of the most auspicious combinations, creating a Dharma-Karmadhipati Yoga. The native is learned, virtuous, spiritually evolved, and blessed with excellent children.','पुत्रेश नवम भाव में हो तो (दो त्रिकोणों का मिलन) यह धर्म-कर्माधिपति योग बनाने वाली अत्यंत शुभ संयोजनों में से एक है। जातक विद्वान, धर्मात्मा, आध्यात्मिक रूप से उन्नत और उत्कृष्ट संतान से सम्पन्न होता है।'],
      ['The 5th lord in the 10th house creates a career in education, entertainment, arts, or speculation. The native gains fame through intellectual or creative pursuits and may become a well-known educator or artist.','पुत्रेश दशम भाव में हो तो शिक्षा, मनोरंजन, कला या सट्टे में करियर बनता है। जातक बौद्धिक या रचनात्मक प्रयासों से प्रसिद्धि प्राप्त करता है और एक प्रसिद्ध शिक्षक या कलाकार बन सकता है।'],
      ['The 5th lord in the 11th house brings gains through speculation, children\'s success, and creative ventures. The native is highly intelligent in financial matters and achieves aspirations through knowledge.','पुत्रेश एकादश भाव में हो तो सट्टे, संतान की सफलता और रचनात्मक उद्यमों से लाभ होता है। जातक वित्तीय मामलों में अत्यधिक बुद्धिमान होता है और ज्ञान के माध्यम से आकांक्षाएं पूर्ण करता है।'],
      ['The 5th lord in the 12th house indicates expense through children, separation from children, or children living abroad. The native may have spiritual children or deep interest in meditation and mantra practices.','पुत्रेश द्वादश भाव में हो तो संतान पर व्यय, संतान से वियोग या संतान का विदेश वास होता है। जातक की संतान आध्यात्मिक हो सकती है या जातक को ध्यान और मंत्र साधना में गहरी रुचि हो सकती है।'],
    ],

    // ─── 6th Lord ──────────────────────────────────────────────────────────────
    [
      ['The 6th lord in the 1st house may cause health issues, conflicts with enemies, and a combative personality. However, the native is a powerful fighter who overcomes opposition and thrives in competitive fields.','रिपेश प्रथम भाव में हो तो स्वास्थ्य समस्याएं, शत्रुओं से संघर्ष और लड़ाकू स्वभाव हो सकता है। परंतु जातक एक शक्तिशाली योद्धा होता है जो विपक्ष पर विजय प्राप्त करता है और प्रतिस्पर्धी क्षेत्रों में फलता-फूलता है।'],
      ['The 6th lord in the 2nd house creates expenses on health and legal matters, and possible debts. Family conflicts over money are likely. However, income from healthcare or legal professions is also indicated.','रिपेश द्वितीय भाव में हो तो स्वास्थ्य और कानूनी मामलों पर व्यय तथा संभावित ऋण होता है। धन को लेकर पारिवारिक संघर्ष की संभावना है। परंतु स्वास्थ्य सेवा या कानूनी व्यवसायों से आय भी संकेतित है।'],
      ['The 6th lord in the 3rd house creates conflicts with siblings and competitive communication. The native may write about legal, medical, or social issues. Siblings may cause problems.','रिपेश तृतीय भाव में हो तो भाई-बहनों से विवाद और प्रतिस्पर्धी संचार होता है। जातक कानूनी, चिकित्सा या सामाजिक मुद्दों पर लिख सकता है। भाई-बहन समस्याएं उत्पन्न कर सकते हैं।'],
      ['The 6th lord in the 4th house may create domestic conflicts, mother\'s health issues, or property disputes. The native may work in healthcare at home or face competitive situations in family.','रिपेश चतुर्थ भाव में हो तो घरेलू संघर्ष, माता के स्वास्थ्य में समस्याएं या संपत्ति विवाद हो सकते हैं। जातक घर पर स्वास्थ्य सेवा कार्य कर सकता है या परिवार में प्रतिस्पर्धी परिस्थितियों का सामना कर सकता है।'],
      ['The 6th lord in the 5th house affects children, education, and romance with disease or conflict energy. The native may work in competitive education, sports training, or deal with health issues of children.','रिपेश पंचम भाव में हो तो संतान, शिक्षा और प्रेम पर रोग या संघर्ष ऊर्जा का प्रभाव पड़ता है। जातक प्रतिस्पर्धी शिक्षा, खेल प्रशिक्षण में कार्य कर सकता है या संतान के स्वास्थ्य की समस्याओं से निपट सकता है।'],
      ['The 6th lord in its own house is powerful for defeating enemies, winning legal battles, and overcoming diseases. The native is resilient and highly competitive. This can create powerful Viparita Raja Yoga.','रिपेश स्वयं षष्ठ भाव में हो तो शत्रुओं पर विजय, कानूनी लड़ाइयाँ जीतना और रोगों पर काबू पाने के लिए शक्तिशाली है। जातक लचीला, सेवा-उन्मुख और अत्यधिक प्रतिस्पर्धी होता है। यह शक्तिशाली विपरीत राज योग बना सकता है।'],
      ['The 6th lord in the 7th house creates conflicts in marriage, disputes with partners, and health issues of spouse. Legal battles involving business partnerships are common. Marriage may be service-oriented or medical professional.','रिपेश सप्तम भाव में हो तो विवाह में संघर्ष, साझेदारों से विवाद और जीवनसाथी के स्वास्थ्य की समस्याएं होती हैं। व्यावसायिक साझेदारियों से जुड़े कानूनी विवाद सामान्य हैं। जीवनसाथी सेवा-उन्मुख या चिकित्सा पेशेवर हो सकता है।'],
      ['The 6th lord in the 8th house (Dusthana to Dusthana) creates a Viparita Raja Yoga, making the native rise after great adversity. The native overcomes chronic diseases and defeats hidden enemies through transformation.','रिपेश अष्टम भाव में हो तो (दुष्टस्थान से दुष्टस्थान) विपरीत राज योग बनता है, जिससे जातक महान प्रतिकूलता के बाद उठता है। जातक दीर्घकालिक बीमारियों पर काबू पाता है और रूपांतरण के माध्यम से छिपे शत्रुओं को परास्त करता है।'],
      ['The 6th lord in the 9th house creates conflict between dharma and daily duties. The native may face legal issues with father, gurus, or religious institutions. Service in spiritual or healing professions abroad is possible.','रिपेश नवम भाव में हो तो धर्म और दैनिक कर्तव्यों के बीच संघर्ष होता है। जातक को पिता, गुरुओं या धार्मिक संस्थाओं के साथ कानूनी समस्याएं हो सकती हैं। परंतु विदेश में आध्यात्मिक या उपचार व्यवसायों में सेवा भी संभव है।'],
      ['The 6th lord in the 10th house gives a career in service, medicine, military, law enforcement, or conflict resolution. The native is diligent and rises in career through hard work and overcoming competition.','रिपेश दशम भाव में हो तो सेवा, चिकित्सा, सेना, कानून प्रवर्तन या संघर्ष समाधान में करियर बनता है। जातक परिश्रमी, सटीक होता है और कड़ी मेहनत तथा प्रतिस्पर्धा पर काबू पाकर करियर में उठता है।'],
      ['The 6th lord in the 11th house brings gains through service, healthcare, or legal work. Income from enemies (defeating them) or working in competitive groups is possible. Friendships may involve rivals.','रिपेश एकादश भाव में हो तो सेवा, स्वास्थ्य सेवा या कानूनी कार्य से लाभ होता है। शत्रुओं से (उन्हें हराकर) या प्रतिस्पर्धी समूहों में काम करके आय संभव है। मित्रता में प्रतिद्वंद्वी शामिल हो सकते हैं।'],
      ['The 6th lord in the 12th house (Dusthana to Dusthana) forms another Viparita Raja Yoga. Enemies destroy each other, debts are settled, and health issues resolve over time. The native triumphs over all adversaries.','रिपेश द्वादश भाव में हो तो (दुष्टस्थान से दुष्टस्थान) एक और विपरीत राज योग बनता है। शत्रु एक-दूसरे को नष्ट करते हैं, ऋण चुकाए जाते हैं और स्वास्थ्य समस्याएं समय के साथ हल होती हैं। जातक सभी प्रतिद्वंद्वियों पर विजय प्राप्त करता है।'],
    ],

    // ─── 7th Lord ──────────────────────────────────────────────────────────────
    [
      ['The 7th lord in the 1st house makes the native relationship-oriented, socially charming, and dependent on partnerships for identity. Marriage and business partnerships profoundly shape the personality.','कलत्रेश प्रथम भाव में हो तो जातक संबंध-उन्मुख, सामाजिक रूप से आकर्षक होता है और पहचान के लिए साझेदारी पर निर्भर रहता है। विवाह और व्यापारिक साझेदारियां व्यक्तित्व को गहराई से आकार देती हैं।'],
      ['The 7th lord in the 2nd house brings wealth through marriage, business, and public dealings. The spouse contributes significantly to family wealth. The native earns through trading, law, or diplomacy.','कलत्रेश द्वितीय भाव में हो तो विवाह, व्यापार और सार्वजनिक व्यवहार से धन की प्राप्ति होती है। जीवनसाथी पारिवारिक धन में महत्वपूर्ण योगदान करता है। जातक व्यापार, कानून या कूटनीति से कमाता है।'],
      ['The 7th lord in the 3rd house gives a communicative and skilled partner. Business success comes through communication, media, and travel. Sibling\'s partner or business with brothers is indicated.','कलत्रेश तृतीय भाव में हो तो जीवनसाथी संचारशील और कुशल होता है। संचार, मीडिया और यात्रा के माध्यम से व्यावसायिक सफलता मिलती है। भाई की साझेदारी या भाइयों के साथ व्यापार संकेतित है।'],
      ['The 7th lord in the 4th house brings domestic happiness through marriage. The spouse is deeply connected to home and mother. Real estate business with partners is favoured.','कलत्रेश चतुर्थ भाव में हो तो विवाह के माध्यम से गृह सुख मिलता है। जीवनसाथी घर और माता से गहराई से जुड़ा होता है। साझेदारों के साथ संपत्ति व्यवसाय अनुकूल है।'],
      ['The 7th lord in the 5th house gives a love marriage, an intelligent and creative partner, and happiness through children born in wedlock. Romance and business speculation are intertwined.','कलत्रेश पंचम भाव में हो तो प्रेम विवाह, बुद्धिमान और रचनात्मक जीवनसाथी, और विवाह में जन्मी संतान से सुख मिलता है। प्रेम और व्यापारिक सट्टा आपस में जुड़े होते हैं।'],
      ['The 7th lord in the 6th house creates marital conflicts, health challenges for the spouse, and disputes with business partners. Legal battles in marriage or business are possible.','कलत्रेश षष्ठ भाव में हो तो वैवाहिक संघर्ष, जीवनसाथी के स्वास्थ्य की चुनौतियाँ और व्यावसायिक साझेदारों से विवाद होता है। विवाह या व्यापार में कानूनी लड़ाइयाँ संभव हैं।'],
      ['The 7th lord in its own house strengthens marriage, partnerships, and public relationships. The native attracts a strong, loving spouse and excels in business or diplomatic roles.','कलत्रेश स्वयं सप्तम भाव में हो तो विवाह, साझेदारी और सार्वजनिक संबंध प्रबल होते हैं। जातक एक मजबूत, प्रेमपूर्ण जीवनसाथी को आकर्षित करता है और व्यापार या कूटनीतिक भूमिकाओं में उत्कृष्ट रहता है।'],
      ['The 7th lord in the 8th house creates sudden changes in marriage — transformation, separation, or a mysterious and secretive partner. The spouse may be involved in research, occult, or inherited wealth.','कलत्रेश अष्टम भाव में हो तो विवाह में अचानक परिवर्तन — रूपांतरण, अलगाव, या रहस्यमय और गुप्त जीवनसाथी होता है। जीवनसाथी शोध, तंत्र-विद्या या विरासत के धन से जुड़ा हो सकता है।'],
      ['The 7th lord in the 9th house brings a fortunate, educated, and dharmic partner. The native may marry a foreigner or meet their partner on long travels. Business partnerships with foreign connections prosper.','कलत्रेश नवम भाव में हो तो भाग्यशाली, शिक्षित और धार्मिक जीवनसाथी मिलता है। जातक किसी विदेशी से विवाह कर सकता है या दीर्घ यात्राओं पर अपना साथी मिल सकता है। विदेशी संबंधों के साथ व्यावसायिक साझेदारियाँ फलती-फूलती हैं।'],
      ['The 7th lord in the 10th house creates a professional partner or career in public relations, diplomacy, and business. Marriage may come through profession or the spouse significantly helps the native\'s career.','कलत्रेश दशम भाव में हो तो पेशेवर साझेदार मिलता है या जनसंपर्क, कूटनीति और व्यापार में करियर बनता है। विवाह पेशे के माध्यम से हो सकता है या जीवनसाथी जातक के करियर में महत्वपूर्ण सहायता करता है।'],
      ['The 7th lord in the 11th house brings financial gains through marriage, business, and social networks. The spouse is a great friend and ally. Business partnerships result in abundant profits.','कलत्रेश एकादश भाव में हो तो विवाह, व्यापार और सामाजिक नेटवर्क से आर्थिक लाभ होता है। जीवनसाथी एक महान मित्र और सहयोगी होता है। व्यावसायिक साझेदारियाँ प्रचुर लाभ लाती हैं।'],
      ['The 7th lord in the 12th house brings a foreign-born spouse, bed pleasures, or separation in marriage. The native may settle abroad after marriage. There can be spiritual or secluded partnerships.','कलत्रेश द्वादश भाव में हो तो विदेशी जीवनसाथी, शयन सुख या विवाह में अलगाव होता है। जातक विवाह के बाद विदेश में बस सकता है। आध्यात्मिक या एकांत साझेदारियाँ हो सकती हैं।'],
    ],

    // ─── 8th Lord ──────────────────────────────────────────────────────────────
    [
      ['The 8th lord in the 1st house brings sudden events in the native\'s life, possible chronic health issues, and a deep, mysterious personality. However, the native is resilient and has strong regenerative power.','आयुषेश प्रथम भाव में हो तो जातक के जीवन में अचानक घटनाएं, संभावित दीर्घकालिक स्वास्थ्य समस्याएं और गहरा, रहस्यमय व्यक्तित्व होता है। परंतु जातक लचीला होता है और उसमें प्रबल पुनर्जीवन शक्ति होती है।'],
      ['The 8th lord in the 2nd house creates sudden gains or losses of wealth, inheritance money, and unpredictable family situations. The native may inherit family secrets along with assets.','आयुषेश द्वितीय भाव में हो तो धन का अचानक लाभ-हानि, विरासत की राशि और अप्रत्याशित पारिवारिक परिस्थितियाँ होती हैं। जातक को संपत्ति के साथ-साथ पारिवारिक रहस्य भी विरासत में मिल सकते हैं।'],
      ['The 8th lord in the 3rd house creates sudden events involving siblings and risky short travels. The native is bold, willing to take risks, and may be interested in investigative journalism or extreme sports.','आयुषेश तृतीय भाव में हो तो भाई-बहनों से जुड़ी अचानक घटनाएं और जोखिम भरी लघु यात्राएं होती हैं। जातक साहसी, जोखिम लेने वाला होता है और खोजी पत्रकारिता या अत्यधिक खेलों में रुचि हो सकती है।'],
      ['The 8th lord in the 4th house brings sudden disruptions in home, mother\'s health challenges, or secret property matters. Ancestral property may be inherited but with complications.','आयुषेश चतुर्थ भाव में हो तो घर में अचानक व्यवधान, माता के स्वास्थ्य में संकट या गुप्त संपत्ति के मामले होते हैं। पैतृक संपत्ति विरासत में मिल सकती है, परंतु जटिलताओं के साथ।'],
      ['The 8th lord in the 5th house creates sudden and transformative events involving children and education. The native has deep occult knowledge and interest in tantra, mysticism, and speculative risks.','आयुषेश पंचम भाव में हो तो संतान और शिक्षा से जुड़ी अचानक और परिवर्तनकारी घटनाएं होती हैं। जातक को गहरी तांत्रिक जानकारी और तंत्र, रहस्यवाद और सट्टेबाजी के जोखिमों में रुचि होती है।'],
      ['The 8th lord in the 6th house creates sudden health crises but also strong recovery power. The native may deal with chronic diseases professionally and is excellent at defeating enemies through sudden tactics.','आयुषेश षष्ठ भाव में हो तो अचानक स्वास्थ्य संकट, परंतु शक्तिशाली पुनर्प्राप्ति शक्ति भी होती है। जातक पेशेवर रूप से दीर्घकालिक बीमारियों से निपट सकता है और अचानक रणनीतियों से शत्रुओं को परास्त करने में उत्कृष्ट होता है।'],
      ['The 8th lord in the 7th house creates transformation in marriage and partnerships. The spouse may be secretive, involved in research, or bring sudden changes. Marital life may be intense or unconventional.','आयुषेश सप्तम भाव में हो तो विवाह और साझेदारियों में रूपांतरण होता है। जीवनसाथी गुप्त, शोध में संलग्न हो सकता है, या अचानक बदलाव ला सकता है। वैवाहिक जीवन तीव्र या अपरंपरागत हो सकता है।'],
      ['The 8th lord in its own house intensifies interest in the occult, research, and transformative sciences. The native has deep penetrating insight, long life potential, and a profound connection with death and rebirth themes.','आयुषेश स्वयं अष्टम भाव में हो तो तंत्र, अनुसंधान और परिवर्तनकारी विज्ञानों में रुचि तीव्र होती है। जातक में गहरी अंतर्दृष्टि, दीर्घ जीवन की क्षमता और मृत्यु एवं पुनर्जन्म के विषयों से गहरा संबंध होता है।'],
      ['The 8th lord in the 9th house creates sudden transformation through dharma, philosophy, and long journeys. The native may experience sudden changes in religious beliefs or encounter transformative gurus and teachers.','आयुषेश नवम भाव में हो तो धर्म, दर्शन और दीर्घ यात्राओं के माध्यम से अचानक रूपांतरण होता है। जातक की धार्मिक मान्यताओं में अचानक बदलाव हो सकता है या परिवर्तनकारी गुरुओं और शिक्षकों से मुलाकात हो सकती है।'],
      ['The 8th lord in the 10th house may create sudden career upheavals, but also a career in research, investigation, forensics, or occult sciences. The native achieves hidden fame or works in secretive professions.','आयुषेश दशम भाव में हो तो अचानक करियर में उथल-पुथल हो सकती है, परंतु अनुसंधान, जाँच, फोरेंसिक या तंत्र-विज्ञान में भी करियर बनता है। जातक छिपी प्रसिद्धि प्राप्त करता है या गुप्त व्यवसायों में कार्यरत होता है।'],
      ['The 8th lord in the 11th house brings sudden gains from inheritance, insurance, or occult practices. Income from research, mining, or transformative businesses is indicated.','आयुषेश एकादश भाव में हो तो विरासत, बीमा या तांत्रिक प्रथाओं से अचानक लाभ होता है। अनुसंधान, खनन या परिवर्तनकारी व्यवसायों से आय संकेतित है।'],
      ['The 8th lord in the 12th house (Dusthana to Dusthana) forms a Viparita Raja Yoga. The native has a spiritual, transformative life, and rises after great challenges. Moksha and liberation are indicated.','आयुषेश द्वादश भाव में हो तो (दुष्टस्थान से दुष्टस्थान) विपरीत राज योग बनता है। जातक का जीवन आध्यात्मिक और परिवर्तनकारी होता है और महान चुनौतियों के बाद उठता है। मोक्ष और मुक्ति संकेतित है।'],
    ],

    // ─── 9th Lord ──────────────────────────────────────────────────────────────
    [
      ['The 9th lord in the 1st house makes the native fortunate, philosophical, religious, and respected. The native carries divine grace in their personality and is naturally guided by higher wisdom.','धर्मेश प्रथम भाव में हो तो जातक भाग्यशाली, दार्शनिक, धार्मिक और सम्माननीय होता है। जातक के व्यक्तित्व में दैवीय कृपा होती है और वह स्वाभाविक रूप से उच्च ज्ञान द्वारा निर्देशित होता है।'],
      ['The 9th lord in the 2nd house creates wealth through fortune, father\'s resources, publishing, and religion. The native has an educated, virtuous family background and speaks with wisdom and authority.','धर्मेश द्वितीय भाव में हो तो भाग्य, पिता के संसाधनों, प्रकाशन और धर्म से धन की प्राप्ति होती है। जातक का पारिवारिक वातावरण शिक्षित और गुणवान होता है और वह बुद्धि और अधिकार के साथ बोलता है।'],
      ['The 9th lord in the 3rd house makes the native a religious writer, philosophical communicator, or spiritual traveller. Siblings may be religiously inclined. Short travels for spiritual purposes are common.','धर्मेश तृतीय भाव में हो तो जातक धार्मिक लेखक, दार्शनिक संचारक या आध्यात्मिक यात्री बनता है। भाई-बहन धार्मिक प्रवृत्ति के हो सकते हैं। आध्यात्मिक उद्देश्यों के लिए लघु यात्राएं सामान्य हैं।'],
      ['The 9th lord in the 4th house brings happiness through ancestral properties, a religious mother, and a spiritually enriched home environment. The native may worship at home or run a religious establishment.','धर्मेश चतुर्थ भाव में हो तो पैतृक संपत्ति, धार्मिक माता और आध्यात्मिक रूप से समृद्ध घरेलू वातावरण से सुख मिलता है। जातक घर पर पूजा कर सकता है या धार्मिक प्रतिष्ठान चला सकता है।'],
      ['The 9th lord in the 5th house creates a powerful Dharma Trikona Yoga (two trines). The native is scholarly, spiritually evolved, has fortunate children, and excels in philosophy, spirituality, and higher education.','धर्मेश पंचम भाव में हो तो शक्तिशाली धर्म त्रिकोण योग बनता है (दो त्रिकोण)। जातक विद्वान, आध्यात्मिक रूप से उन्नत होता है, उसकी संतान भाग्यशाली होती है और वह दर्शन, आध्यात्मिकता और उच्च शिक्षा में उत्कृष्ट होता है।'],
      ['The 9th lord in the 6th house creates conflict between dharma and daily struggles. The native may face opposition from gurus or father. Working in religious service, healing, or spiritual counselling is common.','धर्मेश षष्ठ भाव में हो तो धर्म और दैनिक संघर्षों के बीच मतभेद होता है। जातक को गुरुओं या पिता से विरोध का सामना करना पड़ सकता है। परंतु धार्मिक सेवा, उपचार या आध्यात्मिक परामर्श में कार्य करना सामान्य है।'],
      ['The 9th lord in the 7th house brings a fortunate, educated, and religiously inclined spouse. Marriage may happen during long travels or to a foreign person. Business partnerships with ethical foundations prosper.','धर्मेश सप्तम भाव में हो तो भाग्यशाली, शिक्षित और धार्मिक प्रवृत्ति वाला जीवनसाथी मिलता है। विवाह दीर्घ यात्राओं के दौरान या किसी विदेशी व्यक्ति से हो सकता है। नैतिक और दार्शनिक आधारों वाली व्यावसायिक साझेदारियाँ फलती-फूलती हैं।'],
      ['The 9th lord in the 8th house creates sudden transformations in belief systems, father\'s health issues, and hidden spiritual practices. The native may inherit from a guru or experience a profound spiritual crisis followed by awakening.','धर्मेश अष्टम भाव में हो तो विश्वास प्रणालियों में अचानक परिवर्तन, पिता के स्वास्थ्य में समस्याएं और छिपी आध्यात्मिक साधनाएं होती हैं। जातक को गुरु से विरासत मिल सकती है या गहन आध्यात्मिक संकट के बाद जागृति का अनुभव हो सकता है।'],
      ['The 9th lord in its own house is ideal for fortune, religion, and philosophical wisdom. The native is a true seeker of truth, blessed by father and gurus, and leads a dharmic, prosperous life.','धर्मेश स्वयं नवम भाव में हो तो भाग्य, धर्म और दार्शनिक बुद्धि के लिए आदर्श स्थिति है। जातक सत्य का वास्तविक साधक होता है, पिता और गुरुओं की कृपा से सम्पन्न होता है और धार्मिक, समृद्ध जीवन जीता है।'],
      ['The 9th lord in the 10th house creates a powerful Dharma-Karma Adhipati Yoga. The native achieves fame and high status through dharmic actions, teaching, law, or spiritual leadership.','धर्मेश दशम भाव में हो तो शक्तिशाली धर्म-कर्माधिपति योग बनता है। जातक धार्मिक कार्यों, शिक्षण, कानून या आध्यात्मिक नेतृत्व के माध्यम से प्रसिद्धि और उच्च पद प्राप्त करता है।'],
      ['The 9th lord in the 11th house brings gains through fortune, father, and religious networks. The native achieves aspirations through dharmic means and has a large, spiritually oriented social circle.','धर्मेश एकादश भाव में हो तो भाग्य, पिता और धार्मिक नेटवर्क से लाभ होता है। जातक धार्मिक साधनों से आकांक्षाएं पूरी करता है और उसका सामाजिक दायरा बड़ा और आध्यात्मिक रूप से उन्मुख होता है।'],
      ['The 9th lord in the 12th house creates spending on religious pursuits, foreign pilgrimages, and spiritual retreats. The native finds ultimate fortune in letting go of material attachment and pursuing liberation.','धर्मेश द्वादश भाव में हो तो धार्मिक अनुसरण, विदेशी तीर्थाटन और आध्यात्मिक साधनाओं पर व्यय होता है। जातक भौतिक आसक्ति को छोड़ने और मोक्ष की साधना में परम भाग्य पाता है।'],
    ],

    // ─── 10th Lord ─────────────────────────────────────────────────────────────
    [
      ['The 10th lord in the 1st house makes career central to the native\'s identity. The native is ambitious, hard-working, and achieves high status. Professional success defines who they are.','कर्मेश प्रथम भाव में हो तो करियर जातक की पहचान का केंद्र बन जाता है। जातक महत्वाकांक्षी, परिश्रमी होता है और उच्च पद प्राप्त करता है। व्यावसायिक सफलता उसकी पहचान को परिभाषित करती है।'],
      ['The 10th lord in the 2nd house brings career-related wealth and financial stability through profession. Family business or ancestral trade is favoured. The native earns well and supports family generously.','कर्मेश द्वितीय भाव में हो तो करियर से संबंधित धन और व्यवसाय के माध्यम से वित्तीय स्थिरता आती है। पारिवारिक व्यवसाय या पैतृक व्यापार अनुकूल है। जातक अच्छा कमाता है और उदारता से परिवार का पालन-पोषण करता है।'],
      ['The 10th lord in the 3rd house creates a career in communications, media, marketing, or writing. The native is courageous in professional pursuits and benefits from sibling connections in career.','कर्मेश तृतीय भाव में हो तो संचार, मीडिया, विपणन या लेखन में करियर बनता है। जातक व्यावसायिक प्रयासों में साहसी होता है और करियर में भाई-बहन के संपर्कों से लाभ होता है।'],
      ['The 10th lord in the 4th house creates a career in real estate, agriculture, or family business. The native works from home or has a strong connection between career and domestic life. Mother\'s guidance shapes career.','कर्मेश चतुर्थ भाव में हो तो संपत्ति, कृषि या पारिवारिक व्यवसाय में करियर बनता है। जातक घर से काम करता है या करियर और घरेलू जीवन के बीच मजबूत संबंध होता है। माता का मार्गदर्शन करियर को आकार देता है।'],
      ['The 10th lord in the 5th house creates a career in education, arts, entertainment, or finance. The native achieves fame through creative expression. Children may also rise to public prominence.','कर्मेश पंचम भाव में हो तो शिक्षा, कला, मनोरंजन या वित्त में करियर बनता है। जातक रचनात्मक अभिव्यक्ति के माध्यम से प्रसिद्धि प्राप्त करता है। संतान भी सार्वजनिक प्रमुखता तक उठ सकती है।'],
      ['The 10th lord in the 6th house creates a career in service, healthcare, military, or law. The native is dedicated, hardworking, and fights competition fiercely in professional life.','कर्मेश षष्ठ भाव में हो तो सेवा, स्वास्थ्य सेवा, सेना या कानून में करियर बनता है। जातक समर्पित, परिश्रमी होता है और व्यावसायिक जीवन में प्रतिस्पर्धा से कड़ा संघर्ष करता है।'],
      ['The 10th lord in the 7th house creates a career in business, diplomacy, law, or public relations. The native achieves professional success through partnerships and public dealings. Marriage partner supports career.','कर्मेश सप्तम भाव में हो तो व्यापार, कूटनीति, कानून या जनसंपर्क में करियर बनता है। जातक साझेदारियों और सार्वजनिक व्यवहार के माध्यम से व्यावसायिक सफलता प्राप्त करता है। विवाह साथी करियर को समर्थन देता है।'],
      ['The 10th lord in the 8th house creates sudden career transformations, secretive professions, or careers in research, forensics, and occult sciences. The native may have a hidden form of success.','कर्मेश अष्टम भाव में हो तो अचानक करियर में परिवर्तन, गुप्त व्यवसाय, या अनुसंधान, फोरेंसिक और तंत्र-विज्ञान में करियर बनता है। जातक की सफलता का रूप भूमिगत या छिपा हो सकता है।'],
      ['The 10th lord in the 9th house creates a career in law, religion, philosophy, higher education, or publishing. This placement generates a powerful Dharma-Karma Yoga, making the native renowned for righteous conduct.','कर्मेश नवम भाव में हो तो कानून, धर्म, दर्शन, उच्च शिक्षा या प्रकाशन में करियर बनता है। यह स्थिति शक्तिशाली धर्म-कर्म योग उत्पन्न करती है, जो जातक को धार्मिक आचरण के लिए प्रसिद्ध बनाती है।'],
      ['The 10th lord in its own house is a Rajayoga. Career flourishes with the native achieving great authority, fame, and status. Government connections are strong and the native leads in their field.','कर्मेश स्वयं दशम भाव में हो तो यह राजयोग है। करियर फलता-फूलता है और जातक महान अधिकार, प्रसिद्धि और पद प्राप्त करता है। सरकारी संपर्क मजबूत होते हैं और जातक अपने क्षेत्र में नेतृत्व करता है।'],
      ['The 10th lord in the 11th house brings income and gains through career, social networks, and professional recognition. The native achieves long-held ambitions and accumulates wealth through status.','कर्मेश एकादश भाव में हो तो करियर, सामाजिक नेटवर्क और व्यावसायिक पहचान से आय और लाभ होता है। जातक लंबे समय से संजोई महत्वाकांक्षाएं पूरी करता है और पद के माध्यम से धन संचित करता है।'],
      ['The 10th lord in the 12th house creates a career in foreign lands, spiritual organisations, hospitals, prisons, or research institutions. The native may be famous in foreign countries rather than the homeland.','कर्मेश द्वादश भाव में हो तो विदेश, आध्यात्मिक संगठनों, अस्पतालों, जेलों या अनुसंधान संस्थानों में करियर बनता है। जातक मातृभूमि की अपेक्षा विदेशों में अधिक प्रसिद्ध हो सकता है।'],
    ],

    // ─── 11th Lord ─────────────────────────────────────────────────────────────
    [
      ['The 11th lord in the 1st house makes the native social, goal-oriented, and naturally attractive to gains and friends. The native\'s personality brings in wealth and social connections effortlessly.','लाभेश प्रथम भाव में हो तो जातक सामाजिक, लक्ष्य-उन्मुख और स्वाभाविक रूप से लाभ और मित्रों को आकर्षित करने वाला होता है। जातक का व्यक्तित्व सहजता से धन और सामाजिक संपर्क लाता है।'],
      ['The 11th lord in the 2nd house is highly auspicious for wealth. Gains flow directly into the family treasury. Elder siblings or friends contribute to financial prosperity.','लाभेश द्वितीय भाव में हो तो धन के लिए अत्यंत शुभ है। लाभ सीधे पारिवारिक खजाने में आता है। बड़े भाई-बहन या मित्र आर्थिक समृद्धि में योगदान करते हैं।'],
      ['The 11th lord in the 3rd house brings gains through communication, skills, media, and siblings. The native achieves aspirations through self-effort and communication-based ventures.','लाभेश तृतीय भाव में हो तो संचार, कौशल, मीडिया और भाई-बहनों से लाभ होता है। जातक आत्म-प्रयास और संचार-आधारित उद्यमों के माध्यम से आकांक्षाएं पूरी करता है।'],
      ['The 11th lord in the 4th house brings gains through real estate, agriculture, and home-based business. The native achieves domestic aspirations and benefits from mother\'s networks and ancestral property.','लाभेश चतुर्थ भाव में हो तो संपत्ति, कृषि और घर-आधारित व्यवसाय से लाभ होता है। जातक घरेलू आकांक्षाएं पूरी करता है और माता के नेटवर्क तथा पैतृक संपत्ति से लाभान्वित होता है।'],
      ['The 11th lord in the 5th house creates gains through speculation, investments, children, education, and creative works. The native has a sharp financial mind and achieves goals through intellect.','लाभेश पंचम भाव में हो तो सट्टा, निवेश, संतान, शिक्षा और रचनात्मक कार्यों से लाभ होता है। जातक की वित्तीय बुद्धि तीक्ष्ण होती है और वह बुद्धि के माध्यम से लक्ष्य प्राप्त करता है।'],
      ['The 11th lord in the 6th house creates gains through service, healthcare, and legal work, but friends or elder siblings may cause problems. Income comes after competition or conflict.','लाभेश षष्ठ भाव में हो तो सेवा, स्वास्थ्य सेवा और कानूनी कार्य से लाभ होता है, परंतु मित्र या बड़े भाई-बहन समस्याएं उत्पन्न कर सकते हैं। प्रतिस्पर्धा या संघर्ष के बाद आय आती है।'],
      ['The 11th lord in the 7th house brings gains through marriage and business partnerships. The spouse contributes to income and the native achieves aspirations through cooperative ventures.','लाभेश सप्तम भाव में हो तो विवाह और व्यावसायिक साझेदारियों से लाभ होता है। जीवनसाथी आय में योगदान करता है और जातक सहकारी उद्यमों और सार्वजनिक व्यवहार के माध्यम से आकांक्षाएं पूरी करता है।'],
      ['The 11th lord in the 8th house brings sudden and unexpected gains from inheritance, insurance, research, or occult practices. Income is erratic but transformative events ultimately bring prosperity.','लाभेश अष्टम भाव में हो तो विरासत, बीमा, अनुसंधान या तांत्रिक प्रथाओं से अचानक और अप्रत्याशित लाभ होता है। आय अनियमित होती है, परंतु परिवर्तनकारी घटनाएं अंततः समृद्धि लाती हैं।'],
      ['The 11th lord in the 9th house brings gains through dharma, foreign connections, higher education, and religious institutions. The native achieves goals through the blessings of gurus and through fortune.','लाभेश नवम भाव में हो तो धर्म, विदेशी संपर्कों, उच्च शिक्षा और धार्मिक संस्थाओं से लाभ होता है। जातक गुरुओं के आशीर्वाद और भाग्य के माध्यम से लक्ष्य प्राप्त करता है।'],
      ['The 11th lord in the 10th house creates abundant income through career. The native achieves financial goals through professional status and high achievements in public life.','लाभेश दशम भाव में हो तो करियर के माध्यम से प्रचुर आय होती है। जातक व्यावसायिक पद और सार्वजनिक जीवन में उच्च उपलब्धियों के माध्यम से वित्तीय लक्ष्य प्राप्त करता है।'],
      ['The 11th lord in its own house greatly empowers income, social network, and fulfilment of desires. The native is popular, has wide social connections, and achieves most of what they aspire for.','लाभेश स्वयं एकादश भाव में हो तो आय, सामाजिक नेटवर्क और इच्छापूर्ति अत्यधिक प्रबल होती है। जातक लोकप्रिय होता है, उसके विस्तृत सामाजिक संपर्क होते हैं और वह अपनी अधिकांश आकांक्षाएं पूरी करता है।'],
      ['The 11th lord in the 12th house causes spending on gains — the native earns well but also spends lavishly on foreign travels, luxury, and spiritual pursuits. Foreign income is possible.','लाभेश द्वादश भाव में हो तो लाभ पर व्यय होता है — जातक अच्छा कमाता है, परंतु विदेश यात्राओं, विलासिता और आध्यात्मिक अनुसरण पर भव्य खर्च भी करता है। विदेशी आय की संभावना है।'],
    ],

    // ─── 12th Lord ─────────────────────────────────────────────────────────────
    [
      ['The 12th lord in the 1st house may cause health issues, a reclusive nature, or identity struggles. The native may be drawn to foreign lands or spiritual retreat. Losses surround the self unless spiritual practice is embraced.','व्ययेश प्रथम भाव में हो तो स्वास्थ्य समस्याएं, एकांतप्रिय स्वभाव या पहचान की उलझनें हो सकती हैं। जातक विदेश या आध्यात्मिक साधना की ओर खिंच सकता है। जब तक आध्यात्मिक अभ्यास नहीं अपनाया जाए, तब तक स्वयं के इर्द-गिर्द हानि बनी रहती है।'],
      ['The 12th lord in the 2nd house creates financial losses, expenses on family or health, and possible eye-related issues. The native may spend on luxurious food and experiences.','व्ययेश द्वितीय भाव में हो तो आर्थिक हानि, परिवार या स्वास्थ्य पर व्यय और संभावित नेत्र-संबंधी समस्याएं होती हैं (द्वितीय भाव दाहिनी आँख का भी प्रतिनिधित्व करता है)। जातक विलासी भोजन और अनुभवों पर व्यय कर सकता है।'],
      ['The 12th lord in the 3rd house causes loss of courage, expenses through siblings, and distant or foreign travels. Communication about spiritual or foreign subjects is common. The native may write about mysticism.','व्ययेश तृतीय भाव में हो तो साहस की हानि, भाई-बहनों के माध्यम से व्यय और दूरस्थ या विदेशी यात्राएं होती हैं। आध्यात्मिक या विदेशी विषयों पर संचार सामान्य है। जातक रहस्यवाद पर लिख सकता है।'],
      ['The 12th lord in the 4th house creates loss of domestic happiness, expenses on property, or separation from mother and homeland. The native may settle far from birthplace or experience emotional isolation.','व्ययेश चतुर्थ भाव में हो तो गृह सुख की हानि, संपत्ति पर व्यय, या माता और मातृभूमि से अलगाव होता है। जातक जन्मस्थान से दूर बस सकता है या भावनात्मक एकांत का अनुभव कर सकता है।'],
      ['The 12th lord in the 5th house creates expenses through children, romantic losses, and challenges in education. The native may have spiritually gifted children or an intense meditation practice rooted in past-life karma.','व्ययेश पंचम भाव में हो तो संतान पर व्यय, प्रेम में हानि और शिक्षा में चुनौतियाँ होती हैं। जातक की संतान आध्यात्मिक रूप से प्रतिभाशाली हो सकती है या पूर्वजन्म के कर्म में निहित गहन ध्यान अभ्यास हो सकता है।'],
      ['The 12th lord in the 6th house creates a Viparita Raja Yoga. Enemies, debts, and diseases destroy each other. The native prospers after hardships. Medical work in foreign countries or isolated institutions is common.','व्ययेश षष्ठ भाव में हो तो विपरीत राज योग बनता है। शत्रु, ऋण और रोग एक-दूसरे को नष्ट करते हैं। जातक कठिनाइयों के बाद समृद्ध होता है। विदेशी देशों या एकांत संस्थाओं में चिकित्सा कार्य सामान्य है।'],
      ['The 12th lord in the 7th house creates expenses through marriage, foreign spouse, or losses through business partnerships. The native may marry a foreigner and enjoy bed pleasures in foreign lands.','व्ययेश सप्तम भाव में हो तो विवाह के माध्यम से व्यय, विदेशी जीवनसाथी, या व्यावसायिक साझेदारियों से हानि होती है। जातक किसी विदेशी से विवाह कर सकता है और विदेशी भूमि में शयन सुख का आनंद ले सकता है।'],
      ['The 12th lord in the 8th house is another powerful Viparita Raja Yoga. The native triumphs over all losses and becomes resilient after extreme adversity. Hidden wealth, occult mastery, and spiritual liberation are indicated.','व्ययेश अष्टम भाव में हो तो यह एक और शक्तिशाली विपरीत राज योग है। जातक सभी हानियों पर विजय प्राप्त करता है और अत्यधिक प्रतिकूलता के बाद लचीला बनता है। छिपा धन, तांत्रिक निपुणता और आध्यात्मिक मुक्ति संकेतित है।'],
      ['The 12th lord in the 9th house creates expenses on dharmic activities, foreign pilgrimages, and spiritual sacrifices. The native\'s fortune is spent on higher learning and religious causes, leading ultimately to liberation.','व्ययेश नवम भाव में हो तो धार्मिक गतिविधियों, विदेशी तीर्थाटन और आध्यात्मिक त्याग पर व्यय होता है। जातक का भाग्य उच्च शिक्षा और धार्मिक कार्यों पर खर्च होता है, जो अंततः मुक्ति की ओर ले जाता है।'],
      ['The 12th lord in the 10th house may create career setbacks, career in foreign lands, or work in secluded institutions. The native may be famous abroad or work behind the scenes in a significant way.','व्ययेश दशम भाव में हो तो करियर में बाधाएं, विदेश में करियर, या एकांत संस्थाओं में कार्य हो सकता है। जातक विदेश में प्रसिद्ध हो सकता है या पर्दे के पीछे महत्वपूर्ण तरीके से काम कर सकता है।'],
      ['The 12th lord in the 11th house creates expenses through friends and social activities. Gains come through foreign connections, but losses in aspirations are also possible. The native must choose goals wisely.','व्ययेश एकादश भाव में हो तो मित्रों और सामाजिक गतिविधियों के माध्यम से व्यय होता है। विदेशी संपर्कों से लाभ आता है, परंतु आकांक्षाओं में हानि भी संभव है। जातक को लक्ष्यों का बुद्धिमानी से चुनाव करना चाहिए।'],
      ['The 12th lord in its own house powerfully intensifies isolation, spirituality, foreign travels, and expenditures. The native is deeply drawn to moksha, has a reclusive nature, and may reach the highest spiritual states.','व्ययेश स्वयं द्वादश भाव में हो तो एकांत, आध्यात्मिकता, विदेश यात्राएं और व्यय अत्यधिक प्रबल होते हैं। जातक मोक्ष की ओर गहराई से खिंचा होता है, उसका स्वभाव एकांतप्रिय होता है और वह उच्चतम आध्यात्मिक अवस्थाओं तक पहुँच सकता है।'],
    ],
  ];

  // ── Build rows ───────────────────────────────────────────────────────────────
  const rows = [];
  for (let li = 0; li < 12; li++) {
    const lord = LORDS[li];
    for (let hi = 0; hi < 12; hi++) {
      const house = hi + 1;
      const [en, hn] = D[li][hi];
      rows.push({
        house_lord:           li + 1,
        placed_in_house:      house,
        title:                `${ordinal(li+1)} Lord in ${ordinal(house)} House`,
        title_hi:             `${li+1}वें भावेश ${house}वें भाव में`,
        interpretation_en:    en,
        interpretation_hi:    hn,
        key_results_en:       JSON.stringify([]),
        key_results_hi:       JSON.stringify([]),
        overall_effect:       eff(li + 1, house),
        source:               src,
        lord_name_en:         lord.en,
        lord_name_hi:         lord.hi,
        house_signification_en: lord.sig_en,
        house_signification_hi: lord.sig_hi,
        forms_viparita_yoga:  vry(li + 1, house),
      });
    }
  }

  await knex('house_lord_interpretations').insert(rows);
};

// ── Helpers (mirror of JS ordinal) ────────────────────────────────────────────
function ordinal(n) {
  const s = ['th','st','nd','rd'];
  const v = n % 100;
  return n + (s[(v-20)%10] || s[v] || s[0]);
}
