'use strict';
// Seed 019 — Kundli Judgement Priority Engine rule data (idempotent)

const CATEGORIES = [
  { key:'lagna',     name_en:'Lagna & Personality',          name_hi:'लग्न और व्यक्तित्व',           description:'Rules for evaluating Lagna lord strength and personality foundation' },
  { key:'sun_moon',  name_en:'Sun & Moon Pillars',           name_hi:'सूर्य और चंद्र स्तंभ',         description:'Rules for Sun (authority/father) and Moon (mind/emotions) evaluation' },
  { key:'yoga',      name_en:'Yoga Conditional Activation',  name_hi:'योग सशर्त सक्रियता',           description:'Rules for conditionally activating detected yogas' },
  { key:'house_lord',name_en:'House Lord Strength',          name_hi:'भाव स्वामी बल',                description:'Rules for evaluating house lord placement and dignity for key houses' },
  { key:'gains',     name_en:'Gains & Income (11th House)',  name_hi:'लाभ और आय (11वां भाव)',        description:'Deep evaluation of 11th house for income stability and desire fulfillment' },
  { key:'marriage',  name_en:'Marriage & Relationships',     name_hi:'विवाह और रिश्ते',              description:'Rules for marriage judgement from 7th house, Venus, D9' },
  { key:'children',  name_en:'Children & Education',         name_hi:'संतान और शिक्षा',              description:'5th house rules for children and education — uses safe language' },
  { key:'rahu',      name_en:'Rahu Special Rules',           name_hi:'राहु विशेष नियम',              description:'Rahu placement rules for each house' },
  { key:'navamsha',  name_en:'Navamsha D9 Activation',       name_hi:'नवांश D9 सक्रियता',           description:'D9 maturity rules after age 36 or marriage' },
  { key:'safety',    name_en:'Language Safety Rules',        name_hi:'भाषा सुरक्षा नियम',           description:'Forbidden phrases and safe replacement rules for user output' },
];

const JUDGEMENT_RULES = [
  // Lagna rules
  { rule_key:'lagna.lord.strong.kendra',   category_key:'lagna', applies_to:'lagna_lord', priority:9, weight:1.2, blocker_level:'none',   activation_type:'full',        output_en:'Lagna lord in kendra/trikona — strong chart foundation.',                                                                        output_hi:'लग्नेश केंद्र/त्रिकोण में — मजबूत कुंडली आधार।',                                                                             advice_en:'Use this strength for long-term goals.',                    advice_hi:'दीर्घकालिक लक्ष्यों के लिए इस शक्ति का उपयोग करें।',          admin_reason_en:'Lagna lord in angular/trine = highest strength zone.' },
  { rule_key:'lagna.lord.weak.trik',       category_key:'lagna', applies_to:'lagna_lord', priority:9, weight:1.2, blocker_level:'medium',  activation_type:'conditional', output_en:'Lagna lord in trik house — health, dispute, or service themes need care.',                                                       output_hi:'लग्नेश तृक भाव में — स्वास्थ्य, विवाद या सेवा विषयों में सावधानी जरूरी।',                                                        caution_en:'Positive yogas may show reduced confidence.',               caution_hi:'सकारात्मक योगों में कम आत्मविश्वास हो सकता है।',              admin_reason_en:'Trik placement reduces lagna lord\'s ability to protect chart.' },
  { rule_key:'lagna.lord.rahu.ketu',       category_key:'lagna', applies_to:'lagna_lord', priority:8, weight:1.1, blocker_level:'mild',    activation_type:'conditional', output_en:'Rahu/Ketu on lagna lord — ambition or confusion in personality.',                                                                 output_hi:'लग्नेश पर राहु/केतु — व्यक्तित्व में महत्वाकांक्षा या अनिश्चितता।',                                                              caution_en:'Grounding practices and consistent routines help.',          caution_hi:'ग्राउंडिंग अभ्यास और नियमित दिनचर्या सहायक है।',              admin_reason_en:'Rahu/Ketu eclipse the lagna lord energy.' },
  { rule_key:'lagna.lord.paap.kartari',    category_key:'lagna', applies_to:'lagna_lord', priority:7, weight:1.0, blocker_level:'medium',  activation_type:'conditional', output_en:'Lagna lord in Paap Kartari — personal growth and health need extra protection.',                                                   output_hi:'लग्नेश पाप कर्तरी में — व्यक्तिगत विकास और स्वास्थ्य को extra सुरक्षा जरूरी।',                                                    caution_en:'Avoid being hemmed into unfavourable situations.',          caution_hi:'प्रतिकूल परिस्थितियों में फंसने से बचें।',                     admin_reason_en:'Paap Kartari squeezes lagna lord between malefics.' },
  // Sun rules
  { rule_key:'sun.9th.afflicted.pitra',    category_key:'sun_moon', applies_to:'sun', priority:8, weight:1.1, blocker_level:'mild',   activation_type:'conditional', output_en:'Sun afflicted in 9th — Pitra Dosha indicator. Ancestral karma and father matters need attention.',                                 output_hi:'9वें में सूर्य पीड़ित — पितृ दोष संकेत। पूर्वज कर्म और पिता के मामलों पर ध्यान जरूरी।',                                           advice_en:'Pitra Tarpan, Sun remedies, and respect for elders help.',  advice_hi:'पितृ तर्पण, सूर्य उपाय और बड़ों का सम्मान सहायक है।',          admin_reason_en:'Sun in 9H with Rahu/Saturn/Ketu = Pitra Dosha indicator.' },
  { rule_key:'sun.exalted.authority',      category_key:'sun_moon', applies_to:'sun', priority:7, weight:1.0, blocker_level:'none',   activation_type:'full',        output_en:'Sun exalted — strong self-confidence, authority, and government support.',                                                          output_hi:'सूर्य उच्च — मजबूत आत्मविश्वास, अधिकार और सरकारी समर्थन।',                                                                       advice_en:'Leadership and authority fields are natural strengths.',     advice_hi:'नेतृत्व और अधिकार क्षेत्र स्वाभाविक शक्तियां हैं।',             admin_reason_en:'Exalted Sun in Aries = peak dignitary strength.' },
  // Moon rules
  { rule_key:'moon.grahan.caution',        category_key:'sun_moon', applies_to:'moon', priority:9, weight:1.2, blocker_level:'medium', activation_type:'conditional', output_en:'Rahu/Ketu with Moon (Grahan) — emotional intensity needs mindful management. Gaj Kesari and Moon yogas are reduced.',              output_hi:'राहु/केतु के साथ चंद्र (ग्रहण) — भावनात्मक तीव्रता का सचेत प्रबंधन जरूरी। गजकेसरी और चंद्र योग कम हो जाते हैं।',              advice_en:'Mindfulness, regular routine, and Moon remedies are very helpful.', advice_hi:'माइंडफुलनेस, नियमित दिनचर्या और चंद्र उपाय बहुत सहायक हैं।', admin_reason_en:'Rahu/Ketu with Moon = Grahan Yoga: emotional unpredictability.' },
  { rule_key:'moon.kemadruma',             category_key:'sun_moon', applies_to:'moon', priority:8, weight:1.1, blocker_level:'medium', activation_type:'conditional', output_en:'Kemadruma condition — Moon alone, emotional support may need conscious cultivation.',                                                   output_hi:'केमद्रुम स्थिति — चंद्रमा अकेला, भावनात्मक समर्थन को सचेत रूप से विकसित करना जरूरी।',                                             advice_en:'Strong community, meditation, and Moon remedies help overcome Kemadruma.', advice_hi:'मजबूत समुदाय, ध्यान और चंद्र उपाय केमद्रुम से उबरने में मदद करते हैं।', admin_reason_en:'Kemadruma: No planet in 2nd or 12th from Moon.' },
  // Yoga rules
  { rule_key:'yoga.gajkesari.blocked',     category_key:'yoga', applies_to:'yoga', priority:9, weight:1.2, blocker_level:'strong',  activation_type:'partial', output_en:'Gaj Kesari blocked — Rahu on Moon and weak Lagna. Wisdom and support potential exist but emotional instability can reduce results.', output_hi:'गजकेसरी अवरुद्ध — चंद्र पर राहु और कमजोर लग्न। बुद्धि और समर्थन की संभावना है लेकिन भावनात्मक अस्थिरता परिणाम घटा सकती है।', admin_reason_en:'Grahan on Moon + weak Lagna = Gaj Kesari partial/blocked.' },
  { rule_key:'yoga.rajyog.debil',          category_key:'yoga', applies_to:'yoga', priority:8, weight:1.0, blocker_level:'medium', activation_type:'partial', output_en:'Raja Yoga planets are weak — recognition comes slowly through effort and right timing.',                                                    output_hi:'राज योग ग्रह कमजोर — प्रयास और सही समय से धीरे-धीरे पहचान मिलती है।',                                                             admin_reason_en:'Debilitated or afflicted yoga planets reduce Raja Yoga quality.' },
  // Gains rules
  { rule_key:'gains.11lord.trik',          category_key:'gains', applies_to:'house_lord', priority:8, weight:1.0, blocker_level:'medium', activation_type:'conditional', output_en:'11th lord in trik — income comes with struggle or delay. Disciplined effort and right sources are key.',                           output_hi:'11वें स्वामी तृक में — आय संघर्ष या देरी के साथ आती है। अनुशासित प्रयास और सही स्रोत महत्वपूर्ण है।',                                caution_en:'Avoid risky or speculative income sources.',               caution_hi:'जोखिम भरे या सट्टेबाजी आय स्रोतों से बचें।',                  admin_reason_en:'11th lord in 6/8/12 = restricted income flow.' },
  // Marriage rules
  { rule_key:'marriage.7lord.10th',        category_key:'marriage', applies_to:'house_lord', priority:8, weight:1.0, blocker_level:'none', activation_type:'full', output_en:'7th lord in 10th — spouse may come from same field, or marriage may support career growth.',                                            output_hi:'7वें स्वामी 10वें में — जीवनसाथी एक ही क्षेत्र से आ सकता है, या विवाह करियर विकास में सहयोग दे सकता है।',                         admin_reason_en:'7L in 10H: professional connection with spouse; classic pattern.' },
  { rule_key:'marriage.paap.kartari.7th',  category_key:'marriage', applies_to:'house_lord', priority:8, weight:1.0, blocker_level:'medium', activation_type:'conditional', output_en:'Paap Kartari around 7th lord — delays or ego/support challenges in relationships need care.',                                  output_hi:'7वें स्वामी पर पाप कर्तरी — रिश्तों में देरी या अहंकार/समर्थन की चुनौतियों पर ध्यान जरूरी।',                                      caution_en:'Patience and communication are critical for relationship stability.', caution_hi:'रिश्ते की स्थिरता के लिए धैर्य और संवाद बहुत जरूरी है।', admin_reason_en:'Paap Kartari on 7H lord restricts partnership flow.' },
  // Children rules
  { rule_key:'children.ketu.5th',          category_key:'children', applies_to:'planet', priority:9, weight:1.2, blocker_level:'medium', activation_type:'conditional', output_en:'Ketu in 5th — extra care in children matters, unconventional education, love-life maturity. Medical guidance and timing important.', output_hi:'5वें में केतु — संतान के मामलों में extra care, असामान्य शिक्षा, प्रेम में परिपक्वता। चिकित्सा मार्गदर्शन और समय महत्वपूर्ण।',   caution_en:'Never interpret as denial — patience and guidance are key.', caution_hi:'कभी इनकार की तरह नहीं लेना — धैर्य और मार्गदर्शन महत्वपूर्ण है।', admin_reason_en:'Ketu in 5H: detachment, delay, spiritual creativity.' },
  { rule_key:'children.saturn.aspect.5th', category_key:'children', applies_to:'planet', priority:8, weight:1.0, blocker_level:'mild',   activation_type:'conditional', output_en:'Saturn aspects 5th — delay or responsibility in children matters. Patience and medical guidance are important.',                   output_hi:'शनि का 5वें पर पहलू — संतान में देरी या जिम्मेदारी। धैर्य और चिकित्सा मार्गदर्शन महत्वपूर्ण।',                                     admin_reason_en:'Saturn aspect = delay + responsibility on 5H themes.' },
  // Rahu rules
  { rule_key:'rahu.11th.gains.conditional', category_key:'rahu', applies_to:'rahu', priority:9, weight:1.1, blocker_level:'mild', activation_type:'conditional', output_en:'Rahu in 11th — income potential conditional on age 42+, dasha support, and strong 11th lord.',                                         output_hi:'11वें में राहु — आय क्षमता 42+ उम्र, दशा समर्थन और मजबूत 11वें स्वामी पर आधारित।',                                               admin_reason_en:'Rahu 11H: gains = Rahu maturity age + lord strength + dasha.' },
  { rule_key:'rahu.good.houses',            category_key:'rahu', applies_to:'rahu', priority:7, weight:0.9, blocker_level:'none', activation_type:'full', output_en:'Rahu in 3rd/6th/10th — good placement for initiative, overcoming obstacles, or career ambition.',                                            output_hi:'3/6/10वें में राहु — पहल, बाधाओं पर काबू या करियर महत्वाकांक्षा के लिए अच्छा स्थान।',                                              admin_reason_en:'Rahu in upachaya/kendra gives worldly success drive.' },
  // Navamsha rules
  { rule_key:'navamsha.d9.weak.d1.strong', category_key:'navamsha', applies_to:'navamsha', priority:8, weight:1.0, blocker_level:'mild', activation_type:'conditional', output_en:'D1 strong but D9 challenges present — marriage depth and post-marriage harmony need conscious effort.',                           output_hi:'D1 मजबूत लेकिन D9 में चुनौतियां — विवाह की गहराई और बाद में सामंजस्य के लिए सचेत प्रयास जरूरी।',                                   admin_reason_en:'D9 weakness shows in post-marriage relationship quality.' },
  { rule_key:'navamsha.d9.strong.d1.weak', category_key:'navamsha', applies_to:'navamsha', priority:8, weight:1.0, blocker_level:'none', activation_type:'conditional', output_en:'D1 challenges but D9 is positive — improvement after maturity (36+) or marriage. Patience and right choices lead to better outcomes.', output_hi:'D1 में चुनौतियां लेकिन D9 सकारात्मक — परिपक्वता (36+) या विवाह के बाद सुधार। धैर्य और सही चुनाव बेहतर परिणाम देते हैं।', admin_reason_en:'Stronger D9 vs D1 = late bloomer / improvement after marriage.' },
  // Safety rules
  { rule_key:'safety.no.spouse.death',      category_key:'safety', applies_to:'marriage', priority:10, weight:1.5, blocker_level:'severe', activation_type:'blocked', output_en:'Use safe language only: "Extra care needed in health, safety, and relationship management."', output_hi:'केवल सुरक्षित भाषा: "स्वास्थ्य, safety और रिश्ते प्रबंधन में extra care जरूरी।"', admin_reason_en:'NEVER output spouse death prediction in user mode.' },
  { rule_key:'safety.no.divorce.guarantee', category_key:'safety', applies_to:'marriage', priority:10, weight:1.5, blocker_level:'severe', activation_type:'blocked', output_en:'Use safe language: "Relationship communication, ego management, and family maturity are very important."', output_hi:'सुरक्षित भाषा: "रिश्ते का संवाद, अहंकार प्रबंधन और पारिवारिक परिपक्वता बहुत जरूरी है।"', admin_reason_en:'Divorce guarantee is fatalistic and harmful. Never use.' },
  { rule_key:'safety.no.child.denial',      category_key:'safety', applies_to:'children', priority:10, weight:1.5, blocker_level:'severe', activation_type:'blocked', output_en:'Use safe language: "Extra care, patience, and medical guidance are recommended in children matters."', output_hi:'सुरक्षित भाषा: "संतान के मामलों में extra care, धैर्य और चिकित्सा मार्गदर्शन अनुशंसित है।"', admin_reason_en:'Child denial is harmful and astrologically inaccurate.' },
];

const YOGA_ACTIVATION_RULES = [
  { yoga_key:'gajakesari', required_conditions_json: JSON.stringify(['moon_in_kendra','jupiter_in_kendra','moon_jupiter_relation']), blocking_conditions_json: JSON.stringify(['rahu_on_moon','ketu_on_moon','moon_debilitated','jupiter_debilitated','lagna_score_below_40']), output_en:'Gaj Kesari Yoga is present. Its activation depends on Moon strength, Jupiter dignity, Rahu/Ketu absence on Moon, and Lagna strength.', output_hi:'गजकेसरी योग मौजूद है। इसकी सक्रियता चंद्र शक्ति, गुरु की राशि, चंद्र पर राहु/केतु की अनुपस्थिति और लग्न शक्ति पर निर्भर करती है।', admin_reason:'Classic Gaj Kesari requires Moon+Jupiter in kendra mutual, both dignified, no Grahan.' },
  { yoga_key:'rajyoga_generic', required_conditions_json: JSON.stringify(['kendra_trikona_lord_connection']), blocking_conditions_json: JSON.stringify(['yoga_lord_debilitated','yoga_lord_deeply_afflicted','paap_kartari_on_yoga_lord']), output_en:'Raja Yoga shows achievement potential. Activation requires yoga lords to be dignified and supported by dasha.', output_hi:'राज योग उपलब्धि क्षमता दिखाता है। सक्रियता के लिए योग स्वामियों का बलवान और दशा समर्थित होना जरूरी है।', admin_reason:'Raja Yoga: kendra-trikona lord connection. Strength depends on dignity and freedom from affliction.' },
  { yoga_key:'dhan_lakshmi', required_conditions_json: JSON.stringify(['sun_9th_own_sign_or_strength','2nd_9th_11th_lords_supported']), blocking_conditions_json: JSON.stringify(['lagna_weak','11th_lord_trik','paap_kartari_on_11th']), output_en:'Dhan Lakshmi yoga potential. Full activation needs strong 2nd, 9th, 11th lords and Lagna lord.', output_hi:'धन लक्ष्मी योग क्षमता। पूर्ण सक्रियता के लिए मजबूत 2, 9, 11वें स्वामी और लग्नेश जरूरी।', admin_reason:'Dhan Lakshmi: Sun in 9H own sign + strong wealth houses. All four lords must cooperate.' },
];

const HOUSE_LORD_RULES = [
  { house_number:1, lord_placed_in_house:6, strength_condition:'strong', output_en:'Lagna lord in 6th but strong — competition, service sector victory, and problem-solving ability.', output_hi:'लग्नेश 6वें में लेकिन बलवान — प्रतिस्पर्धा, सेवा क्षेत्र की जीत और समस्या-समाधान क्षमता।', advice_en:'Use competitive and service-oriented fields as strengths.', advice_hi:'प्रतिस्पर्धी और सेवा-उन्मुख क्षेत्रों को शक्ति के रूप में उपयोग करें।' },
  { house_number:1, lord_placed_in_house:6, strength_condition:'weak',   output_en:'Lagna lord in 6th and weak — health challenges, disputes, and service-sector difficulties need care.', output_hi:'लग्नेश 6वें में और कमजोर — स्वास्थ्य चुनौतियां, विवाद और सेवा क्षेत्र की कठिनाइयों पर ध्यान जरूरी।', caution_en:'Health monitoring and conflict avoidance are important.', caution_hi:'स्वास्थ्य निगरानी और संघर्ष से बचाव महत्वपूर्ण है।' },
  { house_number:4, lord_placed_in_house:6, strength_condition:'any',    output_en:'4th lord in 6th — mother health concern, home disputes, or reduced domestic peace unless lord is strong.', output_hi:'4वें स्वामी 6वें में — माता स्वास्थ्य चिंता, घर के विवाद, या घरेलू शांति में कमी जब तक स्वामी बलवान न हो।', advice_en:'Property through effort, ability to solve home disputes if lord is strong.', advice_hi:'प्रयास से संपत्ति, यदि स्वामी बलवान हो तो घरेलू विवाद सुलझाने की क्षमता।' },
  { house_number:7, lord_placed_in_house:10, strength_condition:'any',   output_en:'7th lord in 10th — spouse from same profession or field. Marriage may support career growth when supported.', output_hi:'7वें स्वामी 10वें में — एक ही पेशे के जीवनसाथी। समर्थन मिलने पर विवाह करियर विकास में सहायक हो सकता है।', advice_en:'Work-life balance and career communication with partner are important.', advice_hi:'काम-जीवन संतुलन और साथी के साथ करियर संवाद महत्वपूर्ण है।' },
  { house_number:11, lord_placed_in_house:6, strength_condition:'any',   output_en:'11th lord in 6th — income through service, health field, or legal field. Gains come with effort and competition.', output_hi:'11वें स्वामी 6वें में — सेवा, स्वास्थ्य या कानूनी क्षेत्र से आय। प्रयास और प्रतिस्पर्धा से लाभ मिलता है।', advice_en:'Service-sector, healthcare, or legal professions can be income sources.', advice_hi:'सेवा क्षेत्र, स्वास्थ्य सेवा या कानूनी व्यवसाय आय स्रोत हो सकते हैं।' },
];

const SPECIAL_PLANET_RULES = [
  { planet:'Rahu', house_number:3,  condition_key:'good_placement', output_en:'Rahu in 3rd — courage, communication, unconventional thinking, and competitive ability.', output_hi:'3वें में राहु — साहस, संवाद, असामान्य सोच और प्रतिस्पर्धी क्षमता।', caution_en:'Watch for over-ambition or sibling rivalry.', caution_hi:'अत्यधिक महत्वाकांक्षा या भाई-बहन की प्रतिद्वंद्विता से सावधान।' },
  { planet:'Rahu', house_number:6,  condition_key:'good_placement', output_en:'Rahu in 6th — victory over enemies, overcoming health challenges, success in competition.', output_hi:'6वें में राहु — शत्रु पर विजय, स्वास्थ्य चुनौतियों पर काबू, प्रतिस्पर्धा में सफलता।', caution_en:'Watch for hidden enemies and chronic health issues.', caution_hi:'छिपे दुश्मनों और दीर्घकालिक स्वास्थ्य समस्याओं से सावधान।' },
  { planet:'Rahu', house_number:10, condition_key:'good_placement', output_en:'Rahu in 10th — strong career ambition, unconventional or technology/foreign career success.', output_hi:'10वें में राहु — मजबूत करियर महत्वाकांक्षा, असामान्य या प्रौद्योगिकी/विदेशी करियर सफलता।', caution_en:'Ethics, shortcuts, and authority conflicts need careful management.', caution_hi:'नैतिकता, शॉर्टकट और अधिकार संघर्षों का सावधानी से प्रबंधन जरूरी।' },
  { planet:'Rahu', house_number:11, condition_key:'conditional',    output_en:'Rahu in 11th — income potential conditional on age 42+, strong 11th lord, and dasha support.', output_hi:'11वें में राहु — आय क्षमता 42+ उम्र, मजबूत 11वें स्वामी और दशा समर्थन पर आधारित।', caution_en:'Wise financial planning and stable income sources are essential.', caution_hi:'सुबुद्ध वित्तीय योजना और स्थिर आय स्रोत आवश्यक हैं।' },
  { planet:'Ketu', house_number:5,  condition_key:'delay_care',     output_en:'Ketu in 5th — extra care in children matters, unconventional education path, love-life needs maturity.', output_hi:'5वें में केतु — संतान में extra care, असामान्य शिक्षा, प्रेम जीवन में परिपक्वता जरूरी।', advice_en:'Medical guidance, patience, and right timing are very important for children matters.', advice_hi:'संतान के मामलों में चिकित्सा मार्गदर्शन, धैर्य और सही समय बहुत जरूरी।', caution_en:'Never interpret as denial of children.', caution_hi:'कभी संतान से इनकार की तरह नहीं लेना।' },
];

async function upsert(knex, table, uniqueKeys, data) {
  for (const row of data) {
    const whereClause = {};
    for (const key of uniqueKeys) whereClause[key] = row[key];
    const exists = await knex(table).where(whereClause).first();
    if (exists) {
      await knex(table).where(whereClause).update({ ...row, updated_at: new Date() });
    } else {
      await knex(table).insert(row).catch(() => {});
    }
  }
}

exports.seed = async (knex) => {
  await upsert(knex, 'astrology_rule_categories', ['key'], CATEGORIES);
  await upsert(knex, 'astrology_judgement_rules', ['rule_key'], JUDGEMENT_RULES);
  await upsert(knex, 'astrology_yoga_activation_rules', ['yoga_key'], YOGA_ACTIVATION_RULES);
  await upsert(knex, 'astrology_house_lord_rules', ['house_number','lord_placed_in_house','strength_condition'], HOUSE_LORD_RULES);
  await upsert(knex, 'astrology_special_planet_rules', ['planet','house_number','condition_key'], SPECIAL_PLANET_RULES);
};
