'use strict';

exports.seed = async function (knex) {
  // ── 1. Master definitions ────────────────────────────────────────────────────
  const UPAGRAHAS = [
    {
      slug: 'dhuma',
      name_en: 'Dhuma', name_hi: 'धूम',
      literal_meaning_en: 'Smoke', literal_meaning_hi: 'धुआँ',
      nature_en: 'Saturn-like (tamasic, malefic); represents clouding of clarity.',
      nature_hi: 'शनिवत् (तामसिक, अशुभ); स्पष्टता पर आवरण का प्रतीक।',
      symbolism_en: 'Confusion, obscurity, smoke screen over judgement.',
      symbolism_hi: 'भ्रम, अस्पष्टता, निर्णय पर धुएं का आवरण।',
      positive_traits_en: 'Can give depth, introspection, and ability to work patiently behind the scenes when well placed.',
      positive_traits_hi: 'शुभ स्थिति में गहराई, आत्मचिंतन तथा पर्दे के पीछे धैर्यपूर्वक कार्य करने की क्षमता देता है।',
      negative_traits_en: 'Confusion, deception, scandal, ill health, obscured judgement, addictions.',
      negative_traits_hi: 'भ्रम, छल, बदनामी, अस्वस्थता, अस्पष्ट निर्णय-क्षमता, व्यसन।',
      psychological_en: 'Tendency to hide true feelings; secretive, brooding, occasional pessimism.',
      psychological_hi: 'वास्तविक भावनाओं को छिपाने की प्रवृत्ति; गुप्तचेता, चिंतनशील, कभी-कभी निराशावाद।',
      spiritual_en: 'Encourages letting go of illusion (maya) and facing hidden truths; linked to purification through difficulty.',
      spiritual_hi: 'माया के त्याग तथा छिपे हुए सत्य का सामना करने हेतु प्रेरित करता है; कष्ट के माध्यम से शुद्धिकरण से संबंधित।',
      formula_en: "Sun's longitude + 133° 20'",
      formula_hi: "सूर्य रेखांश + 133° 20'",
      key_indication_en: 'Examine for hidden afflictions, secretive behaviour, and respiratory/eye health when placed in the 1st, 6th, 8th or 12th house.',
      key_indication_hi: 'लग्न, षष्ठ, अष्टम या द्वादश भाव में स्थिति पर गुप्त कष्ट, गुप्त स्वभाव तथा श्वास/आँख स्वास्थ्य का परीक्षण करें।',
      is_malefic: true, is_benefic: false, display_order: 1,
    },
    {
      slug: 'vyatipata',
      name_en: 'Vyatipata', name_hi: 'व्यतिपात',
      literal_meaning_en: 'Calamity / sudden reversal', literal_meaning_hi: 'विपत्ति, आकस्मिक उलटफेर',
      nature_en: 'Saturn-Rahu-like; volatile and malefic.',
      nature_hi: 'शनि-राहु तुल्य; अस्थिर तथा अशुभ।',
      symbolism_en: 'Sudden adverse turn, instability, contrary fortune.',
      symbolism_hi: 'आकस्मिक विपरीत मोड़, अस्थिरता, विपरीत भाग्य।',
      positive_traits_en: 'Can confer sharp intuition about danger and the ability to survive sudden upheavals.',
      positive_traits_hi: 'खतरे के प्रति तीव्र अंतर्ज्ञान तथा आकस्मिक उलटफेर से उबरने की क्षमता दे सकता है।',
      negative_traits_en: 'Sudden misfortune, instability, accidents, reversal of well-laid plans, betrayal.',
      negative_traits_hi: 'आकस्मिक दुर्भाग्य, अस्थिरता, दुर्घटना, सुनियोजित योजनाओं का उलटना, विश्वासघात।',
      psychological_en: 'Restlessness, fear of unpredictability, tendency toward anxiety in uncertain situations.',
      psychological_hi: 'अस्थिरता-भय, अनिश्चितता के प्रति चिंता की प्रवृत्ति।',
      spiritual_en: 'Teaches surrender to fate (prarabdha) and acceptance of impermanence.',
      spiritual_hi: 'भाग्य (प्रारब्ध) के प्रति समर्पण तथा अनित्यता की स्वीकृति सिखाता है।',
      formula_en: "360° − Dhuma's longitude",
      formula_hi: '360° − धूम रेखांश',
      key_indication_en: 'Examine for sudden reversals of fortune and accident-proneness when conjunct malefics or angular houses.',
      key_indication_hi: 'पाप ग्रहों से युति या केंद्र भावों में आकस्मिक भाग्य-परिवर्तन और दुर्घटना-प्रवृत्ति का परीक्षण करें।',
      is_malefic: true, is_benefic: false, display_order: 2,
    },
    {
      slug: 'parivesha',
      name_en: 'Parivesha', name_hi: 'परिवेष',
      literal_meaning_en: 'Halo / encircling ring of light', literal_meaning_hi: 'प्रभामंडल, घेरा',
      nature_en: 'Venus-like; generally benefic and luminous.',
      nature_hi: 'शुक्रवत्; सामान्यतः शुभ तथा तेजयुक्त।',
      symbolism_en: 'Brilliance, fame, halo of authority and recognition.',
      symbolism_hi: 'प्रतिभा, यश, अधिकार और मान्यता का प्रभामंडल।',
      positive_traits_en: 'Confers fame, charisma, artistic refinement, public recognition and protective grace.',
      positive_traits_hi: 'यश, आकर्षण, कलात्मक परिष्कार, जनमान्यता तथा रक्षात्मक कृपा प्रदान करता है।',
      negative_traits_en: 'Can give vanity, superficial glamour, or fame that proves short-lived if afflicted.',
      negative_traits_hi: 'पीड़ित होने पर अहंकार, सतही चमक-दमक अथवा अल्पकालिक यश दे सकता है।',
      psychological_en: 'Desire for recognition and admiration; sensitivity to public image.',
      psychological_hi: 'मान्यता तथा प्रशंसा की इच्छा; सार्वजनिक प्रतिष्ठा के प्रति संवेदनशीलता।',
      spiritual_en: 'Associated with the aura of grace surrounding sincere effort; symbolic of divine protection encircling the soul.',
      spiritual_hi: 'निष्ठापूर्ण प्रयास के चतुर्दिक कृपा-तेज से संबंधित; आत्मा को घेरने वाली दिव्य सुरक्षा का प्रतीक।',
      formula_en: "Vyatipata's longitude + 180°",
      formula_hi: 'व्यतिपात रेखांश + 180°',
      key_indication_en: 'Examine for fame, public recognition and artistic success when well placed in angular or trinal houses.',
      key_indication_hi: 'केंद्र या त्रिकोण भावों में शुभ स्थिति पर यश, जन-मान्यता और कलात्मक सफलता का परीक्षण करें।',
      is_malefic: false, is_benefic: true, display_order: 3,
    },
    {
      slug: 'indrachapa',
      name_en: 'Indrachapa', name_hi: 'इन्द्रचाप',
      literal_meaning_en: "Indra's bow / rainbow", literal_meaning_hi: 'इन्द्रधनुष',
      nature_en: 'Jupiter-like; benefic but transient in effect.',
      nature_hi: 'गुरुवत्; शुभ परंतु अस्थायी प्रभाव।',
      symbolism_en: 'Transient beauty, hope, fleeting brilliance.',
      symbolism_hi: 'क्षणिक सौंदर्य, आशा, अल्पकालिक प्रतिभा।',
      positive_traits_en: 'Brings optimism, brief windfalls, idealism, and moments of inspired wisdom.',
      positive_traits_hi: 'आशावाद, क्षणिक लाभ, आदर्शवाद तथा प्रेरणादायक ज्ञान के क्षण देता है।',
      negative_traits_en: 'Effects often prove fleeting; can indicate hopes that do not fully materialise.',
      negative_traits_hi: 'प्रभाव प्रायः अल्पकालिक होते हैं; ऐसी आशाएँ संकेतित करता है जो पूर्णतः साकार नहीं होती।',
      psychological_en: 'Idealistic, hopeful, occasionally prone to chasing illusions of quick success.',
      psychological_hi: 'आदर्शवादी, आशावान, कभी-कभी शीघ्र सफलता के मोहक भ्रम के पीछे भागने की प्रवृत्ति।',
      spiritual_en: 'Symbolic of divine grace appearing briefly after a storm — a reminder that beauty and relief follow hardship.',
      spiritual_hi: 'तूफान के पश्चात क्षणिक रूप से प्रकट होने वाली दिव्य कृपा का प्रतीक — यह स्मरण कराता है कि कष्ट के पश्चात सौंदर्य व राहत आती है।',
      formula_en: "360° − Parivesha's longitude",
      formula_hi: '360° − परिवेष रेखांश',
      key_indication_en: 'Examine for transient gains, idealistic pursuits, and inspirational but short-lived success in the 9th, 10th or 11th house.',
      key_indication_hi: 'नवम, दशम या एकादश भाव में क्षणिक लाभ, आदर्शवादी प्रयास और प्रेरक परंतु अल्पकालिक सफलता का परीक्षण करें।',
      is_malefic: false, is_benefic: true, display_order: 4,
    },
    {
      slug: 'upaketu',
      name_en: 'Upaketu', name_hi: 'उपकेतु',
      literal_meaning_en: 'Minor comet / lesser banner', literal_meaning_hi: 'लघु धूमकेतु',
      nature_en: 'Ketu/Mars-like; malefic and disruptive.',
      nature_hi: 'केतु-मंगल तुल्य; अशुभ तथा विघटनकारी।',
      symbolism_en: 'Sudden disturbance, fire, restlessness, detachment.',
      symbolism_hi: 'आकस्मिक उपद्रव, अग्नि, अस्थिरता, वैराग्य।',
      positive_traits_en: 'Can give detachment, sudden insight, and the courage to break from convention when needed.',
      positive_traits_hi: 'वैराग्य, आकस्मिक अंतर्दृष्टि तथा आवश्यकता पड़ने पर परंपरा से मुक्त होने का साहस दे सकता है।',
      negative_traits_en: 'Sudden disturbances, fire-related risk, restlessness, accidents, severed relationships.',
      negative_traits_hi: 'आकस्मिक उपद्रव, अग्नि-संबंधी जोखिम, अस्थिरता, दुर्घटना, संबंधों का विच्छेद।',
      psychological_en: 'Impulsive, restless, prone to abrupt decisions and detachment from established ties.',
      psychological_hi: 'आवेगी, अस्थिरचित्त, आकस्मिक निर्णय तथा स्थापित संबंधों से वैराग्य की प्रवृत्ति।',
      spiritual_en: "Linked with Ketu's quality of sudden renunciation; pushes the native toward unexpected spiritual turning points.",
      spiritual_hi: 'केतु के आकस्मिक वैराग्य गुण से संबंधित; जातक को अप्रत्याशित आध्यात्मिक मोड़ की ओर प्रेरित करता है।',
      formula_en: "Indrachapa's longitude + 16° 40'",
      formula_hi: "इन्द्रचाप रेखांश + 16° 40'",
      key_indication_en: 'Examine for sudden disruptions, fire/accident risk, and abrupt detachment when conjunct Mars, Rahu or Ketu.',
      key_indication_hi: 'मंगल, राहु या केतु से युति में आकस्मिक विघ्न, अग्नि/दुर्घटना जोखिम और अचानक वैराग्य का परीक्षण करें।',
      is_malefic: true, is_benefic: false, display_order: 5,
    },
  ];

  for (const u of UPAGRAHAS) {
    await knex('upagrahas').insert(u).onConflict('slug').merge();
  }

  // ── 2. House effects (5 × 12 = 60 rows) ──────────────────────────────────────
  const HOUSE_EFFECTS = [
    // ── Dhuma
    { s:'dhuma', h:1,  en:'Self-doubt, hidden health issues, a clouded sense of identity.',                                                  hi:'आत्म-संदेह, गुप्त स्वास्थ्य समस्याएँ, अस्पष्ट आत्म-बोध।' },
    { s:'dhuma', h:2,  en:'Confused finances, harsh or unclear speech, hoarding tendencies.',                                               hi:'धन संबंधी भ्रम, कठोर अथवा अस्पष्ट वाणी, संग्रहण की प्रवृत्ति।' },
    { s:'dhuma', h:3,  en:'Hesitant courage, strained sibling ties, secretive efforts.',                                                     hi:'साहस में संकोच, भाई-बहनों से तनाव, गुप्त प्रयास।' },
    { s:'dhuma', h:4,  en:'Domestic unease, emotional fog, possible property disputes.',                                                     hi:'घरेलू अशांति, भावनात्मक धुंध, संभावित संपत्ति विवाद।' },
    { s:'dhuma', h:5,  en:'Distracted intellect, delays in progeny matters, overthinking.',                                                  hi:'विचलित बुद्धि, संतान संबंधी विलंब, अति-चिंतन।' },
    { s:'dhuma', h:6,  en:'Hidden enemies, chronic but masked ailments.',                                                                    hi:'छिपे हुए शत्रु, गुप्त किंतु पुराने रोग।' },
    { s:'dhuma', h:7,  en:'Misunderstandings in marriage, secretive partners.',                                                              hi:'वैवाहिक गलतफहमियाँ, गुप्त स्वभाव वाला साथी।' },
    { s:'dhuma', h:8,  en:'Obscured crises, sudden but veiled dangers; needs careful health monitoring.',                                    hi:'अस्पष्ट संकट, आकस्मिक परंतु छिपे खतरे; स्वास्थ्य पर सतर्कता आवश्यक।' },
    { s:'dhuma', h:9,  en:'Clouded faith, philosophical confusion, delayed fortune.',                                                        hi:'धुंधली आस्था, दार्शनिक भ्रम, भाग्य में विलंब।' },
    { s:'dhuma', h:10, en:'Behind-the-scenes career role, reputation challenges if afflicted.',                                              hi:'पर्दे के पीछे का व्यावसायिक कार्य, पीड़ित होने पर प्रतिष्ठा को चुनौती।' },
    { s:'dhuma', h:11, en:'Gains arrive through indirect or hidden means.',                                                                  hi:'अप्रत्यक्ष अथवा गुप्त साधनों से लाभ।' },
    { s:'dhuma', h:12, en:'Suited to introspective or monastic withdrawal; aids inner cleansing.',                                           hi:'आत्मनिरीक्षण अथवा सन्न्यास हेतु उपयुक्त; आंतरिक शुद्धि में सहायक।' },
    // ── Vyatipata
    { s:'vyatipata', h:1,  en:'Sudden personality shifts, accident-proneness.',                                                             hi:'आकस्मिक स्वभाव-परिवर्तन, दुर्घटना की प्रवृत्ति।' },
    { s:'vyatipata', h:2,  en:'Abrupt financial reversals, impulsive speech.',                                                              hi:'अचानक आर्थिक उलटफेर, आवेगी वाणी।' },
    { s:'vyatipata', h:3,  en:'Sudden conflicts with siblings, reckless courage.',                                                          hi:'भाई-बहनों से आकस्मिक विवाद, दुस्साहस।' },
    { s:'vyatipata', h:4,  en:'Disturbances at home, sudden relocation.',                                                                   hi:'घर में अशांति, आकस्मिक स्थानांतरण।' },
    { s:'vyatipata', h:5,  en:'Erratic intellect, complications around children.',                                                          hi:'अस्थिर बुद्धि, संतान संबंधी जटिलताएँ।' },
    { s:'vyatipata', h:6,  en:'Sudden health crises, unpredictable rivals.',                                                                hi:'आकस्मिक स्वास्थ्य संकट, अप्रत्याशित प्रतिद्वंद्वी।' },
    { s:'vyatipata', h:7,  en:'Turbulent marriage, unexpected separations.',                                                                hi:'अशांत विवाह, अप्रत्याशित वियोग।' },
    { s:'vyatipata', h:8,  en:'Significant caution needed; sudden upheavals affecting well-being.',                                         hi:'विशेष सावधानी आवश्यक; कल्याण को प्रभावित करने वाले आकस्मिक उलटफेर।' },
    { s:'vyatipata', h:9,  en:'Disrupted fortune, unconventional belief shifts.',                                                           hi:'बाधित भाग्य, अपरंपरागत विश्वास-परिवर्तन।' },
    { s:'vyatipata', h:10, en:'Career volatility, abrupt status changes.',                                                                  hi:'व्यावसायिक अस्थिरता, आकस्मिक प्रतिष्ठा-परिवर्तन।' },
    { s:'vyatipata', h:11, en:'Unstable gains, sudden windfalls or losses.',                                                               hi:'अस्थिर लाभ, आकस्मिक प्राप्ति अथवा हानि।' },
    { s:'vyatipata', h:12, en:'Sudden detachment or unexpected spiritual awakening.',                                                       hi:'आकस्मिक वैराग्य अथवा अप्रत्याशित आध्यात्मिक जागृति।' },
    // ── Parivesha
    { s:'parivesha', h:1,  en:'Charismatic presence, admired personality.',                                                                hi:'आकर्षक उपस्थिति, सराही जाने वाली व्यक्तित्व।' },
    { s:'parivesha', h:2,  en:'Wealth through charm, pleasant speech.',                                                                    hi:'आकर्षण से धन-प्राप्ति, सुखद वाणी।' },
    { s:'parivesha', h:3,  en:'Courageous yet graceful conduct, supportive siblings.',                                                     hi:'साहसी परंतु सौम्य व्यवहार, सहायक भाई-बहन।' },
    { s:'parivesha', h:4,  en:'Comfortable, attractive home environment.',                                                                 hi:'सुखद, आकर्षक गृह-वातावरण।' },
    { s:'parivesha', h:5,  en:'Creative intellect, charming children.',                                                                    hi:'सृजनात्मक बुद्धि, आकर्षक संतान।' },
    { s:'parivesha', h:6,  en:'Ability to win over rivals through diplomacy.',                                                             hi:'कूटनीति द्वारा प्रतिद्वंद्वियों पर विजय।' },
    { s:'parivesha', h:7,  en:'Attractive, harmonious marriage and partnerships.',                                                         hi:'आकर्षक, सामंजस्यपूर्ण विवाह व साझेदारी।' },
    { s:'parivesha', h:8,  en:'Protective grace during crises; resilience.',                                                               hi:'संकट के समय रक्षात्मक कृपा; सहनशीलता।' },
    { s:'parivesha', h:9,  en:'Fortunate, philosophically inspiring outlook.',                                                             hi:'सौभाग्यशाली, दार्शनिक रूप से प्रेरक दृष्टिकोण।' },
    { s:'parivesha', h:10, en:'Public recognition, career success and fame.',                                                              hi:'जन-मान्यता, व्यावसायिक सफलता तथा यश।' },
    { s:'parivesha', h:11, en:'Steady gains through reputation and connections.',                                                          hi:'प्रतिष्ठा व संपर्कों द्वारा स्थिर लाभ।' },
    { s:'parivesha', h:12, en:'Graceful detachment; spiritually uplifting closure.',                                                       hi:'सौम्य वैराग्य; आध्यात्मिक रूप से उन्नत समापन।' },
    // ── Indrachapa
    { s:'indrachapa', h:1,  en:'Optimistic, idealistic but inconsistent self-image.',                                                      hi:'आशावान, आदर्शवादी परंतु अस्थिर आत्म-बोध।' },
    { s:'indrachapa', h:2,  en:'Periodic financial gains, eloquent but inconsistent speech.',                                              hi:'समय-समय पर आर्थिक लाभ, वाक्पटु परंतु अस्थिर वाणी।' },
    { s:'indrachapa', h:3,  en:'Inspired courage, supportive yet variable sibling bonds.',                                                 hi:'प्रेरित साहस, सहायक परंतु परिवर्तनशील भाई-बहन संबंध।' },
    { s:'indrachapa', h:4,  en:'Pleasant but changeable domestic life.',                                                                   hi:'सुखद परंतु परिवर्तनशील घरेलू जीवन।' },
    { s:'indrachapa', h:5,  en:'Inspired learning, hopeful outlook on progeny.',                                                           hi:'प्रेरित अध्ययन, संतान के विषय में आशावान दृष्टिकोण।' },
    { s:'indrachapa', h:6,  en:'Temporary relief from rivals; brief advantages.',                                                          hi:'प्रतिद्वंद्वियों से अस्थायी राहत; क्षणिक लाभ।' },
    { s:'indrachapa', h:7,  en:'Hopeful but idealised view of marriage; needs realism.',                                                   hi:'विवाह के विषय में आशावान परंतु आदर्शीकृत दृष्टिकोण; यथार्थवाद आवश्यक।' },
    { s:'indrachapa', h:8,  en:'Brief reprieve from crises; transient relief.',                                                            hi:'संकट से क्षणिक राहत; अल्पकालिक मुक्ति।' },
    { s:'indrachapa', h:9,  en:'Inspired faith, philosophical idealism.',                                                                  hi:'प्रेरित आस्था, दार्शनिक आदर्शवाद।' },
    { s:'indrachapa', h:10, en:'Bursts of recognition; career success that may not be permanent.',                                         hi:'मान्यता के क्षणिक उभार; व्यावसायिक सफलता जो स्थायी न हो।' },
    { s:'indrachapa', h:11, en:'Sudden but short-lived gains.',                                                                            hi:'आकस्मिक परंतु अल्पकालिक लाभ।' },
    { s:'indrachapa', h:12, en:'Fleeting yet meaningful spiritual insights.',                                                              hi:'क्षणिक परंतु सार्थक आध्यात्मिक अंतर्दृष्टि।' },
    // ── Upaketu
    { s:'upaketu', h:1,  en:'Impulsive, restless personality; accident risk.',                                                             hi:'आवेगी, अस्थिरचित्त व्यक्तित्व; दुर्घटना का जोखिम।' },
    { s:'upaketu', h:2,  en:'Sudden expenses, sharp or hasty speech.',                                                                     hi:'आकस्मिक व्यय, तीखी अथवा शीघ्र वाणी।' },
    { s:'upaketu', h:3,  en:'Reckless courage, abrupt sibling rifts.',                                                                     hi:'दुस्साहस, भाई-बहनों से आकस्मिक मतभेद।' },
    { s:'upaketu', h:4,  en:'Domestic disturbances, possible fire-related risk at home.',                                                   hi:'घरेलू अशांति, घर में अग्नि-जोखिम की संभावना।' },
    { s:'upaketu', h:5,  en:'Restless intellect, complications with children.',                                                             hi:'अस्थिर बुद्धि, संतान संबंधी जटिलताएँ।' },
    { s:'upaketu', h:6,  en:'Sudden conflicts, health flare-ups.',                                                                          hi:'आकस्मिक विवाद, स्वास्थ्य में अचानक उभार।' },
    { s:'upaketu', h:7,  en:'Abrupt marital discord or sudden separations.',                                                                hi:'आकस्मिक वैवाहिक कलह अथवा वियोग।' },
    { s:'upaketu', h:8,  en:'Heightened caution needed; sudden crises.',                                                                    hi:'अधिक सतर्कता आवश्यक; आकस्मिक संकट।' },
    { s:'upaketu', h:9,  en:'Disrupted faith; unconventional, abrupt belief changes.',                                                      hi:'बाधित आस्था; अपरंपरागत, आकस्मिक विश्वास-परिवर्तन।' },
    { s:'upaketu', h:10, en:'Unconventional career turns; sudden professional disruption.',                                                  hi:'अपरंपरागत व्यावसायिक मोड़; आकस्मिक पेशेवर बाधा।' },
    { s:'upaketu', h:11, en:'Erratic gains; sudden but unstable income.',                                                                    hi:'अस्थिर लाभ; आकस्मिक परंतु अस्थायी आय।' },
    { s:'upaketu', h:12, en:'Sudden renunciation; abrupt spiritual turning point.',                                                          hi:'आकस्मिक वैराग्य; अप्रत्याशित आध्यात्मिक मोड़।' },
  ];

  for (const r of HOUSE_EFFECTS) {
    await knex('upagraha_house_effects')
      .insert({ upagraha_slug: r.s, house_number: r.h, effect_en: r.en, effect_hi: r.hi })
      .onConflict(['upagraha_slug', 'house_number']).merge();
  }

  // ── 3. Planet conjunction effects (5 × 9 = 45 rows) ──────────────────────────
  const CONJUNCTIONS = [
    // ── Dhuma
    { s:'dhuma', p:'Sun',     en:'Clouds self-confidence and authority; ego struggles.',                                    hi:'आत्मविश्वास तथा अधिकार को धुंधला करता है; अहंकार संघर्ष।' },
    { s:'dhuma', p:'Moon',    en:'Emotional fog, anxious mind, unsettled mother-relationship.',                             hi:'भावनात्मक धुंध, चिंतित मन, माता से अस्थिर संबंध।' },
    { s:'dhuma', p:'Mars',    en:'Suppressed courage, hidden aggression.',                                                  hi:'दबा हुआ साहस, गुप्त आक्रामकता।' },
    { s:'dhuma', p:'Mercury', en:'Confused communication, secretive intellect.',                                            hi:'भ्रमित संवाद, गुप्त बुद्धि।' },
    { s:'dhuma', p:'Jupiter', en:'Clouded wisdom, delayed higher learning.',                                                hi:'धुंधला ज्ञान, उच्च शिक्षा में विलंब।' },
    { s:'dhuma', p:'Venus',   en:'Hidden relationship troubles, subdued charm.',                                            hi:'गुप्त संबंध-समस्याएँ, दबा हुआ आकर्षण।' },
    { s:'dhuma', p:'Saturn',  en:'Reinforces obscurity, delay, and heaviness (both tamasic in nature).',                   hi:'धुंधलापन, विलंब तथा भारीपन को सुदृढ़ करता है (दोनों तामसिक स्वभाव)।' },
    { s:'dhuma', p:'Rahu',    en:'Intensifies confusion, obsession and hidden agendas.',                                    hi:'भ्रम, मोह तथा गुप्त उद्देश्यों को तीव्र करता है।' },
    { s:'dhuma', p:'Ketu',    en:'Deepens introspection but increases confusion.',                                          hi:'आत्मचिंतन को गहरा करता है परंतु भ्रम भी बढ़ाता है।' },
    // ── Vyatipata
    { s:'vyatipata', p:'Sun',     en:'Sudden ego clashes; volatile authority figures.',                                    hi:'आकस्मिक अहंकार-संघर्ष; अस्थिर सत्ताधारी व्यक्ति।' },
    { s:'vyatipata', p:'Moon',    en:'Emotional turbulence, mood swings, sudden domestic change.',                         hi:'भावनात्मक उथल-पुथल, मनोदशा परिवर्तन, आकस्मिक घरेलू बदलाव।' },
    { s:'vyatipata', p:'Mars',    en:'Explosive temper, accident-prone energy.',                                           hi:'विस्फोटक स्वभाव, दुर्घटना-प्रवृत्त ऊर्जा।' },
    { s:'vyatipata', p:'Mercury', en:'Erratic, sharp speech; sudden miscommunication.',                                    hi:'अस्थिर, तीखी वाणी; आकस्मिक गलतफहमी।' },
    { s:'vyatipata', p:'Jupiter', en:'Disrupted fortune, sudden philosophical shifts.',                                    hi:'बाधित भाग्य, आकस्मिक दार्शनिक परिवर्तन।' },
    { s:'vyatipata', p:'Venus',   en:'Sudden romantic upheavals, relationship volatility.',                                hi:'आकस्मिक प्रेम-उथल-पुथल, संबंधों में अस्थिरता।' },
    { s:'vyatipata', p:'Saturn',  en:'Compounds instability and sudden hardship.',                                         hi:'अस्थिरता तथा आकस्मिक कठिनाई को बढ़ाता है।' },
    { s:'vyatipata', p:'Rahu',    en:'Magnifies sudden, unpredictable upheavals.',                                         hi:'आकस्मिक, अप्रत्याशित उथल-पुथल को बढ़ाता है।' },
    { s:'vyatipata', p:'Ketu',    en:'Sudden spiritual or material upheaval.',                                             hi:'आकस्मिक आध्यात्मिक अथवा भौतिक उथल-पुथल।' },
    // ── Parivesha
    { s:'parivesha', p:'Sun',     en:'Halo of authority and respected leadership.',                                        hi:'अधिकार तथा सम्मानित नेतृत्व का तेजोमंडल।' },
    { s:'parivesha', p:'Moon',    en:'Emotionally radiant, popular, comforting presence.',                                 hi:'भावनात्मक रूप से तेजोमय, लोकप्रिय, सुखदायक उपस्थिति।' },
    { s:'parivesha', p:'Mars',    en:'Courageous yet graceful action.',                                                    hi:'साहसी परंतु सौम्य कर्म।' },
    { s:'parivesha', p:'Mercury', en:'Eloquent, charming communication skills.',                                           hi:'वाक्पटु, आकर्षक संवाद-कौशल।' },
    { s:'parivesha', p:'Jupiter', en:'Wise, graceful, well-respected counsel.',                                            hi:'विवेकपूर्ण, सौम्य तथा सम्मानित परामर्श।' },
    { s:'parivesha', p:'Venus',   en:'Enhanced charm, beauty and artistic success.',                                       hi:'बढ़ा हुआ आकर्षण, सौंदर्य तथा कलात्मक सफलता।' },
    { s:'parivesha', p:'Saturn',  en:"Tempers Saturn's harshness with grace and dignity.",                                 hi:'शनि की कठोरता को कृपा व गरिमा से शांत करता है।' },
    { s:'parivesha', p:'Rahu',    en:"Adds charisma to Rahu's worldly ambitions.",                                        hi:'राहु की सांसारिक महत्त्वाकांक्षा में आकर्षण जोड़ता है।' },
    { s:'parivesha', p:'Ketu',    en:'Graceful detachment; spiritually elevating influence.',                              hi:'सौम्य वैराग्य; आध्यात्मिक रूप से उन्नायक प्रभाव।' },
    // ── Indrachapa
    { s:'indrachapa', p:'Sun',     en:'Inspired but inconsistent self-expression.',                                        hi:'प्रेरित परंतु अस्थिर आत्म-अभिव्यक्ति।' },
    { s:'indrachapa', p:'Moon',    en:'Hopeful but fluctuating emotional life.',                                           hi:'आशावान परंतु अस्थिर भावनात्मक जीवन।' },
    { s:'indrachapa', p:'Mars',    en:'Bursts of inspired energy that may not last.',                                      hi:'प्रेरित ऊर्जा के क्षण जो स्थायी न हों।' },
    { s:'indrachapa', p:'Mercury', en:'Inspired but inconsistent intellect.',                                              hi:'प्रेरित परंतु अस्थिर बुद्धि।' },
    { s:'indrachapa', p:'Jupiter', en:'Idealistic wisdom; inspirational but fleeting insight.',                            hi:'आदर्शवादी ज्ञान; प्रेरक परंतु क्षणिक अंतर्दृष्टि।' },
    { s:'indrachapa', p:'Venus',   en:'Idealised romance; short-lived attractions.',                                       hi:'आदर्शीकृत प्रेम; अल्पकालिक आकर्षण।' },
    { s:'indrachapa', p:'Saturn',  en:'Brief relief from Saturnine restriction.',                                          hi:'शनि के अवरोध से क्षणिक राहत।' },
    { s:'indrachapa', p:'Rahu',    en:'Brief illusionary gains; idealism mixed with illusion.',                            hi:'क्षणिक मायावी लाभ; भ्रम से मिश्रित आदर्शवाद।' },
    { s:'indrachapa', p:'Ketu',    en:'Fleeting spiritual insight.',                                                       hi:'क्षणिक आध्यात्मिक अंतर्दृष्टि।' },
    // ── Upaketu
    { s:'upaketu', p:'Sun',     en:'Sudden, disruptive challenges to ego and status.',                                     hi:'अहंकार व प्रतिष्ठा हेतु आकस्मिक, विघटनकारी चुनौतियाँ।' },
    { s:'upaketu', p:'Moon',    en:'Restless mind, sudden emotional disturbances.',                                        hi:'अस्थिर मन, आकस्मिक भावनात्मक उथल-पुथल।' },
    { s:'upaketu', p:'Mars',    en:'Reckless, impulsive and accident-prone actions.',                                      hi:'दुस्साहसी, आवेगी तथा दुर्घटना-प्रवृत्त कर्म।' },
    { s:'upaketu', p:'Mercury', en:'Restless, scattered thinking; abrupt decisions.',                                      hi:'अस्थिर, बिखरी हुई सोच; आकस्मिक निर्णय।' },
    { s:'upaketu', p:'Jupiter', en:'Sudden detachment from conventional belief; abrupt renunciation.',                     hi:'परंपरागत विश्वास से आकस्मिक वैराग्य; अचानक सन्न्यास।' },
    { s:'upaketu', p:'Venus',   en:'Sudden relationship endings; detachment from pleasures.',                              hi:'आकस्मिक संबंध-समाप्ति; सुखों से वैराग्य।' },
    { s:'upaketu', p:'Saturn',  en:'Sudden, disruptive karmic challenges.',                                               hi:'आकस्मिक, विघटनकारी कार्मिक चुनौतियाँ।' },
    { s:'upaketu', p:'Rahu',    en:'Sudden, disruptive and unconventional outcomes.',                                      hi:'आकस्मिक, विघटनकारी तथा अपरंपरागत परिणाम।' },
    { s:'upaketu', p:'Ketu',    en:'Reinforces detachment and abrupt renunciation (both similar in nature).',              hi:'वैराग्य व आकस्मिक सन्न्यास को सुदृढ़ करता है (दोनों समान स्वभाव)।' },
  ];

  for (const r of CONJUNCTIONS) {
    await knex('upagraha_planet_conjunctions')
      .insert({ upagraha_slug: r.s, planet_slug: r.p, effect_en: r.en, effect_hi: r.hi })
      .onConflict(['upagraha_slug', 'planet_slug']).merge();
  }
};
